<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure to delete this item?' => 'Ви впевнені, що хочете видалити даний елемент?',
  'Delete' => 'Видалити',
  'Displaying {start}-{end} of {count} result(s).' => 'Елементи {start}—{end} з {count}.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Для CDataColumn необхідно вказати "name" або "value".',
  'No results found.' => 'Нема результатів.',
  'Not set' => 'Не задано',
  'Please specify the "attributes" property.' => 'Будь ласка визначте властивість "attributes".',
  'Please specify the "data" property.' => 'Будь ласка визначте властивість "data".',
  'Sort by: ' => 'Сортування за: ',
  'The "dataProvider" property cannot be empty.' => 'Властивість "dataProvider" не може бути порожнім.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Атрибут повинен бути визначений у форматі "Ім\'я:Тип:Заголовок". "Тип" і "Заголовок" не обов\'язкові.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Стовпець повинен бути визначений у форматі "Ім\'я:Тип:Заголовок". "Тип" і "Заголовок" не обов\'язкові.',
  'The property "itemView" cannot be empty.' => 'Властивість "itemView" не може бути порожнім.',
  'Total {count} result(s).' => 'Всього результатів: {count}.',
  'Update' => 'Редагувати',
  'View' => 'Переглянути',
  '{class} must specify "model" and "attribute" or "name" property values.' => 'У класі {class} повинні визначатись "model" і "attribute" або значення "name".',
);
