<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Either "name" or "value" must be specified for CDataColumn.' => 'Или "name" или "value" трябва да бъдат посочени за CDataColumn.',
  'Please specify the "data" property.' => 'Моля, посочете "data" свойството.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Колоната трябва да бъде посочена във формат "Name:Typ:Label", където "Typ" и "Label" не са задължителни.',
  'Are you sure to delete this item?' => 'Сигурен ли сте че искате да изтриете това?',
  'Delete' => 'Изтрии',
  'Displaying {start}-{end} of {count} result(s).' => 'Показване на {start}-{end} от {count}.',
  'No results found.' => 'Няма намерени резултати.',
  'Not set' => 'Не е посочено',
  'Please specify the "attributes" property.' => 'Моля, посочете "attributes" свойството.',
  'Sort by: ' => 'Сотриране по:',
  'The "dataProvider" property cannot be empty.' => 'Свойството "dataProvider" не може да бъде празно.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Свойството трябва да бъде въведено във формат "Name:Typ:Label", където "Typ" и "Label" не са задължителни.',
  'The property "itemView" cannot be empty.' => 'Свойството "itemView" не може да бъде празно.',
  'Total {count} result(s).' => 'Общо {count} резултата',
  'Update' => 'Редактиране',
  'View' => 'Преглед',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} трябва да има отбелязани "model" или "attribute" или "name" свойства.',
);

?>
