<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER không chứa {vars}',
  '$_SERVER variable' => 'Biến $_SERVER',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] phải giống đường dẫn của file khởi động',
  'APC extension' => 'APC extension',
  'All <a href="https://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Tất cả <a href="https://www.yiiframework.com/doc/api/#system.db">các lớp liên quan đến CSDL</a>',
  'DOM extension' => 'DOM extension',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Biến $_SERVER["REQUEST_URI"] hoặc $_SERVER["QUERY_STRING"] phải tồn tại.',
  'GD extension' => 'GD extension',
  'Mcrypt extension' => 'Mcrypt extension',
  'Memcache extension' => 'Memcache extension',
  'PCRE extension' => 'PCRE extension',
  'PDO MySQL extension' => 'PDO MySQl extension',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL extension',
  'PDO SQLite extension' => 'PDO SQLite extension',
  'PDO extension' => 'PDO extension',
  'PHP 5.1.0 or higher is required.' => 'Phải có PHP 5.1.0 hoặc mới hơn',
  'PHP version' => 'Phiên bản PHP',
  'Reflection extension' => 'Reflection extension',
  'SOAP extension' => 'SOAP extension',
  'SPL extension' => 'SPL extension',
  'This is required if you are using MySQL database.' => 'Cần phải có nếu bạn dùng MySQL',
  'This is required if you are using PostgreSQL database.' => 'Cần phải có nếu bạn dùng PostgreSQL',
  'This is required if you are using SQLite database.' => 'Cần phải có nếu bạn dùng SQLite',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Không xác định được thông tin đường dẫn URL. Hãy kiểm tra đảm bảo $_SERVER["PATH_INFO"] (hoặc $_SERVER["PHP_SELF"] và $_SERVER["SCRIPT_NAME"]) có giá trị đúng.',
);
