<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'This is required by encrypt and decrypt methods.' => 'Nevyhnutné pre kryptovacie a dekryptovacie metódy.',
  '$_SERVER does not have {vars}.' => '$_SERVER nenašiel {vars}.',
  '$_SERVER variable' => '$_SERVER premenná',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] musí ukazovať na štartovací skript.',
  'APC extension' => 'APC rozšírenie',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Všetky <a href="http://www.yiiframework.com/doc/api/#system.db">objekty vzťahujúce sa k databáze</a>',
  'DOM extension' => 'DOM rozšírenie',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"] alebo $_SERVER["QUERY_STRING"] musia existovať.',
  'GD extension' => 'GD rozšírenie',
  'Mcrypt extension' => 'Mcrypt rozšírenie',
  'Memcache extension' => 'Memcache rozšírenie',
  'PCRE extension' => 'PCRE rozšírenie',
  'PDO MySQL extension' => 'PDO MySQL rozšírenie',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL rozšírenie',
  'PDO SQLite extension' => 'PDO SQLite rozšírenie',
  'PDO extension' => 'PDO rozšírenie',
  'PHP 5.1.0 or higher is required.' => 'Je potrebná verzia PHP 5.1.0 alebo vyššia.',
  'PHP version' => 'PHP verzia',
  'Reflection extension' => 'Reflection rozšírenie',
  'SOAP extension' => 'SOAP rozšírenie',
  'SPL extension' => 'SPL rozšírenie',
  'This is required if you are using MySQL database.' => 'Potrebné v prípade využitia databázy mySQL.',
  'This is required if you are using PostgreSQL database.' => 'Potrebné v prípade využitia databázy PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Potrebné v prípade využitia databázy SQLite.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Nepodarilo sa zistiť informácie o URL linke. Ubezúpečte sa, že $_SERVER["PATH_INFO"] (alebo $_SERVER["PHP_SELF"] a $_SERVER["SCRIPT_NAME"]) obsahuje správne hodnoty.',
);
