<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'The property updateSelector should be defined.' => 'Η ιδιότητα updateSelector πρέπει να οριστεί.',
  'Are you sure you want to delete this item?' => 'Είστε σίγουρος ότι θέλετε να διαγράψετε το αντικείμενο;',
  'Delete' => 'Διαγραφή',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Εμφάνιση {start}-{end} από {count} των αποτελεσμάτων.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Πρέπει να οριστεί είτε το "όνομα" είτε η "τιμή" για το CDataColumn.',
  'Home' => 'Αρχή',
  'No results found.' => 'Δεν υπάρχουν αποτελέσματα.',
  'Not set' => 'Δεν έχει οριστεί',
  'Please specify the "attributes" property.' => 'Καθορίστε την ιδιότητα "attributes".',
  'Please specify the "data" property.' => 'Καθορίστε την ιδιότητα "data".',
  'Sort by: ' => 'Ταξινόμηση κατά: ',
  'The "dataProvider" property cannot be empty.' => 'Η ιδιότητα "dataProvider" δεν μπορεί να μην έχει τιμή.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Η ιδιότητα πρέπει να οριστεί στη μορφή "Όνομα:Τύπος:Ετικέτα", όπου "Τύπος" και "Ετικέτα" είναι προαιρετικά.',
  'The button type "{type}" is not supported.' => 'Ο τύπος κουμπιού "{type}" δεν υποστηρίζεται.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Η στήλη πρέπει να οριστεί στη μορφή "Όνομα:Τύπος:Ετικέτα", όπου "Τύπος" και "Ετικέτα" είναι προαιρετικά.',
  'The property "itemView" cannot be empty.' => 'Η ιδιότητα "itemView" δεν μπορεί να μην έχει τιμή.',
  'Total 1 result.|Total {count} results.' => 'Συνολικά {count} αποτελέσματα.',
  'Update' => 'Ενημέρωση',
  'View' => 'Εμφάνιση',
  '{class} must specify "model" and "attribute" or "name" property values.' => 'Το {class} πρέπει να ορίζει τις ιδιότητες "model" και "attribute" ή "name".',
);
