<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'GD extension with<br />FreeType support' => 'GD-tillägg med<br />FreeType-stöd',
  'GD installed<br />FreeType support not installed' => 'GD installerad<br />FreeType-stöd ej installerat',
  'GD not installed' => 'GD ej installerat',
  '$_SERVER does not have {vars}.' => '$_SERVER innehåller inte {vars}.',
  '$_SERVER variable' => '$_SERVER-variabel',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] måste vara samma som startskriptets namn och sökväg.',
  'APC extension' => 'APC-tillägg',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Alla <a href="http://www.yiiframework.com/doc/api/#system.db">DB-relaterade klasser</a>',
  'DOM extension' => 'DOM-tillägg',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Antingen $_SERVER["REQUEST_URI"] eller $_SERVER["QUERY_STRING"] måste finnas.',
  'Mcrypt extension' => 'Mcrypt-tillägg',
  'Memcache extension' => 'Memcache-tillägg',
  'PCRE extension' => 'PCRE-tillägg',
  'PDO MySQL extension' => 'PDO MySQL-tillägg',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL-tillägg',
  'PDO SQLite extension' => 'PDO SQLite-tillägg',
  'PDO extension' => 'PDO-tillägg',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0 eller senare krävs',
  'PHP version' => 'PHP-version',
  'Reflection extension' => 'Reflection-tillägg',
  'SOAP extension' => 'SOAP-tillägg',
  'SPL extension' => 'SPL-tillägg',
  'This is required by encrypt and decrypt methods.' => 'Detta krävs av krypterings- och dekrypteringsmetoderna',
  'This is required if you are using MySQL database.' => 'Detta krävs om MySQL-databas används.',
  'This is required if you are using PostgreSQL database.' => 'Detta krävs om PostgresSQL-databas används.',
  'This is required if you are using SQLite database.' => 'Detta krävs om SQLite-databas används.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Kan inte avgöra URL:ens sökvägsinfo. Kontrollera att $_SERVER["PATH_INFO"] (eller $_SERVER["PHP_SELF"] och $_SERVER["SCRIPT_NAME"]) innehåller korrekta värden.',
);
