<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure you want to delete this item?' => 'Voulez-vous vraiment supprimer cet élément ?',
  'Delete' => 'Supprimer',
  'Displaying {start}-{end} of {count} result(s).' => 'Afficher les résultats de {start} à {end} (total de {count})',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Soit "name", soit "value" doivent être définis pour CDataColumn.',
  'No results found.' => 'Aucun résultat trouvé.',
  'Not set' => 'Non défini',
  'Please specify the "attributes" property.' => 'Veuillez définir la propriété « attributes ».',
  'Please specify the "data" property.' => 'Veuillez définir la propriété « data ».',
  'Sort by: ' => 'Trier par : ',
  'The "dataProvider" property cannot be empty.' => 'La propriété « dataProvider » ne peut être vide.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'L\'attribut doit être défini selon le format « Name:Type:Label », où « Type » et « Label » sont optionnels.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'La colonne doit être définie selon le format « Name:Type:Label », où « Type » et « Label » sont optionnels.',
  'The property "itemView" cannot be empty.' => 'La propriété « itemView » ne peut être vide.',
  'Total {count} result(s).' => 'Total de {count} résultat(s).',
  'Update' => 'Mettre à jour',
  'View' => 'Voir',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} doit définir les valeurs des propriétés « model » et « attribute » ou « name ».',
);
