<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure you want to delete this item?' => 'Seguro que desea borrar este elemento?',
  'Delete' => 'Borrar',
  'Displaying {start}-{end} of {count} result(s).' => 'Desplegando {start}-{end} de {count} resultado(s).',
  'Either "name" or "value" must be specified for CDataColumn.' => '"name" o "value" deben especificarse para CDataColumn.',
  'No results found.' => 'No se encontraron resultados.',
  'Not set' => 'No asignado',
  'Please specify the "attributes" property.' => 'Favor de especificar la propiedad "attributes".',
  'Please specify the "data" property.' => 'Favor de especificar la propiedad "data".',
  'Sort by: ' => 'Ordenar por: ',
  'The "dataProvider" property cannot be empty.' => 'La propiedad "dataProvider" no puede estar vacia.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'El atributo debe especificarse en el formato "Nombre:Tipo:Etiqueta", donde "Tipo" y "Etiqueta" son opcionales.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'La columna debe especificarse en el formato "Nombre:Tipo:Etiqueta", donde "Tipo" y "Etiqueta" son opcionales.',
  'The property "itemView" cannot be empty.' => 'La propiedad "itemView" no puede estar vacia.',
  'Total {count} result(s).' => 'Total de {count} resultado(s).',
  'Update' => 'Actualiza',
  'View' => 'Mostrar',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} doit définir les valeurs des propriétés « model » et « attribute » ou « name ».',
);
