<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: yii.php 2164 2011-06-23 13:46:17Z yiifrmwrk@lourdas.name $
 */
return array (
  'Ctype extension' => 'Επέκταση Ctype',
  '$_SERVER does not have {vars}.' => 'Ο πίνακας $_SERVER δεν περιέχει τη(τις) μεταβλητή(-ές) {vars}.',
  '$_SERVER variable' => 'Μεταβλητή $_SERVER',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => 'Το $_SERVER["SCRIPT_FILENAME"] πρέπει να είναι το ίδιο με το αρχικό αρχείο σεναρίου.',
  'APC extension' => 'Επέκταση APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Όλες οι <a href="http://www.yiiframework.com/doc/api/#system.db">σχετικές με βάση κλάσεις</a>',
  'DOM extension' => 'Επέκταση DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Πρέπει να υπάρχει είτε το $_SERVER["REQUEST_URI"] είτε το $_SERVER["QUERY_STRING"].',
  'GD extension with<br />FreeType support' => 'Επέκταση GD με<br />υποστήριξη για FreeType',
  'GD installed<br />FreeType support not installed' => 'Επέκταση GD εγκατεστημένη<br />υποστήριξη FreeType δεν υπάρχει.',
  'GD not installed' => 'Δεν είναι εγκατεστημένη η επέκταση GD',
  'Mcrypt extension' => 'Επέκταση Mcrypt',
  'Memcache extension' => 'Επέκταση Memcache',
  'PCRE extension' => 'Επέκταση PCRE',
  'PDO MySQL extension' => 'Επέκταση PDO MySQL',
  'PDO PostgreSQL extension' => 'Επέκταση PDO PostgreSQL',
  'PDO SQLite extension' => 'Επέκταση PDO SQLite',
  'PDO extension' => 'Επέκταση PDO',
  'PHP 5.1.0 or higher is required.' => 'Απαιτείται PHP 5.1.0 ή μεγαλύτερης έκδοσης.',
  'PHP version' => 'Έκδοση PHP',
  'Reflection extension' => 'Επέκταση Reflection',
  'SOAP extension' => 'Επέκταση SOAP',
  'SPL extension' => 'Επέκταση SPL',
  'This is required by encrypt and decrypt methods.' => 'Απαιτείται από τις μεθόδους κρυπτογράφησης και αποκρυπτογράφησης.',
  'This is required if you are using MySQL database.' => 'Απαιτείται αν χρησιμοποιείτε βάση MySQL.',
  'This is required if you are using PostgreSQL database.' => 'Απαιτείται αν χρησιμοποιείτε βάση PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Απαιτείται αν χρησιμοποιείτε βάση SQLite.',
  'To use memcached set <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => 'Για να χρησιμοποιήσετε memcached, ορίστε το <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> να είναι <code>true</code>.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Δεν ήταν δυνατός ο καθορισμός της διαδρομής URL. Σιγουρευτείτε ότι το $_SERVER["PATH_INFO"] (ή $_SERVER["PHP_SELF"] και $_SERVER["SCRIPT_NAME"]) περιέχει τη σωστή τιμή.',
);
