<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER 中沒有 {vars}.',
  '$_SERVER variable' => '$_SERVER 變數',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] 必須與入口腳本檔案路徑一致.',
  'APC extension' => '',
  'All <a href="https://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => '所有 <a href="https://www.yiiframework.com/doc/api/#system.db">資料庫相關的類別</a>',
  'DOM extension' => '',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"] 或 $_SERVER["QUERY_STRING"] 必須存在.',
  'GD extension' => '',
  'Mcrypt extension' => '',
  'Memcache extension' => '',
  'PCRE extension' => '',
  'PDO MySQL extension' => '',
  'PDO PostgreSQL extension' => '',
  'PDO SQLite extension' => '',
  'PDO extension' => '',
  'PHP 5.1.0 or higher is required.' => '需要 PHP 5.1.0 或之後的版本.',
  'PHP version' => 'PHP 版本',
  'Reflection extension' => '',
  'SOAP extension' => '',
  'SPL extension' => '',
  'This is required if you are using MySQL database.' => '當使用 MySQL 資料庫時, 此項為必要.',
  'This is required if you are using PostgreSQL database.' => '當使用 PostgreSQL 資料庫時, 此項為必要.',
  'This is required if you are using SQLite database.' => '當使用 SQLite 資料庫時, 此項為必要.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => '無法確認 URL 路徑資訊. 請確定 $_SERVER["PATH_INFO"] (或 $_SERVER["PHP_SELF"] 與 $_SERVER["SCRIPT_NAME"]) 包含適當的值.',
);
