<?php
/**
 * Locale data for 'aa_ER_SAAHO'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.34',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'DJF' => 'FD',
    'ERN' => '$',
    'ETB' => 'ETB',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Qunxa Garablu',
      2 => 'Kudo',
      3 => 'Ciggilta Kudo',
      4 => 'Agda Baxis',
      5 => 'Caxah Alsa',
      6 => 'Qasa Dirri',
      7 => 'Qado Dirri',
      8 => 'Liiqen',
      9 => 'Waysu',
      10 => 'Diteli',
      11 => 'Ximoli',
      12 => 'Kaxxa Garablu',
    ),
    'abbreviated' => 
    array (
      1 => 'Qun',
      2 => 'Nah',
      3 => 'Cig',
      4 => 'Agd',
      5 => 'Cax',
      6 => 'Qas',
      7 => 'Qad',
      8 => 'Leq',
      9 => 'Way',
      10 => 'Dit',
      11 => 'Xim',
      12 => 'Kax',
    ),
    'narrow' => 
    array (
      1 => 'Q',
      2 => 'N',
      3 => 'C',
      4 => 'A',
      5 => 'C',
      6 => 'Q',
      7 => 'Q',
      8 => 'L',
      9 => 'W',
      10 => 'D',
      11 => 'X',
      12 => 'K',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Naba Sambat',
      1 => 'Sani',
      2 => 'Salus',
      3 => 'Rabuq',
      4 => 'Camus',
      5 => 'Jumqata',
      6 => 'Qunxa Sambat',
    ),
    'abbreviated' => 
    array (
      0 => 'Nab',
      1 => 'San',
      2 => 'Sal',
      3 => 'Rab',
      4 => 'Cam',
      5 => 'Jum',
      6 => 'Qun',
    ),
    'narrow' => 
    array (
      0 => 'A',
      1 => 'E',
      2 => 'T',
      3 => 'A',
      4 => 'K',
      5 => 'G',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'Yaasuusuk Duma',
      1 => 'Yaasuusuk Wadir',
    ),
    'wide' => 
    array (
      0 => 'Yaasuusuk Duma',
      1 => 'Yaasuusuk Wadir',
    ),
    'narrow' => 
    array (
      0 => 'Yaasuusuk Duma',
      1 => 'Yaasuusuk Wadir',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, MMMM dd, yyyy',
    'long' => 'dd MMMM yyyy',
    'medium' => 'dd-MMM-yyyy',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'saaku',
  'pmName' => 'carra',
);
