<?php
/**
 * Locale data for 'ar_SY'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.48',
  'numberSymbols' => 
  array (
    'decimal' => '٫',
    'group' => '٬',
    'list' => '؛',
    'percentSign' => '٪',
    'nativeZeroDigit' => '٠',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'اس',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'ليس رقم',
  ),
  'decimalFormat' => '#0.###;#0.###-',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#0.00',
  'currencySymbols' => 
  array (
    'BRL' => '.‏ر.ب',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '.‏ر.ه',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'AED' => 'د.إ.‏',
    'BHD' => 'د.ب.‏',
    'CNY' => 'ى.ص',
    'DZD' => 'د.ج.‏',
    'EGP' => 'ج.م.‏',
    'IQD' => 'د.ع.‏',
    'JOD' => 'د.أ.‏',
    'KMF' => '.‏ف.ج.ق',
    'KWD' => 'د.ك.‏',
    'LBP' => 'ل.ل.‏',
    'LYD' => 'د.ل.‏',
    'MAD' => 'د.م.‏',
    'MRO' => '.‏أ.م',
    'OMR' => 'ر.ع.‏',
    'QAR' => 'ر.ق.‏',
    'RUB' => 'ر.ر.‏',
    'SAR' => 'ر.س.‏',
    'SDD' => '.‏د.س',
    'SDP' => 'ج.س.‏',
    'SYP' => 'ل.س.‏',
    'TND' => 'د.ت.‏',
    'XAF' => '.‏ف.ا',
    'XXX' => '***',
    'YER' => 'ر.ي.‏',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'كانون الثاني',
      2 => 'شباط',
      3 => 'آذار',
      4 => 'نيسان',
      5 => 'نوار',
      6 => 'حزيران',
      7 => 'تموز',
      8 => 'آب',
      9 => 'أيلول',
      10 => 'تشرين الأول',
      11 => 'تشرين الثاني',
      12 => 'كانون الأول',
    ),
    'abbreviated' => 
    array (
      1 => 'كانون الثاني',
      2 => 'شباط',
      3 => 'آذار',
      4 => 'نيسان',
      5 => 'نوار',
      6 => 'حزيران',
      7 => 'تموز',
      8 => 'آب',
      9 => 'أيلول',
      10 => 'تشرين الأول',
      11 => 'تشرين الثاني',
      12 => 'كانون الأول',
    ),
    'narrow' => 
    array (
      1 => 'ي',
      2 => 'ف',
      3 => 'م',
      4 => 'أ',
      5 => 'و',
      6 => 'ن',
      7 => 'ل',
      8 => 'غ',
      9 => 'س',
      10 => 'ك',
      11 => 'ب',
      12 => 'د',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'الأحد',
      1 => 'الاثنين',
      2 => 'الثلاثاء',
      3 => 'الأربعاء',
      4 => 'الخميس',
      5 => 'الجمعة',
      6 => 'السبت',
    ),
    'abbreviated' => 
    array (
      0 => 'الأحد',
      1 => 'الاثنين',
      2 => 'الثلاثاء',
      3 => 'الأربعاء',
      4 => 'الخميس',
      5 => 'الجمعة',
      6 => 'السبت',
    ),
    'narrow' => 
    array (
      0 => 'ح',
      1 => 'ن',
      2 => 'ث',
      3 => 'ر',
      4 => 'خ',
      5 => 'ج',
      6 => 'س',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ق.م',
      1 => 'م',
    ),
    'wide' => 
    array (
      0 => 'قبل الميلاد',
      1 => 'ميلادي',
    ),
    'narrow' => 
    array (
      0 => 'ق.م',
      1 => 'م',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE، d MMMM، yyyy',
    'long' => 'd MMMM، yyyy',
    'medium' => 'dd‏/MM‏/yyyy',
    'short' => 'd‏/M‏/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'v h:mm:ss a',
    'long' => 'z h:mm:ss a',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'ص',
  'pmName' => 'م',
);
