<?php
/**
 * Locale data for 'as_IN'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.37',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##,##0%',
  'currencyFormat' => '¤ #,##,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => 'টকা',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'জানুয়াৰী',
      2 => 'ফেব্ৰুয়াৰী',
      3 => 'মাৰ্চ',
      4 => 'এপ্ৰিল',
      5 => 'মে',
      6 => 'জুন',
      7 => 'জুলাই',
      8 => 'আগষ্ট',
      9 => 'সেপ্টেম্বৰ',
      10 => 'অক্টোবৰ',
      11 => 'নভেম্বৰ',
      12 => 'ডিসেম্বৰ',
    ),
    'abbreviated' => 
    array (
      1 => 'জানু',
      2 => 'ফেব্ৰু',
      3 => 'মাৰ্চ',
      4 => 'এপ্ৰিল',
      5 => 'মে',
      6 => 'জুন',
      7 => 'জুলাই',
      8 => 'আগ',
      9 => 'সেপ্ট',
      10 => 'অক্টো',
      11 => 'নভে',
      12 => 'ডিসে',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'দেওবাৰ',
      1 => 'সোমবাৰ',
      2 => 'মঙ্গলবাৰ',
      3 => 'বুধবাৰ',
      4 => 'বৃহষ্পতিবাৰ',
      5 => 'শুক্ৰবাৰ',
      6 => 'শনিবাৰ',
    ),
    'abbreviated' => 
    array (
      0 => 'ৰবি',
      1 => 'সোম',
      2 => 'মঙ্গল',
      3 => 'বুধ',
      4 => 'বৃহষ্পতি',
      5 => 'শুক্ৰ',
      6 => 'শনি',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM, yyyy',
    'long' => 'd MMMM, yyyy',
    'medium' => 'dd-MM-yyyy',
    'short' => 'd-M-yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h.mm.ss a v',
    'long' => 'h.mm.ss a z',
    'medium' => 'h.mm.ss a',
    'short' => 'h.mm. a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'পূৰ্বা',
  'pmName' => 'অপ',
);
