<?php
/**
 * Locale data for 'be_BY'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.45',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => '£',
    'INR' => 'Rs.',
    'ITL' => 'IT₤',
    'JPY' => '¥',
    'USD' => '$',
    'AUD' => '$A',
    'BYB' => 'Руб',
    'RUB' => 'рас. руб.',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'студзень',
      2 => 'люты',
      3 => 'сакавік',
      4 => 'красавік',
      5 => 'май',
      6 => 'чэрвень',
      7 => 'ліпень',
      8 => 'жнівень',
      9 => 'верасень',
      10 => 'кастрычнік',
      11 => 'лістапад',
      12 => 'снежань',
    ),
    'abbreviated' => 
    array (
      1 => 'сту',
      2 => 'лют',
      3 => 'сак',
      4 => 'кра',
      5 => 'май',
      6 => 'чэр',
      7 => 'ліп',
      8 => 'жні',
      9 => 'вер',
      10 => 'кас',
      11 => 'ліс',
      12 => 'сне',
    ),
    'narrow' => 
    array (
      5 => 'м',
      1 => 'с',
      2 => 'л',
      3 => 'с',
      4 => 'к',
      6 => 'ч',
      7 => 'л',
      8 => 'ж',
      9 => 'в',
      10 => 'к',
      11 => 'л',
      12 => 'с',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'нядзеля',
      1 => 'панядзелак',
      2 => 'аўторак',
      3 => 'серада',
      4 => 'чацвер',
      5 => 'пятніца',
      6 => 'субота',
    ),
    'abbreviated' => 
    array (
      0 => 'нд',
      1 => 'пн',
      2 => 'аў',
      3 => 'ср',
      4 => 'чц',
      5 => 'пт',
      6 => 'сб',
    ),
    'narrow' => 
    array (
      0 => 'н',
      1 => 'п',
      2 => 'а',
      3 => 'с',
      4 => 'ч',
      5 => 'п',
      6 => 'с',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'да н.е.',
      1 => 'н.е.',
    ),
    'wide' => 
    array (
      0 => 'да н.э.',
      1 => 'н.э.',
    ),
    'narrow' => 
    array (
      0 => 'да н.э.',
      1 => 'н.э.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'd.M.yyyy',
    'short' => 'd.M.yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH.mm.ss v',
    'long' => 'HH.mm.ss z',
    'medium' => 'HH.mm.ss',
    'short' => 'HH.mm',
  ),
  'dateTimeFormat' => '{0} {1}',
  'amName' => 'да палудня',
  'pmName' => 'пасля палудня',
);
