<?php
/**
 * Locale data for 'bn_IN'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.56',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '০',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##,##0%',
  'currencyFormat' => '#,##,##0.00¤;(#,##,##0.00¤)',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => 'টাকা',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'BDT' => '৳',
    'XXX' => 'XXX',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'জানুয়ারী',
      2 => 'ফেব্রুয়ারী',
      3 => 'মার্চ',
      4 => 'এপ্রিল',
      5 => 'মে',
      6 => 'জুন',
      7 => 'জুলাই',
      8 => 'আগস্ট',
      9 => 'সেপ্টেম্বর',
      10 => 'অক্টোবর',
      11 => 'নভেম্বর',
      12 => 'ডিসেম্বর',
    ),
    'abbreviated' => 
    array (
      1 => 'জানুয়ারী',
      2 => 'ফেব্রুয়ারী',
      3 => 'মার্চ',
      4 => 'এপ্রিল',
      5 => 'মে',
      6 => 'জুন',
      7 => 'জুলাই',
      8 => 'আগস্ট',
      9 => 'সেপ্টেম্বর',
      10 => 'অক্টোবর',
      11 => 'নভেম্বর',
      12 => 'ডিসেম্বর',
    ),
    'narrow' => 
    array (
      1 => 'জা',
      2 => 'ফে',
      3 => 'মা',
      4 => 'এ',
      5 => 'মে',
      6 => 'জুন',
      7 => 'জু',
      8 => 'আ',
      9 => 'সে',
      10 => 'অ',
      11 => 'ন',
      12 => 'ডি',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'রবিবার',
      1 => 'সোমবার',
      2 => 'মঙ্গলবার',
      3 => 'বুধবার',
      4 => 'বৃহষ্পতিবার',
      5 => 'শুক্রবার',
      6 => 'শনিবার',
    ),
    'abbreviated' => 
    array (
      0 => 'রবি',
      1 => 'সোম',
      2 => 'মঙ্গল',
      3 => 'বুধ',
      4 => 'বৃহস্পতি',
      5 => 'শুক্র',
      6 => 'শনি',
    ),
    'narrow' => 
    array (
      0 => 'র',
      1 => 'সো',
      2 => 'ম',
      3 => 'বু',
      4 => 'বৃ',
      5 => 'শু',
      6 => 'শ',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'খৃষ্টপূর্ব',
      1 => 'খৃষ্টাব্দ',
    ),
    'wide' => 
    array (
      0 => 'খৃষ্টপূর্ব',
      1 => 'খৃষ্টাব্দ',
    ),
    'narrow' => 
    array (
      0 => 'খৃষ্টপূর্ব',
      1 => 'খৃষ্টাব্দ',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM, yyyy',
    'long' => 'd MMMM, yyyy',
    'medium' => 'd MMM, yyyy',
    'short' => 'd/M/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'পূর্বাহ্ণ',
  'pmName' => 'অপরাহ্ণ',
);
