<?php
/**
 * Locale data for 'byn_ER'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.36',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'CNY' => 'Y',
    'ETB' => '$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ልደትሪ',
      2 => 'ካብኽብቲ',
      3 => 'ክብላ',
      4 => 'ፋጅኺሪ',
      5 => 'ክቢቅሪ',
      6 => 'ምኪኤል ትጟኒሪ',
      7 => 'ኰርኩ',
      8 => 'ማርያም ትሪ',
      9 => 'ያኸኒ መሳቅለሪ',
      10 => 'መተሉ',
      11 => 'ምኪኤል መሽወሪ',
      12 => 'ተሕሳስሪ',
    ),
    'abbreviated' => 
    array (
      1 => 'ልደት',
      2 => 'ካብኽ',
      3 => 'ክብላ',
      4 => 'ፋጅኺ',
      5 => 'ክቢቅ',
      6 => 'ም/ት',
      7 => 'ኰር',
      8 => 'ማርያ',
      9 => 'ያኸኒ',
      10 => 'መተሉ',
      11 => 'ም/ም',
      12 => 'ተሕሳ',
    ),
    'narrow' => 
    array (
      1 => 'ል',
      2 => 'ካ',
      3 => 'ክ',
      4 => 'ፋ',
      5 => 'ክ',
      6 => 'ም',
      7 => 'ኰ',
      8 => 'ማ',
      9 => 'ያ',
      10 => 'መ',
      11 => 'ም',
      12 => 'ተ',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ሰንበር ቅዳዅ',
      1 => 'ሰኑ',
      2 => 'ሰሊጝ',
      3 => 'ለጓ ወሪ ለብዋ',
      4 => 'ኣምድ',
      5 => 'ኣርብ',
      6 => 'ሰንበር ሽጓዅ',
    ),
    'abbreviated' => 
    array (
      0 => 'ሰ/ቅ',
      1 => 'ሰኑ',
      2 => 'ሰሊጝ',
      3 => 'ለጓ',
      4 => 'ኣምድ',
      5 => 'ኣርብ',
      6 => 'ሰ/ሽ',
    ),
    'narrow' => 
    array (
      0 => 'ሰ',
      1 => 'ሰ',
      2 => 'ሰ',
      3 => 'ለ',
      4 => 'ኣ',
      5 => 'ኣ',
      6 => 'ሰ',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ይጅ',
      1 => 'ኣድ',
    ),
    'wide' => 
    array (
      0 => 'ይጅ',
      1 => 'ኣድ',
    ),
    'narrow' => 
    array (
      0 => 'ይጅ',
      1 => 'ኣድ',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE፡ dd MMMM ግርጋ yyyy G',
    'long' => 'dd MMMM yyyy',
    'medium' => 'dd-MMM-yyyy',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'ፋዱስ ጃብ',
  'pmName' => 'ፋዱስ ደምቢ',
);
