<?php
/**
 * Locale data for 'ca'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.90',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'CYP' => '£C',
    'ESP' => '₧',
    'IEP' => 'IR£',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'de gener',
      2 => 'de febrer',
      3 => 'de març',
      4 => 'd\'abril',
      5 => 'de maig',
      6 => 'de juny',
      7 => 'de juliol',
      8 => 'd\'agost',
      9 => 'de setembre',
      10 => 'de octubre',
      11 => 'de novembre',
      12 => 'de desembre',
    ),
    'abbreviated' => 
    array (
      1 => 'gen.',
      2 => 'feb.',
      3 => 'mar.',
      4 => 'abr.',
      5 => 'mai.',
      6 => 'jun.',
      7 => 'jul.',
      8 => 'ago.',
      9 => 'set.',
      10 => 'oct.',
      11 => 'nov.',
      12 => 'des.',
    ),
    'narrow' => 
    array (
      1 => 'g',
      2 => 'f',
      3 => 'm',
      4 => 'a',
      5 => 'm',
      6 => 'j',
      7 => 'j',
      8 => 'a',
      9 => 's',
      10 => 'o',
      11 => 'n',
      12 => 'd',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'diumenge',
      1 => 'dilluns',
      2 => 'dimarts',
      3 => 'dimecres',
      4 => 'dijous',
      5 => 'divendres',
      6 => 'dissabte',
    ),
    'abbreviated' => 
    array (
      0 => 'dg.',
      1 => 'dl.',
      2 => 'dt.',
      3 => 'dc.',
      4 => 'dj.',
      5 => 'dv.',
      6 => 'ds.',
    ),
    'narrow' => 
    array (
      0 => 'g',
      1 => 'l',
      2 => 't',
      3 => 'c',
      4 => 'j',
      5 => 'v',
      6 => 's',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'aC',
      1 => 'dC',
    ),
    'wide' => 
    array (
      0 => 'aC',
      1 => 'dC',
    ),
    'narrow' => 
    array (
      0 => 'aC',
      1 => 'dC',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d \'de\' MMMM \'de\' yyyy',
    'long' => 'd \'de\' MMMM \'de\' yyyy',
    'medium' => 'dd/MM/yyyy',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'H:mm:ss v',
    'long' => 'H:mm:ss z',
    'medium' => 'H:mm:ss',
    'short' => 'H:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
