<?php
/**
 * Locale data for 'cy_GB'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.42',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => 'EUR',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Ionawr',
      2 => 'Chwefror',
      3 => 'Mawrth',
      4 => 'Ebrill',
      5 => 'Mai',
      6 => 'Mehefin',
      7 => 'Gorffennaf',
      8 => 'Awst',
      9 => 'Medi',
      10 => 'Hydref',
      11 => 'Tachwedd',
      12 => 'Rhagfyr',
    ),
    'abbreviated' => 
    array (
      1 => 'Ion',
      2 => 'Chwe',
      3 => 'Maw',
      4 => 'Ebr',
      5 => 'Mai',
      6 => 'Meh',
      7 => 'Gor',
      8 => 'Aws',
      9 => 'Med',
      10 => 'Hyd',
      11 => 'Tach',
      12 => 'Rhag',
    ),
    'narrow' => 
    array (
      1 => 'I',
      2 => 'C',
      3 => 'M',
      4 => 'E',
      5 => 'M',
      6 => 'M',
      7 => 'G',
      8 => 'A',
      9 => 'M',
      10 => 'H',
      11 => 'T',
      12 => 'R',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Dydd Sul',
      1 => 'Dydd Llun',
      2 => 'Dydd Mawrth',
      3 => 'Dydd Mercher',
      4 => 'Dydd Iau',
      5 => 'Dydd Gwener',
      6 => 'Dydd Sadwrn',
    ),
    'abbreviated' => 
    array (
      0 => 'Sul',
      1 => 'Llun',
      2 => 'Maw',
      3 => 'Mer',
      4 => 'Iau',
      5 => 'Gwe',
      6 => 'Sad',
    ),
    'narrow' => 
    array (
      0 => 'S',
      1 => 'L',
      2 => 'M',
      3 => 'M',
      4 => 'I',
      5 => 'G',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'CC',
      1 => 'OC',
    ),
    'wide' => 
    array (
      0 => 'Cyn Crist',
      1 => 'Oed Crist',
    ),
    'narrow' => 
    array (
      0 => 'C',
      1 => 'O',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, dd MMMM yyyy',
    'long' => 'dd MMMM yyyy',
    'medium' => 'd MMM yyyy',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
