<?php
/**
 * Locale data for 'dz'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.56',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => 'དང་',
    'percentSign' => 'བརྒ་ཆཱ',
    'nativeZeroDigit' => '༠',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => 'གྲངས་མེད',
    'nan' => 'ཨང་མད',
  ),
  'decimalFormat' => '#,##,##0.###',
  'scientificFormat' => '#E+00',
  'percentFormat' => '#,##,##0 %',
  'currencyFormat' => '¤#,##,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'BTN' => 'Nu',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'སྤྱི་ཟླཝ་དངཔ་',
      2 => 'སྤྱི་ཟླཝ་གཉིས་པ་',
      3 => 'སྤྱི་ཟླཝ་གསུམ་པ་',
      4 => 'སྤྱི་ཟླཝ་བཞི་པ་',
      5 => 'སྤྱི་ཟླཝ་ལྔ་པ་',
      6 => 'སྤྱི་ཟླཝ་དྲུག་པ་',
      7 => 'སྤྱི་ཟླཝ་བདུན་པ་',
      8 => 'སྤྱི་ཟླཝ་བརྒྱད་པ་',
      9 => 'སྤྱི་ཟླཝ་དགུ་པ་',
      10 => 'སྤྱི་ཟླཝ་བཅུ་པ་',
      11 => 'སྤྱི་ཟླཝ་བཅུ་གཅིག་པ་',
      12 => 'སྤྱི་ཟླཝ་བཅུ་གཉིས་པ་',
    ),
    'abbreviated' => 
    array (
      1 => 'ཟླ་ ༡',
      2 => 'ཟླ་ ༢',
      3 => 'ཟླ་ ༣',
      4 => 'ཟླ་ ༤',
      5 => 'ཟླ་ ༥',
      6 => 'ཟླ་ ༦',
      7 => 'ཟླ་ ༧',
      8 => 'ཟླ་ ༨',
      9 => 'ཟླ་ ༩',
      10 => 'ཟླ་ ༡༠',
      11 => 'ཟླ་ ༡༡',
      12 => 'ཟླ་ ༡༢',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'གཟའ་ཟླ་བ་',
      1 => 'གཟའ་མིག་དམར་',
      2 => 'གཟའ་ལྷག་པ་',
      3 => 'གཟའ་ཕུར་བུ་',
      4 => 'གཟའ་པ་སངས་',
      5 => 'གཟའ་སྤེན་པ་',
      6 => 'གཟའ་ཉི་མ་',
    ),
    'abbreviated' => 
    array (
      0 => 'ཟླ་',
      1 => 'མིར་',
      2 => 'ལྷག་',
      3 => 'ཕུར་',
      4 => 'སངས་',
      5 => 'སྤེན་',
      6 => 'ཉི་',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'སྤྱི་ལོ་yyyy ཟླ་ MMMM ཚེས་ dd',
    'long' => 'སྤྱི་ལོ་yyyy ཟླ་ MMMM ཚེས་ dd',
    'medium' => 'སྤྱི་ལོ་yyyy ཟླ་ MMM ཚེས་ dd',
    'short' => 'སྤྱི་ལོ་ yyyy ཟླ་ MM ཚེས་ dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'ཆུ་ཚོད་ h སྐར་མ་ mm སྐར་ཆཱ་ ss a vvvv',
    'long' => 'ཆུ་ཚོད་ h སྐར་མ་ mm སྐར་ཆཱ་ ss a zzz',
    'medium' => 'ཆུ་ཚོད་h:mm:ss a',
    'short' => 'ཆུ་ཚོད་ h སྐར་མ་ mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'སྔ་ཆ་',
  'pmName' => 'ཕྱི་ཆ་',
);
