<?php
/**
 * Locale data for 'ee_TG'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.18',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'GHC' => '¢',
    'XOF' => 'CFA',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Dzove',
      2 => 'Dzodze',
      3 => 'Tedoxe',
      4 => 'Afɔfiɛ',
      5 => 'Dama',
      6 => 'Masa',
      7 => 'Siamlɔm',
      8 => 'Deasiamime',
      9 => 'Anyɔnyɔ',
      10 => 'Kele',
      11 => 'Adeɛmekpɔxe',
      12 => 'Dzome',
    ),
    'abbreviated' => 
    array (
      1 => 'Dzv',
      2 => 'Dzd',
      3 => 'Ted',
      4 => 'Afɔ',
      5 => 'Dam',
      6 => 'Mas',
      7 => 'Sia',
      8 => 'Dea',
      9 => 'Any',
      10 => 'Kel',
      11 => 'Ade',
      12 => 'Dzm',
    ),
    'narrow' => 
    array (
      1 => 'D',
      2 => 'D',
      3 => 'T',
      4 => 'A',
      5 => 'D',
      6 => 'M',
      7 => 'S',
      8 => 'D',
      9 => 'A',
      10 => 'K',
      11 => 'A',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Kɔsiɖa',
      1 => 'Dzoɖa',
      2 => 'Braɖa',
      3 => 'Kuɖa',
      4 => 'Yawoɖa',
      5 => 'Fiɖa',
      6 => 'Memleɖa',
    ),
    'abbreviated' => 
    array (
      0 => 'Kɔs Kwe',
      1 => 'Dzo',
      2 => 'Bra',
      3 => 'Kuɖ',
      4 => 'Yaw',
      5 => 'Fiɖ',
      6 => 'Mem',
    ),
    'narrow' => 
    array (
      0 => 'K',
      1 => 'D',
      2 => 'B',
      3 => 'K',
      4 => 'Y',
      5 => 'F',
      6 => 'M',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'HY',
      1 => 'YŊ',
    ),
    'wide' => 
    array (
      0 => 'Hafi Yesu Va Do ŋgɔ na Yesu',
      1 => 'Yesu Ŋɔli',
    ),
    'narrow' => 
    array (
      0 => 'HY',
      1 => 'YŊ',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AN',
  'pmName' => 'EW',
);
