<?php
/**
 * Locale data for 'eo'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.66',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'januaro',
      2 => 'februaro',
      3 => 'marto',
      4 => 'aprilo',
      5 => 'majo',
      6 => 'junio',
      7 => 'julio',
      8 => 'aŭgusto',
      9 => 'septembro',
      10 => 'oktobro',
      11 => 'novembro',
      12 => 'decembro',
    ),
    'abbreviated' => 
    array (
      1 => 'jan',
      2 => 'feb',
      3 => 'mar',
      4 => 'apr',
      5 => 'maj',
      6 => 'jun',
      7 => 'jul',
      8 => 'aŭg',
      9 => 'sep',
      10 => 'okt',
      11 => 'nov',
      12 => 'dec',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'dimanĉo',
      1 => 'lundo',
      2 => 'mardo',
      3 => 'merkredo',
      4 => 'ĵaŭdo',
      5 => 'vendredo',
      6 => 'sabato',
    ),
    'abbreviated' => 
    array (
      0 => 'di',
      1 => 'lu',
      2 => 'ma',
      3 => 'me',
      4 => 'ĵa',
      5 => 've',
      6 => 'sa',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'aK',
      1 => 'pK',
    ),
    'wide' => 
    array (
      0 => 'aK',
      1 => 'pK',
    ),
    'narrow' => 
    array (
      0 => 'aK',
      1 => 'pK',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, d-\'a\' \'de\' MMMM yyyy',
    'long' => 'yyyy-MMMM-dd',
    'medium' => 'yyyy-MMM-dd',
    'short' => 'yy-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'H-\'a\' \'horo\' \'kaj\' m:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'atm',
  'pmName' => 'ptm',
);
