<?php
/**
 * Locale data for 'et'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.78',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => '£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => '¥',
    'USD' => '$',
    'EEK' => 'kr',
    'XXX' => 'XXX',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'jaanuar',
      2 => 'veebruar',
      3 => 'märts',
      4 => 'aprill',
      5 => 'mai',
      6 => 'juuni',
      7 => 'juuli',
      8 => 'august',
      9 => 'september',
      10 => 'oktoober',
      11 => 'november',
      12 => 'detsember',
    ),
    'abbreviated' => 
    array (
      1 => 'jaan',
      2 => 'veebr',
      3 => 'märts',
      4 => 'apr',
      5 => 'mai',
      6 => 'juuni',
      7 => 'juuli',
      8 => 'aug',
      9 => 'sept',
      10 => 'okt',
      11 => 'nov',
      12 => 'dets',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'pühapäev',
      1 => 'esmaspäev',
      2 => 'teisipäev',
      3 => 'kolmapäev',
      4 => 'neljapäev',
      5 => 'reede',
      6 => 'laupäev',
    ),
    'abbreviated' => 
    array (
      0 => 'P',
      1 => 'E',
      2 => 'T',
      3 => 'K',
      4 => 'N',
      5 => 'R',
      6 => 'L',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'e.m.a.',
      1 => 'm.a.j.',
    ),
    'wide' => 
    array (
      0 => 'enne meie aega',
      1 => 'meie aja järgi',
    ),
    'narrow' => 
    array (
      0 => 'e.m.a.',
      1 => 'm.a.j.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, d, MMMM yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'dd.MM.yyyy',
    'short' => 'dd.MM.yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'H:mm:ss v',
    'long' => 'H:mm:ss z',
    'medium' => 'H:mm:ss',
    'short' => 'H:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
