<?php
/**
 * Locale data for 'eu_ES'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.47',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'ESP' => '₧',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'urtarrila',
      2 => 'otsaila',
      3 => 'martxoa',
      4 => 'apirila',
      5 => 'maiatza',
      6 => 'ekaina',
      7 => 'uztaila',
      8 => 'abuztua',
      9 => 'iraila',
      10 => 'urria',
      11 => 'azaroa',
      12 => 'abendua',
    ),
    'abbreviated' => 
    array (
      1 => 'urt',
      2 => 'ots',
      3 => 'mar',
      4 => 'api',
      5 => 'mai',
      6 => 'eka',
      7 => 'uzt',
      8 => 'abu',
      9 => 'ira',
      10 => 'urr',
      11 => 'aza',
      12 => 'abe',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'igandea',
      1 => 'astelehena',
      2 => 'asteartea',
      3 => 'asteazkena',
      4 => 'osteguna',
      5 => 'ostirala',
      6 => 'larunbata',
    ),
    'abbreviated' => 
    array (
      0 => 'ig',
      1 => 'al',
      2 => 'as',
      3 => 'az',
      4 => 'og',
      5 => 'or',
      6 => 'lr',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy\'eko\' MMMM\'ren\' dd\'a\'',
    'long' => 'yyyy\'eko\' MMM\'ren\' dd\'a\'',
    'medium' => 'yyyy-MMM-dd',
    'short' => 'yy-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
