<?php
/**
 * Locale data for 'fa_AF'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.59',
  'numberSymbols' => 
  array (
    'decimal' => '٫',
    'group' => '٬',
    'list' => '؛',
    'percentSign' => '٪',
    'nativeZeroDigit' => '۰',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '−',
    'exponential' => '×۱۰^',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###;\'‪\'-#,##0.###\'‬\'',
  'scientificFormat' => '#E0',
  'percentFormat' => '\'‪\'#,##0%\'‬\'',
  'currencyFormat' => '#,##0.00 ¤;\'‪\'-#,##0.00\'‬\' ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'IRR' => '﷼',
    'AFN' => '؋',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'جنوری',
      2 => 'فبروری',
      3 => 'مارچ',
      4 => 'اپریل',
      5 => 'می',
      6 => 'جون',
      7 => 'جولای',
      8 => 'اگست',
      9 => 'سپتمبر',
      10 => 'اکتوبر',
      11 => 'نومبر',
      12 => 'دسمبر',
    ),
    'abbreviated' => 
    array (
      1 => 'جنو',
      5 => 'مـی',
      6 => 'جون',
      7 => 'جول',
      12 => 'دسم',
    ),
    'narrow' => 
    array (
      1 => 'ج',
      2 => 'ف',
      3 => 'م',
      4 => 'ا',
      5 => 'م',
      6 => 'ج',
      7 => 'ج',
      8 => 'ا',
      9 => 'س',
      10 => 'ا',
      11 => 'ن',
      12 => 'د',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'یکشنبه',
      1 => 'دوشنبه',
      2 => 'سه‌شنبه',
      3 => 'چهارشنبه',
      4 => 'پنجشنبه',
      5 => 'جمعه',
      6 => 'شنبه',
    ),
    'abbreviated' => 
    array (
      0 => 'یکشنبه',
      1 => 'دوشنبه',
      2 => 'سه‌شنبه',
      3 => 'چهارشنبه',
      4 => 'پنجشنبه',
      5 => 'جمعه',
      6 => 'شنبه',
    ),
    'narrow' => 
    array (
      0 => 'ی',
      1 => 'د',
      2 => 'س',
      3 => 'چ',
      4 => 'پ',
      5 => 'ج',
      6 => 'ش',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ق.م.',
      1 => 'م.',
    ),
    'wide' => 
    array (
      0 => 'قبل از میلاد',
      1 => 'میلادی',
    ),
    'narrow' => 
    array (
      0 => 'ق.م.',
      1 => 'م.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM yyyy GGGG',
    'long' => 'd MMMM yyyy',
    'medium' => 'yyyy/M/d',
    'short' => 'yy/M/d',
  ),
  'timeFormats' => 
  array (
    'full' => 'H:mm:ss (vvvv)',
    'long' => 'H:mm:ss (zzzz)',
    'medium' => 'H:mm:ss',
    'short' => 'H:mm',
  ),
  'dateTimeFormat' => '{1}، ساعت {0}',
  'amName' => 'قبل از ظهر',
  'pmName' => 'بعد از ظهر',
);
