<?php
/**
 * Locale data for 'fur_IT'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.15',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => '$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Zenâr',
      2 => 'Fevrâr',
      3 => 'Març',
      4 => 'Avrîl',
      5 => 'Mai',
      6 => 'Jugn',
      7 => 'Lui',
      8 => 'Avost',
      9 => 'Setembar',
      10 => 'Otubar',
      11 => 'Novembar',
      12 => 'Dicembar',
    ),
    'abbreviated' => 
    array (
      1 => 'Zen',
      2 => 'Fev',
      3 => 'Mar',
      4 => 'Avr',
      5 => 'Mai',
      6 => 'Jug',
      7 => 'Lui',
      8 => 'Avo',
      9 => 'Set',
      10 => 'Otu',
      11 => 'Nov',
      12 => 'Dic',
    ),
    'narrow' => 
    array (
      1 => 'Z',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'J',
      7 => 'L',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'domenie',
      1 => 'lunis',
      2 => 'martars',
      3 => 'miercus',
      4 => 'joibe',
      5 => 'vinars',
      6 => 'sabide',
    ),
    'abbreviated' => 
    array (
      0 => 'dom',
      1 => 'lun',
      2 => 'mar',
      3 => 'mie',
      4 => 'joi',
      5 => 'vin',
      6 => 'sab',
    ),
    'narrow' => 
    array (
      0 => 'D',
      1 => 'L',
      2 => 'M',
      3 => 'M',
      4 => 'J',
      5 => 'V',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'pdC',
      1 => 'ddC',
    ),
    'wide' => 
    array (
      0 => 'pdC',
      1 => 'ddC',
    ),
    'narrow' => 
    array (
      0 => 'pdC',
      1 => 'ddC',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d \'di\' MMMM \'dal\' yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'd MMM yyyy',
    'short' => 'd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'a.',
  'pmName' => 'p.',
);
