<?php
/**
 * Locale data for 'gaa_GH'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.15',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'GHC' => '¢',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Aharabata',
      2 => 'Oflo',
      3 => 'Ochokrikri',
      4 => 'Abeibee',
      5 => 'Agbeinaa',
      6 => 'Otukwadan',
      7 => 'Maawe',
      8 => 'Manyawale',
      9 => 'Gbo',
      10 => 'Anton',
      11 => 'Alemle',
      12 => 'Afuabee',
    ),
    'abbreviated' => 
    array (
      1 => 'Aha',
      2 => 'Ofl',
      3 => 'Och',
      4 => 'Abe',
      5 => 'Agb',
      6 => 'Otu',
      7 => 'Maa',
      8 => 'Man',
      9 => 'Gbo',
      10 => 'Ant',
      11 => 'Ale',
      12 => 'Afu',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Hogbaa',
      1 => 'Dzu',
      2 => 'Dzufo',
      3 => 'Sho',
      4 => 'Soo',
      5 => 'Sohaa',
      6 => 'Ho',
    ),
    'abbreviated' => 
    array (
      0 => 'Ho',
      1 => 'Dzu',
      2 => 'Dzf',
      3 => 'Sho',
      4 => 'Soo',
      5 => 'Soh',
      6 => 'Ho',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'DJ',
      1 => 'KJ',
    ),
    'wide' => 
    array (
      0 => 'Dani Jesu',
      1 => 'KJ',
    ),
    'narrow' => 
    array (
      0 => 'DJ',
      1 => 'KJ',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'LB',
  'pmName' => 'SN',
);
