<?php
/**
 * Locale data for 'gez_ET'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.39',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => 'ወ',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'USD',
    'CNY' => 'Y',
    'ERN' => 'ERN',
    'ETB' => '$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ጠሐረ',
      2 => 'ከተተ',
      3 => 'መገበ',
      4 => 'አኀዘ',
      5 => 'ግንባት',
      6 => 'ሠንየ',
      7 => 'ሐመለ',
      8 => 'ነሐሰ',
      9 => 'ከረመ',
      10 => 'ጠቀመ',
      11 => 'ኀደረ',
      12 => 'ኀሠሠ',
    ),
    'abbreviated' => 
    array (
      1 => 'ጠሐረ',
      2 => 'ከተተ',
      3 => 'መገበ',
      4 => 'አኀዘ',
      5 => 'ግንባ',
      6 => 'ሠንየ',
      7 => 'ሐመለ',
      8 => 'ነሐሰ',
      9 => 'ከረመ',
      10 => 'ጠቀመ',
      11 => 'ኀደረ',
      12 => 'ኀሠሠ',
    ),
    'narrow' => 
    array (
      1 => 'ጠ',
      2 => 'ከ',
      3 => 'መ',
      4 => 'አ',
      5 => 'ግ',
      6 => 'ሠ',
      7 => 'ሐ',
      8 => 'ነ',
      9 => 'ከ',
      10 => 'ጠ',
      11 => 'ኀ',
      12 => 'ኀ',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'እኁድ',
      1 => 'ሰኑይ',
      2 => 'ሠሉስ',
      3 => 'ራብዕ',
      4 => 'ሐሙስ',
      5 => 'ዓርበ',
      6 => 'ቀዳሚት',
    ),
    'abbreviated' => 
    array (
      0 => 'እኁድ',
      1 => 'ሰኑይ',
      2 => 'ሠሉስ',
      3 => 'ራብዕ',
      4 => 'ሐሙስ',
      5 => 'ዓርበ',
      6 => 'ቀዳሚ',
    ),
    'narrow' => 
    array (
      0 => 'እ',
      1 => 'ሰ',
      2 => 'ሠ',
      3 => 'ራ',
      4 => 'ሐ',
      5 => 'ዓ',
      6 => 'ቀ',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ዓ/ዓ',
      1 => 'ዓ/ም',
    ),
    'wide' => 
    array (
      0 => 'ዓ/ዓ',
      1 => 'ዓ/ም',
    ),
    'narrow' => 
    array (
      0 => 'ዓ/ዓ',
      1 => 'ዓ/ም',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE፥ dd MMMM መዓልት yyyy G',
    'long' => 'dd MMMM yyyy',
    'medium' => 'dd-MMM-yyyy',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'ጽባሕ',
  'pmName' => 'ምሴት',
);
