<?php
/**
 * Locale data for 'gu'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.59',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '૦',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##,##0%',
  'currencyFormat' => '¤ #,##,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => 'રુ',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'જાન્યુઆરી',
      2 => 'ફેબ્રુઆરી',
      3 => 'માર્ચ',
      4 => 'એપ્રિલ',
      5 => 'મે',
      6 => 'જૂન',
      7 => 'જુલાઈ',
      8 => 'ઑગસ્ટ',
      9 => 'સપ્ટેમ્બર',
      10 => 'ઑક્ટ્બર',
      11 => 'નવેમ્બર',
      12 => 'ડિસેમ્બર',
    ),
    'abbreviated' => 
    array (
      1 => 'જાન્યુ',
      2 => 'ફેબ્રુ',
      3 => 'માર્ચ',
      4 => 'એપ્રિલ',
      5 => 'મે',
      6 => 'જૂન',
      7 => 'જુલાઈ',
      8 => 'ઑગસ્ટ',
      9 => 'સપ્ટે',
      10 => 'ઑક્ટો',
      11 => 'નવે',
      12 => 'ડિસે',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'રવિવાર',
      1 => 'સોમવાર',
      2 => 'મંગળવાર',
      3 => 'બુધવાર',
      4 => 'ગુરુવાર',
      5 => 'શુક્રવાર',
      6 => 'શનિવાર',
    ),
    'abbreviated' => 
    array (
      0 => 'રવિ',
      1 => 'સોમ',
      2 => 'મંગળ',
      3 => 'બુધ',
      4 => 'ગુરુ',
      5 => 'શુક્ર',
      6 => 'શનિ',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'ઈસાપૂઋ્વ.',
      1 => 'સન.',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'dd-MM-yyyy',
    'short' => 'd-MM-yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'hh:mm:ss a v',
    'long' => 'hh:mm:ss a z',
    'medium' => 'hh:mm:ss a',
    'short' => 'hh:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'પૂર્વ મધ્યાહ્ન',
  'pmName' => 'ઉત્તર મધ્યાહ્ન',
);
