<?php
/**
 * Locale data for 'gv_GB'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.46',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Jerrey-geuree',
      2 => 'Toshiaght-arree',
      3 => 'Mayrnt',
      4 => 'Averil',
      5 => 'Boaldyn',
      6 => 'Mean-souree',
      7 => 'Jerrey-souree',
      8 => 'Luanistyn',
      9 => 'Mean-fouyir',
      10 => 'Jerrey-fouyir',
      11 => 'Mee Houney',
      12 => 'Mee ny Nollick',
    ),
    'abbreviated' => 
    array (
      1 => 'J-guer',
      2 => 'T-arree',
      3 => 'Mayrnt',
      4 => 'Avrril',
      5 => 'Boaldyn',
      6 => 'M-souree',
      7 => 'J-souree',
      8 => 'Luanistyn',
      9 => 'M-fouyir',
      10 => 'J-fouyir',
      11 => 'M.Houney',
      12 => 'M.Nollick',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Jedoonee',
      1 => 'Jelhein',
      2 => 'Jemayrt',
      3 => 'Jercean',
      4 => 'Jerdein',
      5 => 'Jeheiney',
      6 => 'Jesarn',
    ),
    'abbreviated' => 
    array (
      0 => 'Jed',
      1 => 'Jel',
      2 => 'Jem',
      3 => 'Jerc',
      4 => 'Jerd',
      5 => 'Jeh',
      6 => 'Jes',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'RC',
      1 => 'AD',
    ),
    'wide' => 
    array (
      0 => 'RC',
      1 => 'AD',
    ),
    'narrow' => 
    array (
      0 => 'RC',
      1 => 'AD',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE dd MMMM yyyy',
    'long' => 'dd MMMM yyyy',
    'medium' => 'MMM dd, yyyy',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'a.m.',
  'pmName' => 'p.m.',
);
