<?php
/**
 * Locale data for 'gv_IM'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '9253',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'superscriptingExponent' => '×',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'ARS' => '$',
    'AUD' => 'A$',
    'BBD' => '$',
    'BDT' => '৳',
    'BMD' => '$',
    'BND' => '$',
    'BRL' => 'R$',
    'BSD' => '$',
    'BYR' => 'р.',
    'BZD' => '$',
    'CAD' => 'CA$',
    'CLP' => '$',
    'CNY' => 'CN¥',
    'COP' => '$',
    'CRC' => '₡',
    'CUP' => '$',
    'DOP' => '$',
    'ESP' => '₧',
    'EUR' => '€',
    'FJD' => '$',
    'GBP' => '£',
    'GHS' => '₵',
    'GIP' => '£',
    'GYD' => '$',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JMD' => '$',
    'JPY' => 'JP¥',
    'KHR' => '៛',
    'KRW' => '₩',
    'KYD' => '$',
    'KZT' => '₸',
    'LAK' => '₭',
    'LRD' => '$',
    'MNT' => '₮',
    'MXN' => 'MX$',
    'NAD' => '$',
    'NGN' => '₦',
    'NZD' => 'NZ$',
    'PHP' => '₱',
    'PYG' => '₲',
    'RUR' => 'р.',
    'SBD' => '$',
    'SGD' => '$',
    'SRD' => '$',
    'SSP' => '£',
    'THB' => '฿',
    'TRY' => '₺',
    'TTD' => '$',
    'TWD' => 'NT$',
    'UAH' => '₴',
    'USD' => 'US$',
    'UYU' => '$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Jerrey-geuree',
      2 => 'Toshiaght-arree',
      3 => 'Mayrnt',
      4 => 'Averil',
      5 => 'Boaldyn',
      6 => 'Mean-souree',
      7 => 'Jerrey-souree',
      8 => 'Luanistyn',
      9 => 'Mean-fouyir',
      10 => 'Jerrey-fouyir',
      11 => 'Mee Houney',
      12 => 'Mee ny Nollick',
    ),
    'abbreviated' => 
    array (
      1 => 'J-guer',
      2 => 'T-arree',
      3 => 'Mayrnt',
      4 => 'Avrril',
      5 => 'Boaldyn',
      6 => 'M-souree',
      7 => 'J-souree',
      8 => 'Luanistyn',
      9 => 'M-fouyir',
      10 => 'J-fouyir',
      11 => 'M.Houney',
      12 => 'M.Nollick',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Jedoonee',
      1 => 'Jelhein',
      2 => 'Jemayrt',
      3 => 'Jercean',
      4 => 'Jerdein',
      5 => 'Jeheiney',
      6 => 'Jesarn',
    ),
    'abbreviated' => 
    array (
      0 => 'Jed',
      1 => 'Jel',
      2 => 'Jem',
      3 => 'Jerc',
      4 => 'Jerd',
      5 => 'Jeh',
      6 => 'Jes',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'T',
      3 => 'W',
      4 => 'T',
      5 => 'F',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'RC',
      1 => 'AD',
    ),
    'wide' => 
    array (
      0 => 'RC',
      1 => 'AD',
    ),
    'narrow' => 
    array (
      0 => 'RC',
      1 => 'AD',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE dd MMMM y',
    'long' => 'dd MMMM y',
    'medium' => 'MMM dd, y',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'a.m.',
  'pmName' => 'p.m.',
  'orientation' => 'ltr',
  'pluralRules' => 
  array (
    0 => 'v = 0&&i % 10 = 1 @integer 1, 11, 21, 31, 41, 51, 61, 71, 101, 1001, …',
    1 => 'v = 0&&i % 10 = 2 @integer 2, 12, 22, 32, 42, 52, 62, 72, 102, 1002, …',
    2 => 'v = 0&&i % 100 = 0,20,40,60,80 @integer 0, 20, 40, 60, 80, 100, 120, 140, 1000, 10000, 100000, 1000000, …',
    3 => 'v != 0   @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …',
    4 => ' @integer 3~10, 13~19, 23, 103, 1003, …',
    5 => 'true',
  ),
  'languages' => 
  array (
    'gv' => 'Gaelg',
  ),
  'territories' => 
  array (
    'gb' => 'Rywvaneth Unys',
    'im' => 'Ellan Vannin',
  ),
);
