<?php
/**
 * Locale data for 'ha'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.27',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'NGN' => '₦',
    'XOF' => 'CFA',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Janairu',
      2 => 'Fabrairu',
      3 => 'Maris',
      4 => 'Afrilu',
      5 => 'Mayu',
      6 => 'Yuni',
      7 => 'Yuli',
      8 => 'Augusta',
      9 => 'Satumba',
      10 => 'Oktoba',
      11 => 'Nuwamba',
      12 => 'Disamba',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Fab',
      3 => 'Mar',
      4 => 'Afr',
      5 => 'May',
      6 => 'Yun',
      7 => 'Yul',
      8 => 'Aug',
      9 => 'Sat',
      10 => 'Okt',
      11 => 'Nuw',
      12 => 'Dis',
    ),
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'Y',
      7 => 'Y',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Lahadi',
      1 => 'Litini',
      2 => 'Talata',
      3 => 'Laraba',
      4 => 'Alhamis',
      5 => 'Jumma\'a',
      6 => 'Asabar',
    ),
    'abbreviated' => 
    array (
      0 => 'Lah',
      1 => 'Lit',
      2 => 'Tal',
      3 => 'Lar',
      4 => 'Alh',
      5 => 'Jum',
      6 => 'Asa',
    ),
    'narrow' => 
    array (
      0 => 'L',
      1 => 'L',
      2 => 'T',
      3 => 'L',
      4 => 'A',
      5 => 'J',
      6 => 'A',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'GM',
      1 => 'M',
    ),
    'wide' => 
    array (
      0 => 'Gabanin Miladi',
      1 => 'Miladi',
    ),
    'narrow' => 
    array (
      0 => 'GM',
      1 => 'M',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM, yyyy',
    'long' => 'd MMMM, yyyy',
    'medium' => 'd MMM, yyyy',
    'short' => 'd/M/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
