<?php
/**
 * Locale data for 'ha_Arab_SD'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.1',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'NGN' => '₦',
    'XOF' => 'CFA',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'جَنَيْرُ',
      2 => 'ڢَبْرَيْرُ',
      3 => 'مَرِسْ',
      4 => 'أَڢْرِلُ',
      5 => 'مَيُ',
      6 => 'يُونِ',
      7 => 'يُولِ',
      8 => 'أَغُسْتَ',
      9 => 'سَتُمْبَ',
      10 => 'أُكْتوُبَ',
      11 => 'نُوَمْبَ',
      12 => 'دِسَمْبَ',
    ),
    'abbreviated' => 
    array (
      1 => 'جَن',
      2 => 'ڢَب',
      3 => 'مَر',
      4 => 'أَڢْر',
      5 => 'مَي',
      6 => 'يُون',
      7 => 'يُول',
      8 => 'أَغُ',
      9 => 'سَت',
      10 => 'أُكْت',
      11 => 'نُو',
      12 => 'دِس',
    ),
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'Y',
      7 => 'Y',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'لَحَدِ',
      1 => 'لِتِنِنْ',
      2 => 'تَلَتَ',
      3 => 'لَرَبَ',
      4 => 'أَلْحَمِسْ',
      5 => 'جُمَعَ',
      6 => 'أَسَبَرْ',
    ),
    'abbreviated' => 
    array (
      0 => 'لَح',
      1 => 'لِت',
      2 => 'تَل',
      3 => 'لَر',
      4 => 'أَلْح',
      5 => 'جُم',
      6 => 'أَسَ',
    ),
    'narrow' => 
    array (
      0 => 'L',
      1 => 'L',
      2 => 'T',
      3 => 'L',
      4 => 'A',
      5 => 'J',
      6 => 'A',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'غَبَنِنْ مِلَدِ',
      1 => 'مِلَدِ',
    ),
    'wide' => 
    array (
      0 => 'غَبَنِنْ مِلَدِ',
      1 => 'مِلَدِ',
    ),
    'narrow' => 
    array (
      0 => 'GM',
      1 => 'M',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM, yyyy',
    'long' => 'd MMMM, yyyy',
    'medium' => 'd MMM, yyyy',
    'short' => 'd/M/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'A.M.',
  'pmName' => 'P.M.',
);
