<?php
/**
 * Locale data for 'he'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.105',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'ILP' => 'ל״י',
    'ILS' => '₪',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ינואר',
      2 => 'פברואר',
      3 => 'מרס',
      4 => 'אפריל',
      5 => 'מאי',
      6 => 'יוני',
      7 => 'יולי',
      8 => 'אוגוסט',
      9 => 'ספטמבר',
      10 => 'אוקטובר',
      11 => 'נובמבר',
      12 => 'דצמבר',
    ),
    'abbreviated' => 
    array (
      1 => 'ינו',
      2 => 'פבר',
      3 => 'מרץ',
      4 => 'אפר',
      5 => 'מאי',
      6 => 'יונ',
      7 => 'יול',
      8 => 'אוג',
      9 => 'ספט',
      10 => 'אוק',
      11 => 'נוב',
      12 => 'דצמ',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'יום ראשון',
      1 => 'יום שני',
      2 => 'יום שלישי',
      3 => 'יום רביעי',
      4 => 'יום חמישי',
      5 => 'יום שישי',
      6 => 'שבת',
    ),
    'abbreviated' => 
    array (
      0 => 'א',
      1 => 'ב',
      2 => 'ג',
      3 => 'ד',
      4 => 'ה',
      5 => 'ו',
      6 => 'ש',
    ),
    'narrow' => 
    array (
      0 => 'א',
      1 => 'ב',
      2 => 'ג',
      3 => 'ד',
      4 => 'ה',
      5 => 'ו',
      6 => 'ש',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'לפנה״ס',
      1 => 'לסה״נ',
    ),
    'wide' => 
    array (
      0 => 'לפני הספירה',
      1 => 'לספירה',
    ),
    'narrow' => 
    array (
      0 => 'לפנה״ס',
      1 => 'לסה״נ',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'dd/MM/yyyy',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'לפנה"צ',
  'pmName' => 'אחה"צ',
);
