<?php
/**
 * Locale data for 'hi'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.85',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '०',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##,##0%',
  'currencyFormat' => '¤ #,##,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'रीयाल',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => 'रु.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'AMD' => 'दरम',
    'CNY' => 'युवान',
    'CSD' => 'स. ढीनार',
    'FJD' => 'फ़िजी का डालर',
    'HKD' => 'हॉंगकॉंग डॉलर',
    'RUB' => 'रूबल',
    'XXX' => '१२,३४५.६८ रुपये',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'जनवरी',
      2 => 'फरवरी',
      3 => 'मार्च',
      4 => 'अप्रैल',
      5 => 'मई',
      6 => 'जून',
      7 => 'जुलाई',
      8 => 'अगस्त',
      9 => 'सितम्बर',
      10 => 'अक्तूबर',
      11 => 'नवम्बर',
      12 => 'दिसम्बर',
    ),
    'abbreviated' => 
    array (
      1 => 'जनवरी',
      2 => 'फ़रवरी',
      3 => 'मार्च',
      4 => 'अप्रैल',
      5 => 'मई',
      6 => 'जून',
      7 => 'जुलाई',
      8 => 'अगस्त',
      9 => 'सितम्बर',
      10 => 'अक्टूबर',
      11 => 'नवंबर',
      12 => 'दिसंबर',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'रविवार',
      1 => 'सोमवार',
      2 => 'मंगलवार',
      3 => 'बुधवार',
      4 => 'गुरूवार',
      5 => 'शुक्रवार',
      6 => 'शनिवार',
    ),
    'abbreviated' => 
    array (
      0 => 'रवि',
      1 => 'सोम',
      2 => 'मंगल',
      3 => 'बुध',
      4 => 'गुरु',
      5 => 'शुक्र',
      6 => 'शनि',
    ),
    'narrow' => 
    array (
      0 => 'र',
      1 => '2',
      2 => 'मं',
      3 => '4',
      4 => 'गु',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ईसा पूर्व',
      1 => 'सन्',
    ),
    'wide' => 
    array (
      0 => 'ईसा पूर्व',
      1 => 'सन्',
    ),
    'narrow' => 
    array (
      0 => 'ईसा पूर्व',
      1 => 'सन्',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'dd-MM-yyyy',
    'short' => 'd-M-yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'पूर्वाह्न',
  'pmName' => 'अपराह्न',
);
