<?php
/**
 * Locale data for 'hy'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.64',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#0%',
  'currencyFormat' => '#0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'AMD' => 'դր.',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Յունուար',
      2 => 'Փետրուար',
      3 => 'Մարտ',
      4 => 'Ապրիլ',
      5 => 'Մայիս',
      6 => 'Յունիս',
      7 => 'Յուլիս',
      8 => 'Օգոստոս',
      9 => 'Սեպտեմբեր',
      10 => 'Հոկտեմբեր',
      11 => 'Նոյեմբեր',
      12 => 'Դեկտեմբեր',
    ),
    'abbreviated' => 
    array (
      1 => 'Յնր',
      2 => 'Փտր',
      3 => 'Մրտ',
      4 => 'Ապր',
      5 => 'Մյս',
      6 => 'Յնս',
      7 => 'Յլս',
      8 => 'Օգս',
      9 => 'Սեպ',
      10 => 'Հոկ',
      11 => 'Նոյ',
      12 => 'Դեկ',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Կիրակի',
      1 => 'Երկուշաբթի',
      2 => 'Երեքշաբթի',
      3 => 'Չորեքշաբթի',
      4 => 'Հինգշաբթի',
      5 => 'Ուրբաթ',
      6 => 'Շաբաթ',
    ),
    'abbreviated' => 
    array (
      0 => 'Կիր',
      1 => 'Երկ',
      2 => 'Երք',
      3 => 'Չոր',
      4 => 'Հնգ',
      5 => 'Ուր',
      6 => 'Շաբ',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'Ք․Ա․',
      1 => 'Ք․Ե․',
    ),
    'wide' => 
    array (
      0 => 'Ք․Ա․',
      1 => 'Ք․Ե․',
    ),
    'narrow' => 
    array (
      0 => 'Ք․Ա․',
      1 => 'Ք․Ե․',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, MMMM d, yyyy',
    'long' => 'MMMM dd, yyyy',
    'medium' => 'MMM d, yyyy',
    'short' => 'MM/dd/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'Առ․',
  'pmName' => 'Եր․',
);
