<?php
/**
 * Locale data for 'ig'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.22',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'NGN' => '₦',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Jenụwarị',
      2 => 'Febrụwarị',
      3 => 'Maachị',
      4 => 'Eprel',
      5 => 'Mee',
      6 => 'Juun',
      7 => 'Julaị',
      8 => 'Ọgọọst',
      9 => 'Septemba',
      10 => 'Ọktoba',
      11 => 'Novemba',
      12 => 'Disemba',
    ),
    'abbreviated' => 
    array (
      1 => 'Jen',
      2 => 'Feb',
      3 => 'Maa',
      4 => 'Epr',
      5 => 'Mee',
      6 => 'Juu',
      7 => 'Jul',
      8 => 'Ọgọ',
      9 => 'Sep',
      10 => 'Ọkt',
      11 => 'Nov',
      12 => 'Dis',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Mbọsị Ụka',
      1 => 'Mọnde',
      2 => 'Tiuzdee',
      3 => 'Wenezdee',
      4 => 'Tọọzdee',
      5 => 'Fraịdee',
      6 => 'Satọdee',
    ),
    'abbreviated' => 
    array (
      0 => 'Ụka',
      1 => 'Mọn',
      2 => 'Tiu',
      3 => 'Wen',
      4 => 'Tọọ',
      5 => 'Fraị',
      6 => 'Sat',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'T.K.',
      1 => 'A.K.',
    ),
    'wide' => 
    array (
      0 => 'Tupu Kristi',
      1 => 'Afọ Kristi',
    ),
    'narrow' => 
    array (
      0 => 'T.K.',
      1 => 'A.K.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'A.M.',
  'pmName' => 'P.M.',
);
