<?php
/**
 * Locale data for 'ii'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '9061',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'superscriptingExponent' => '×',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'ARS' => '$',
    'AUD' => 'A$',
    'BBD' => '$',
    'BDT' => '৳',
    'BMD' => '$',
    'BND' => '$',
    'BRL' => 'R$',
    'BSD' => '$',
    'BYR' => 'р.',
    'BZD' => '$',
    'CAD' => 'CA$',
    'CLP' => '$',
    'CNY' => '¥',
    'COP' => '$',
    'CRC' => '₡',
    'CUP' => '$',
    'DOP' => '$',
    'ESP' => '₧',
    'EUR' => '€',
    'FJD' => '$',
    'GBP' => '£',
    'GHS' => '₵',
    'GIP' => '£',
    'GYD' => '$',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JMD' => '$',
    'JPY' => 'JP¥',
    'KHR' => '៛',
    'KRW' => '₩',
    'KYD' => '$',
    'KZT' => '₸',
    'LAK' => '₭',
    'LRD' => '$',
    'MNT' => '₮',
    'MXN' => 'MX$',
    'NAD' => '$',
    'NGN' => '₦',
    'NZD' => 'NZ$',
    'PHP' => '₱',
    'PYG' => '₲',
    'RUR' => 'р.',
    'SBD' => '$',
    'SGD' => '$',
    'SRD' => '$',
    'SSP' => '£',
    'THB' => '฿',
    'TRY' => '₺',
    'TTD' => '$',
    'TWD' => 'NT$',
    'UAH' => '₴',
    'USD' => 'US$',
    'UYU' => '$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ꋍꆪ',
      2 => 'ꑍꆪ',
      3 => 'ꌕꆪ',
      4 => 'ꇖꆪ',
      5 => 'ꉬꆪ',
      6 => 'ꃘꆪ',
      7 => 'ꏃꆪ',
      8 => 'ꉆꆪ',
      9 => 'ꈬꆪ',
      10 => 'ꊰꆪ',
      11 => 'ꊰꊪꆪ',
      12 => 'ꊰꑋꆪ',
    ),
    'abbreviated' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ꑭꆏꑍ',
      1 => 'ꆏꊂꋍ',
      2 => 'ꆏꊂꑍ',
      3 => 'ꆏꊂꌕ',
      4 => 'ꆏꊂꇖ',
      5 => 'ꆏꊂꉬ',
      6 => 'ꆏꊂꃘ',
    ),
    'abbreviated' => 
    array (
      0 => 'ꑭꆏ',
      1 => 'ꆏꋍ',
      2 => 'ꆏꑍ',
      3 => 'ꆏꌕ',
      4 => 'ꆏꇖ',
      5 => 'ꆏꉬ',
      6 => 'ꆏꃘ',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'ꆏ',
      1 => 'ꋍ',
      2 => 'ꑍ',
      3 => 'ꌕ',
      4 => 'ꇖ',
      5 => 'ꉬ',
      6 => 'ꃘ',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ꃅꋊꂿ',
      1 => 'ꃅꋊꊂ',
    ),
    'wide' => 
    array (
      0 => 'ꃅꋊꂿ',
      1 => 'ꃅꋊꊂ',
    ),
    'narrow' => 
    array (
      0 => 'ꃅꋊꂿ',
      1 => 'ꃅꋊꊂ',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'y MMMM d, EEEE',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'y-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'ꎸꄑ',
  'pmName' => 'ꁯꋒ',
  'orientation' => 'ltr',
  'pluralRules' => 
  array (
    0 => ' @integer 0~15, 100, 1000, 10000, 100000, 1000000, … @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …',
    1 => 'true',
  ),
  'languages' => 
  array (
    'de' => 'ꄓꇩꉙ',
    'en' => 'ꑱꇩꉙ',
    'es' => 'ꑭꀠꑸꉙ',
    'fr' => 'ꃔꇩꉙ',
    'ii' => 'ꆈꌠꉙ',
    'it' => 'ꑴꄊꆺꉙ',
    'ja' => 'ꏝꀪꉙ',
    'pt' => 'ꁍꄨꑸꉙ',
    'pt_br' => 'ꀠꑟꁍꄨꑸꉙ',
    'ru' => 'ꊉꇩꉙ',
    'und' => 'ꅉꀋꌠꅇꂷ',
    'zh' => 'ꍏꇩꉙ',
    'zh_hans' => 'ꈝꐯꍏꇩꉙ',
    'zh_hant' => 'ꀎꋏꍏꇩꉙ',
  ),
  'scripts' => 
  array (
    'arab' => 'ꀊꇁꀨꁱꂷ',
    'cyrl' => 'ꀊꆨꌦꇁꃚꁱꂷ',
    'hans' => 'ꈝꐯꉌꈲꁱꂷ',
    'hant' => 'ꀎꋏꉌꈲꁱꂷ',
    'latn' => 'ꇁꄀꁱꂷ',
    'yiii' => 'ꆈꌠꁱꂷ',
    'zxxx' => 'ꁱꀋꉆꌠ',
    'zzzz' => 'ꅉꀋꐚꌠꁱꂷ',
  ),
  'territories' => 
  array (
    'br' => 'ꀠꑭ',
    'cn' => 'ꍏꇩ',
    'de' => 'ꄓꇩ',
    'fr' => 'ꃔꇩ',
    'gb' => 'ꑱꇩ',
    'in' => 'ꑴꄗ',
    'it' => 'ꑴꄊꆺ',
    'jp' => 'ꏝꀪ',
    'ru' => 'ꊉꇆꌦ',
    'us' => 'ꂰꇩ',
    'zz' => 'ꃅꄷꅉꀋꐚꌠ',
  ),
);
