<?php
/**
 * Locale data for 'ii'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.7',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'XXX' => 'XXX',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ꋍꆪ',
      2 => 'ꑍꆪ',
      3 => 'ꌕꆪ',
      4 => 'ꇖꆪ',
      5 => 'ꉬꆪ',
      6 => 'ꃘꆪ',
      7 => 'ꏃꆪ',
      8 => 'ꉆꆪ',
      9 => 'ꈬꆪ',
      10 => 'ꊰꆪ',
      11 => 'ꊰꊪꆪ',
      12 => 'ꊰꑋꆪ',
    ),
    'abbreviated' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ꑭꆏꑍ',
      1 => 'ꆏꊂꋍ',
      2 => 'ꆏꊂꑍ',
      3 => 'ꆏꊂꌕ',
      4 => 'ꆏꊂꇖ',
      5 => 'ꆏꊂꉬ',
      6 => 'ꆏꊂꃘ',
    ),
    'abbreviated' => 
    array (
      0 => 'ꆏꑍ',
      1 => 'ꆏꋍ',
      2 => 'ꆏꑍ',
      3 => 'ꆏꌕ',
      4 => 'ꆏꇖ',
      5 => 'ꆏꉬ',
      6 => 'ꆏꃘ',
    ),
    'narrow' => 
    array (
      0 => 'ꆏ',
      1 => 'ꋍ',
      2 => 'ꑍ',
      3 => 'ꌕ',
      4 => 'ꇖ',
      5 => 'ꉬ',
      6 => 'ꃘ',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ꃅꋊꂿ',
      1 => 'ꃅꋊꊂ',
    ),
    'wide' => 
    array (
      0 => 'ꃅꋊꂿ',
      1 => 'ꃅꋊꊂ',
    ),
    'narrow' => 
    array (
      0 => 'ꃅꋊꂿ',
      1 => 'ꃅꋊꊂ',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yyyy-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'ꎸꄑ',
  'pmName' => 'ꁯꋒ',
);
