<?php
/**
 * Locale data for 'kfo'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.21',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'NGN' => '₦',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Fai Weyene',
      2 => 'Fai Fani',
      3 => 'Fai Tataka',
      4 => 'Fai Nangra',
      5 => 'Fai Tuyo',
      6 => 'Fai Tsoyi',
      7 => 'Fai Tafaka',
      8 => 'Fai Warachi',
      9 => 'Fai Kunobok',
      10 => 'Fai Bansok',
      11 => 'Fai Kom',
      12 => 'Fai Sauk',
    ),
    'abbreviated' => 
    array (
      1 => 'Wey',
      2 => 'Fan',
      3 => 'Tat',
      4 => 'Nan',
      5 => 'Tuy',
      6 => 'Tso',
      7 => 'Taf',
      8 => 'War',
      9 => 'Kun',
      10 => 'Ban',
      11 => 'Kom',
      12 => 'Sau',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Lahadi',
      1 => 'Je-Kubacha',
      2 => 'Je-Gbai',
      3 => 'Tansati',
      4 => 'Je-Yei',
      5 => 'Je-Koye',
      6 => 'Sati',
    ),
    'abbreviated' => 
    array (
      0 => 'Lah',
      1 => 'Kub',
      2 => 'Gba',
      3 => 'Tan',
      4 => 'Yei',
      5 => 'Koy',
      6 => 'Sat',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'KMW',
      1 => 'BCW',
    ),
    'wide' => 
    array (
      0 => 'Kafi Mar Wenom',
      1 => 'Bayan Chi Wenom',
    ),
    'narrow' => 
    array (
      0 => 'KMW',
      1 => 'BCW',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
