<?php
/**
 * Locale data for 'kk_Cyrl'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.1',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤;-#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'KZT' => 'тңг.',
    'XXX' => 'XXX',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'қаңтар',
      2 => 'ақпан',
      3 => 'наурыз',
      4 => 'сәуір',
      5 => 'мамыр',
      6 => 'маусым',
      7 => 'шілде',
      8 => 'тамыз',
      9 => 'қыркүйек',
      10 => 'қазан',
      11 => 'қараша',
      12 => 'желтоқсан',
    ),
    'abbreviated' => 
    array (
      1 => 'қаң.',
      2 => 'ақп.',
      3 => 'нау.',
      4 => 'сәу.',
      5 => 'мам.',
      6 => 'мау.',
      7 => 'шіл.',
      8 => 'там.',
      9 => 'қыр.',
      10 => 'қаз.',
      11 => 'қар.',
      12 => 'желт.',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'жексені',
      1 => 'дуйсенбі',
      2 => 'сейсенбі',
      3 => 'сәренбі',
      4 => 'бейсенбі',
      5 => 'жұма',
      6 => 'сенбі',
    ),
    'abbreviated' => 
    array (
      0 => 'жс.',
      1 => 'дс.',
      2 => 'сс.',
      3 => 'ср.',
      4 => 'бс.',
      5 => 'жм.',
      6 => 'сһ.',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM yyyy \'ж\'.',
    'long' => 'd MMMM yyyy \'ж\'.',
    'medium' => 'dd.MM.yyyy',
    'short' => 'dd.MM.yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
