<?php
/**
 * Locale data for 'kkj'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2011 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '7589',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'A$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'pamba',
      2 => 'wanja',
      3 => 'mbiyɔ mɛndoŋgɔ',
      4 => 'Nyɔlɔmbɔŋgɔ',
      5 => 'Mɔnɔ ŋgbanja',
      6 => 'Nyaŋgwɛ ŋgbanja',
      7 => 'kuŋgwɛ',
      8 => 'fɛ',
      9 => 'njapi',
      10 => 'nyukul',
      11 => '11',
      12 => 'ɓulɓusɛ',
    ),
    'abbreviated' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
    'wide' => 
    array (
      1 => 'pamba',
      2 => 'wanja',
      3 => 'mbiyɔ mɛndoŋgɔ',
      4 => 'Nyɔlɔmbɔŋgɔ',
      5 => 'Mɔnɔ ŋgbanja',
      6 => 'Nyaŋgwɛ ŋgbanja',
      7 => 'kuŋgwɛ',
      8 => 'fɛ',
      9 => 'njapi',
      10 => 'nyukul',
      11 => '11',
      12 => 'ɓulɓusɛ',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'sɔndi',
      1 => 'lundi',
      2 => 'mardi',
      3 => 'mɛrkɛrɛdi',
      4 => 'yedi',
      5 => 'vaŋdɛrɛdi',
      6 => 'mɔnɔ sɔndi',
    ),
    'abbreviated' => 
    array (
      0 => 'sɔndi',
      1 => 'lundi',
      2 => 'mardi',
      3 => 'mɛrkɛrɛdi',
      4 => 'yedi',
      5 => 'vaŋdɛrɛdi',
      6 => 'mɔnɔ sɔndi',
    ),
    'narrow' => 
    array (
      0 => 'so',
      1 => 'lu',
      2 => 'ma',
      3 => 'mɛ',
      4 => 'ye',
      5 => 'va',
      6 => 'ms',
    ),
    'short' => 
    array (
      0 => 'sɔndi',
      1 => 'lundi',
      2 => 'mardi',
      3 => 'mɛrkɛrɛdi',
      4 => 'yedi',
      5 => 'vaŋdɛrɛdi',
      6 => 'mɔnɔ sɔndi',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'so',
      1 => 'lu',
      2 => 'ma',
      3 => 'mɛ',
      4 => 'ye',
      5 => 'va',
      6 => 'ms',
    ),
    'abbreviated' => 
    array (
      0 => 'sɔndi',
      1 => 'lundi',
      2 => 'mardi',
      3 => 'mɛrkɛrɛdi',
      4 => 'yedi',
      5 => 'vaŋdɛrɛdi',
      6 => 'mɔnɔ sɔndi',
    ),
    'short' => 
    array (
      0 => 'so',
      1 => 'lu',
      2 => 'ma',
      3 => 'mɛ',
      4 => 'ye',
      5 => 'va',
      6 => 'ms',
    ),
    'wide' => 
    array (
      0 => 'sɔndi',
      1 => 'lundi',
      2 => 'mardi',
      3 => 'mɛrkɛrɛdi',
      4 => 'yedi',
      5 => 'vaŋdɛrɛdi',
      6 => 'mɔnɔ sɔndi',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE dd MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'dd/MM y',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'en' => 'yaman',
    'fr' => 'numbu buy',
    'kkj' => 'kakɔ',
  ),
  'territories' => 
  array (
    'cm' => 'Kamɛrun',
  ),
  'pluralRules' => 
  array (
    0 => 'n==1',
    1 => 'true',
  ),
);
