<?php
/**
 * Locale data for 'km_KH'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.35',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'KHR' => '៛',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'មករា',
      2 => 'កុម្ភៈ',
      3 => 'មិនា',
      4 => 'មេសា',
      5 => 'ឧសភា',
      6 => 'មិថុនា',
      7 => 'កក្កដា',
      8 => 'សីហា',
      9 => 'កញ្ញា',
      10 => 'តុលា',
      11 => 'វិច្ឆិកា',
      12 => 'ធ្នូ',
    ),
    'abbreviated' => 
    array (
      1 => '១',
      2 => '២',
      3 => '៣',
      4 => '៤',
      5 => '៥',
      6 => '៦',
      7 => '៧',
      8 => '៨',
      9 => '៩',
      10 => '១០',
      11 => '១១',
      12 => '១២',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ថ្ងៃអាទិត្យ',
      1 => '​ថ្ងៃច័ន្ទ',
      2 => 'ថ្ងៃអង្គារ',
      3 => 'ថ្ងៃពុធ',
      4 => 'ថ្ងៃព្រហស្បតិ៍',
      5 => 'ថ្ងៃសុក្រ',
      6 => 'ថ្ងៃសៅរ៍',
    ),
    'abbreviated' => 
    array (
      0 => 'អា',
      1 => 'ច',
      2 => 'អ',
      3 => 'ពុ',
      4 => 'ព្រ',
      5 => 'សុ',
      6 => 'ស',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'មុន​គ.ស.',
      1 => 'គ.ស.',
    ),
    'wide' => 
    array (
      0 => 'មុន​គ្រិស្តសករាជ',
      1 => 'គ្រិស្តសករាជ',
    ),
    'narrow' => 
    array (
      0 => 'មុន​គ.ស.',
      1 => 'គ.ស.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE ថ្ងៃ d ខែ MMMM ឆ្នាំ  yyyy',
    'long' => 'd ខែ MMMM ឆ្នាំ  yyyy',
    'medium' => 'd MMM yyyy',
    'short' => 'd/M/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'H ម៉ោង m នាទី ss វិនាទី​ v',
    'long' => 'H ម៉ោង m នាទី ss វិនាទី​z',
    'medium' => 'H:mm:ss',
    'short' => 'H:mm',
  ),
  'dateTimeFormat' => '{1}, {0}',
  'amName' => 'ព្រឹក',
  'pmName' => 'ល្ងាច',
);
