<?php
/**
 * Locale data for 'kn'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.60',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##,##0%',
  'currencyFormat' => '¤ #,##,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => 'रु',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ಜನವರೀ',
      2 => 'ಫೆಬ್ರವರೀ',
      3 => 'ಮಾರ್ಚ್',
      4 => 'ಎಪ್ರಿಲ್',
      5 => 'ಮೆ',
      6 => 'ಜೂನ್',
      7 => 'ಜುಲೈ',
      8 => 'ಆಗಸ್ಟ್',
      9 => 'ಸಪ್ಟೆಂಬರ್',
      10 => 'ಅಕ್ಟೋಬರ್',
      11 => 'ನವೆಂಬರ್',
      12 => 'ಡಿಸೆಂಬರ್',
    ),
    'abbreviated' => 
    array (
      1 => 'ಜನವರೀ',
      2 => 'ಫೆಬ್ರವರೀ',
      3 => 'ಮಾರ್ಚ್',
      4 => 'ಎಪ್ರಿಲ್',
      5 => 'ಮೆ',
      6 => 'ಜೂನ್',
      7 => 'ಜುಲೈ',
      8 => 'ಆಗಸ್ಟ್',
      9 => 'ಸಪ್ಟೆಂಬರ್',
      10 => 'ಅಕ್ಟೋಬರ್',
      11 => 'ನವೆಂಬರ್',
      12 => 'ಡಿಸೆಂಬರ್',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ರವಿವಾರ',
      1 => 'ಸೋಮವಾರ',
      2 => 'ಮಂಗಳವಾರ',
      3 => 'ಬುಧವಾರ',
      4 => 'ಗುರುವಾರ',
      5 => 'ಶುಕ್ರವಾರ',
      6 => 'ಶನಿವಾರ',
    ),
    'abbreviated' => 
    array (
      0 => 'ರ.',
      1 => 'ಸೋ.',
      2 => 'ಮಂ.',
      3 => 'ಬು.',
      4 => 'ಗು.',
      5 => 'ಶು.',
      6 => 'ಶನಿ.',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'ಈಸಪೂವ೯.',
      1 => 'ಸನ್.',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'dd-MM-yyyy',
    'short' => 'd-M-yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'hh:mm:ss a v',
    'long' => 'hh:mm:ss a z',
    'medium' => 'hh:mm:ss a',
    'short' => 'hh:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'ಪೂರ್ವಾಹ್ನ',
  'pmName' => 'ಅಪರಾಹ್ನ',
);
