<?php
/**
 * Locale data for 'ko_KR'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.55',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => '₤',
    'JPY' => '￥',
    'USD' => 'US$',
    'ALL' => '레크',
    'AMD' => '드램',
    'AUD' => 'A$',
    'BBD' => 'BDS$',
    'BMD' => 'BM$',
    'BND' => 'B$',
    'BZD' => 'BZ$',
    'CAD' => 'Can$',
    'CLP' => 'Ch$',
    'CNY' => '¥',
    'COP' => 'Col$',
    'CYP' => '￡C',
    'DOP' => 'RD$',
    'FJD' => 'F$',
    'FRF' => '₣',
    'GYD' => 'G$',
    'HKD' => 'HK$',
    'IEP' => 'IR£',
    'KPW' => '₩',
    'KRW' => '￦',
    'MRO' => 'UM',
    'SGD' => 'S$',
    'TWD' => 'NT$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => '1월',
      2 => '2월',
      3 => '3월',
      4 => '4월',
      5 => '5월',
      6 => '6월',
      7 => '7월',
      8 => '8월',
      9 => '9월',
      10 => '10월',
      11 => '11월',
      12 => '12월',
    ),
    'abbreviated' => 
    array (
      1 => '1월',
      2 => '2월',
      3 => '3월',
      4 => '4월',
      5 => '5월',
      6 => '6월',
      7 => '7월',
      8 => '8월',
      9 => '9월',
      10 => '10월',
      11 => '11월',
      12 => '12월',
    ),
    'narrow' => 
    array (
      1 => '1월',
      2 => '2월',
      3 => '3월',
      4 => '4월',
      5 => '5월',
      6 => '6월',
      7 => '7월',
      8 => '8월',
      9 => '9월',
      10 => '10월',
      11 => '11월',
      12 => '12월',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => '일요일',
      1 => '월요일',
      2 => '화요일',
      3 => '수요일',
      4 => '목요일',
      5 => '금요일',
      6 => '토요일',
    ),
    'abbreviated' => 
    array (
      0 => '일',
      1 => '월',
      2 => '화',
      3 => '수',
      4 => '목',
      5 => '금',
      6 => '토',
    ),
    'narrow' => 
    array (
      0 => '일',
      1 => '월',
      2 => '화',
      3 => '수',
      4 => '목',
      5 => '금',
      6 => '토',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => '기원전',
      1 => '서기',
    ),
    'wide' => 
    array (
      0 => '서력기원전',
      1 => '서력기원',
    ),
    'narrow' => 
    array (
      0 => '기원전',
      1 => '서기',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'yyyy년 M월 d일 EEEE',
    'long' => 'yyyy년 M월 d일',
    'medium' => 'yyyy. M. d.',
    'short' => 'yy. M. d.',
  ),
  'timeFormats' => 
  array (
    'full' => 'a hh시 mm분 ss초 v',
    'long' => 'a hh시 mm분 ss초 z',
    'medium' => 'a h:mm:ss',
    'short' => 'a h:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => '오전',
  'pmName' => '오후',
);
