<?php
/**
 * Locale data for 'kok'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.56',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##,##0%',
  'currencyFormat' => '¤ #,##,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => 'रु',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'जानेवारी',
      2 => 'फेब्रुवारी',
      3 => 'मार्च',
      4 => 'एप्रिल',
      5 => 'मे',
      6 => 'जून',
      7 => 'जुलै',
      8 => 'ओगस्ट',
      9 => 'सेप्टेंबर',
      10 => 'ओक्टोबर',
      11 => 'नोव्हेंबर',
      12 => 'डिसेंबर',
    ),
    'abbreviated' => 
    array (
      1 => 'जानेवारी',
      2 => 'फेबृवारी',
      3 => 'मार्च',
      4 => 'एप्रिल',
      5 => 'मे',
      6 => 'जून',
      7 => 'जुलै',
      8 => 'ओगस्ट',
      9 => 'सेप्टेंबर',
      10 => 'ओक्टोबर',
      11 => 'नोव्हेंबर',
      12 => 'डिसेंबर',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'आदित्यवार',
      1 => 'सोमवार',
      2 => 'मंगळार',
      3 => 'बुधवार',
      4 => 'गुरुवार',
      5 => 'शुक्रवार',
      6 => 'शनिवार',
    ),
    'abbreviated' => 
    array (
      0 => 'रवि',
      1 => 'सोम',
      2 => 'मंगळ',
      3 => 'बुध',
      4 => 'गुरु',
      5 => 'शुक्र',
      6 => 'शनि',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'क्रिस्तपूर्व',
      1 => 'क्रिस्तशखा',
    ),
    'wide' => 
    array (
      0 => 'क्रिस्तपूर्व',
      1 => 'क्रिस्तशखा',
    ),
    'narrow' => 
    array (
      0 => 'क्रिस्तपूर्व',
      1 => 'क्रिस्तशखा',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'dd-MM-yyyy',
    'short' => 'd-M-yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'म.पू.',
  'pmName' => 'म.नं.',
);
