<?php
/**
 * Locale data for 'ku_Latn_TR'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.10',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'çile',
      2 => 'sibat',
      3 => 'adar',
      4 => 'nîsan',
      5 => 'gulan',
      6 => 'hezîran',
    ),
    'abbreviated' => 
    array (
      1 => 'çil',
      2 => 'sib',
      3 => 'adr',
      4 => 'nîs',
      5 => 'gul',
      6 => 'hez',
      7 => 'tîr',
    ),
    'narrow' => 
    array (
      1 => 'ç',
      2 => 's',
      3 => 'a',
      4 => 'n',
      5 => 'g',
      6 => 'h',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'yekşem',
      1 => 'duşem',
      2 => 'şê',
      3 => 'çarşem',
      4 => 'pêncşem',
      5 => 'în',
      6 => 'şemî',
    ),
    'abbreviated' => 
    array (
      0 => 'yş',
      1 => 'dş',
      2 => 'sş',
      3 => 'çş',
      4 => 'pş',
      5 => 'în',
      6 => 'ş',
    ),
    'narrow' => 
    array (
      0 => 'y',
      1 => 'd',
      2 => 's',
      3 => 'ç',
      4 => 'p',
      5 => 'î',
      6 => 'ş',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BZ',
      1 => 'PZ',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'BN',
  'pmName' => 'PN',
);
