<?php
/**
 * Locale data for 'kw_GB'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '9061',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'superscriptingExponent' => '×',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'ARS' => '$',
    'AUD' => 'A$',
    'BBD' => '$',
    'BDT' => '৳',
    'BMD' => '$',
    'BND' => '$',
    'BRL' => 'R$',
    'BSD' => '$',
    'BYR' => 'р.',
    'BZD' => '$',
    'CAD' => 'CA$',
    'CLP' => '$',
    'CNY' => 'CN¥',
    'COP' => '$',
    'CRC' => '₡',
    'CUP' => '$',
    'DOP' => '$',
    'ESP' => '₧',
    'EUR' => '€',
    'FJD' => '$',
    'GBP' => '£',
    'GHS' => '₵',
    'GIP' => '£',
    'GYD' => '$',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JMD' => '$',
    'JPY' => 'JP¥',
    'KHR' => '៛',
    'KRW' => '₩',
    'KYD' => '$',
    'KZT' => '₸',
    'LAK' => '₭',
    'LRD' => '$',
    'MNT' => '₮',
    'MXN' => 'MX$',
    'NAD' => '$',
    'NGN' => '₦',
    'NZD' => 'NZ$',
    'PHP' => '₱',
    'PYG' => '₲',
    'RUR' => 'р.',
    'SBD' => '$',
    'SGD' => '$',
    'SRD' => '$',
    'SSP' => '£',
    'THB' => '฿',
    'TRY' => '₺',
    'TTD' => '$',
    'TWD' => 'NT$',
    'UAH' => '₴',
    'USD' => 'US$',
    'UYU' => '$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Mys Genver',
      2 => 'Mys Whevrel',
      3 => 'Mys Merth',
      4 => 'Mys Ebrel',
      5 => 'Mys Me',
      6 => 'Mys Efan',
      7 => 'Mys Gortheren',
      8 => 'Mye Est',
      9 => 'Mys Gwyngala',
      10 => 'Mys Hedra',
      11 => 'Mys Du',
      12 => 'Mys Kevardhu',
    ),
    'abbreviated' => 
    array (
      1 => 'Gen',
      2 => 'Whe',
      3 => 'Mer',
      4 => 'Ebr',
      5 => 'Me',
      6 => 'Efn',
      7 => 'Gor',
      8 => 'Est',
      9 => 'Gwn',
      10 => 'Hed',
      11 => 'Du',
      12 => 'Kev',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'De Sul',
      1 => 'De Lun',
      2 => 'De Merth',
      3 => 'De Merher',
      4 => 'De Yow',
      5 => 'De Gwener',
      6 => 'De Sadorn',
    ),
    'abbreviated' => 
    array (
      0 => 'Sul',
      1 => 'Lun',
      2 => 'Mth',
      3 => 'Mhr',
      4 => 'Yow',
      5 => 'Gwe',
      6 => 'Sad',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'T',
      3 => 'W',
      4 => 'T',
      5 => 'F',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'RC',
      1 => 'AD',
    ),
    'wide' => 
    array (
      0 => 'RC',
      1 => 'AD',
    ),
    'narrow' => 
    array (
      0 => 'RC',
      1 => 'AD',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'dd/MM/y',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'a.m.',
  'pmName' => 'p.m.',
  'orientation' => 'ltr',
  'pluralRules' => 
  array (
    0 => 'n = 1 @integer 1 @decimal 1.0, 1.00, 1.000, 1.0000',
    1 => 'n = 2 @integer 2 @decimal 2.0, 2.00, 2.000, 2.0000',
    2 => ' @integer 0, 3~17, 100, 1000, 10000, 100000, 1000000, … @decimal 0.0~0.9, 1.1~1.6, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …',
    3 => 'true',
  ),
  'languages' => 
  array (
    'ar' => 'Arabek',
    'cy' => 'Kembrek',
    'da' => 'Danek',
    'de' => 'Almaynek',
    'en' => 'Sowsnek',
    'es' => 'Spaynek',
    'eu' => 'Baskek',
    'fr' => 'Frenkek',
    'ga' => 'Wordhonek',
    'it' => 'Italek',
    'ja' => 'Japanek',
    'kw' => 'kernewek',
    'nl' => 'Iseldiryek',
    'pt' => 'Portyngalek',
    'pt_br' => 'Portyngalek Brasil',
    'ru' => 'Russek',
    'yue' => 'Kantonek',
    'zh' => 'Chinek',
    'zh_hans' => 'Chinek sempel',
    'zh_hant' => 'Chînek Tradycyonal',
  ),
  'scripts' => 
  array (
    'arab' => 'Arabek',
  ),
  'territories' => 
  array (
    'br' => 'Brasil',
    'cn' => 'China',
    'de' => 'Almayn',
    'fr' => 'Pow Frenk',
    'gb' => 'Rywvaneth Unys',
    'in' => 'Eynda',
    'it' => 'Itali',
    'jp' => 'Japan',
    'ru' => 'Russi',
    'us' => 'Statys Unys',
  ),
);
