<?php
/**
 * Locale data for 'ln_CG'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.14',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'CDF' => 'Fc',
    'CHF' => 'Fr.',
    'XXX' => 'XXX',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'sánzá ya yambo',
      2 => 'sánzá ya míbalé',
      3 => 'sánzá ya mísáto',
      4 => 'sánzá ya mínei',
      5 => 'sánzá ya mítáno',
      6 => 'sánzá ya motóbá',
      7 => 'sánzá ya nsambo',
      8 => 'sánzá ya mwambe',
      9 => 'sánzá ya libwa',
      10 => 'sánzá ya zómi',
      11 => 'sánzá ya zómi na mɔ̌kɔ́',
      12 => 'sánzá ya zómi na míbalé',
    ),
    'abbreviated' => 
    array (
      1 => 's1',
      2 => 's2',
      3 => 's3',
      4 => 's4',
      5 => 's5',
      6 => 's6',
      7 => 's7',
      8 => 's8',
      9 => 's9',
      10 => 's10',
      11 => 's11',
      12 => 's12',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'eyenga',
      1 => 'mokɔlɔ ya libosó',
      2 => 'mokɔlɔ ya míbalé',
      3 => 'mokɔlɔ ya mísáto',
      4 => 'mokɔlɔ ya mínéi',
      5 => 'mokɔlɔ ya mítáno',
      6 => 'mpɔ́sɔ',
    ),
    'abbreviated' => 
    array (
      0 => 'eye',
      1 => 'm1',
      2 => 'm2',
      3 => 'm3',
      4 => 'm4',
      5 => 'm5',
      6 => 'mps',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'libosó ya Y.-K.',
      1 => 'nsima ya Y.-K.',
    ),
    'wide' => 
    array (
      0 => 'libosó ya Y.-K.',
      1 => 'nsima ya Y.-K.',
    ),
    'narrow' => 
    array (
      0 => 'libosó ya Y.-K.',
      1 => 'nsima ya Y.-K.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
