<?php
/**
 * Locale data for 'lo_LA'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.38',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00;¤-#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'LAK' => '₭',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ມັງກອນ',
      2 => 'ກຸມພາ',
      3 => 'ມີນາ',
      4 => 'ເມສາ',
      5 => 'ພຶດສະພາ',
      6 => 'ມິຖຸນາ',
      7 => 'ກໍລະກົດ',
      8 => 'ສິງຫາ',
      9 => 'ກັນຍາ',
      10 => 'ຕຸລາ',
      11 => 'ພະຈິກ',
      12 => 'ທັນວາ',
    ),
    'abbreviated' => 
    array (
      1 => 'ມ.ກ.',
      2 => 'ກ.ພ.',
      3 => 'ມີ.ນ.',
      4 => 'ມ.ສ..',
      5 => 'ພ.ພ.',
      6 => 'ມິ.ຖ.',
      7 => 'ກ.ລ.',
      8 => 'ສ.ຫ.',
      9 => 'ກ.ຍ.',
      10 => 'ຕ.ລ.',
      11 => 'ພ.ຈ.',
      12 => 'ທ.ວ.',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ວັນອາທິດ',
      1 => 'ວັນຈັນ',
      2 => 'ວັນອັງຄານ',
      3 => 'ວັນພຸດ',
      4 => 'ວັນພະຫັດ',
      5 => 'ວັນສຸກ',
      6 => 'ວັນເສົາ',
    ),
    'abbreviated' => 
    array (
      0 => 'ອາ.',
      1 => 'ຈ.',
      2 => 'ອ.',
      3 => 'ພ.',
      4 => 'ພຫ.',
      5 => 'ສກ.',
      6 => 'ສ.',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ປີກ່ອນຄິດສະການທີ່',
      1 => 'ຄ.ສ.',
    ),
    'wide' => 
    array (
      0 => 'ປີກ່ອນຄິດສະການທີ່',
      1 => 'ຄິດສະການທີ່',
    ),
    'narrow' => 
    array (
      0 => 'ປີກ່ອນຄິດສະການທີ່',
      1 => 'ຄ.ສ.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEEທີ  d MMMM G yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'd MMM yyyy',
    'short' => 'd/M/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'Hໂມງ mນາທີ ss ວິນາທີv',
    'long' => 'H ໂມງ mນາທີss z',
    'medium' => 'H:mm:ss',
    'short' => 'H:mm',
  ),
  'dateTimeFormat' => '{1}, {0}',
  'amName' => 'ກ່ອນທ່ຽງ',
  'pmName' => 'ຫລັງທ່ຽງ',
);
