<?php
/**
 * Locale data for 'lt'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.92',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '−',
    'exponential' => '×10^',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'LTL' => 'Lt',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'sausio',
      2 => 'vasario',
      3 => 'kovo',
      4 => 'balandžio',
      5 => 'gegužės',
      6 => 'birželio',
      7 => 'liepos',
      8 => 'rugpjūčio',
      9 => 'rugsėjo',
      10 => 'spalio',
      11 => 'lapkričio',
      12 => 'gruodžio',
    ),
    'abbreviated' => 
    array (
      1 => 'Sau',
      2 => 'Vas',
      3 => 'Kov',
      4 => 'Bal',
      5 => 'Geg',
      6 => 'Bir',
      7 => 'Lie',
      8 => 'Rgp',
      9 => 'Rgs',
      10 => 'Spl',
      11 => 'Lap',
      12 => 'Grd',
    ),
    'narrow' => 
    array (
      1 => 'S',
      2 => 'V',
      3 => 'K',
      4 => 'B',
      5 => 'G',
      6 => 'B',
      7 => 'L',
      8 => 'R',
      9 => 'R',
      10 => 'S',
      11 => 'L',
      12 => 'G',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'sekmadienis',
      1 => 'pirmadienis',
      2 => 'antradienis',
      3 => 'trečiadienis',
      4 => 'ketvirtadienis',
      5 => 'penktadienis',
      6 => 'šeštadienis',
    ),
    'abbreviated' => 
    array (
      0 => 'Sk',
      1 => 'Pr',
      2 => 'An',
      3 => 'Tr',
      4 => 'Kt',
      5 => 'Pn',
      6 => 'Št',
    ),
    'narrow' => 
    array (
      0 => 'S',
      1 => 'P',
      2 => 'A',
      3 => 'T',
      4 => 'K',
      5 => 'P',
      6 => 'Š',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'pr. Kr.',
      1 => 'po Kr.',
    ),
    'wide' => 
    array (
      0 => 'pr. Kr.',
      1 => 'po Kr.',
    ),
    'narrow' => 
    array (
      0 => 'pr. Kr.',
      1 => 'po Kr.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'yyyy \'m\'. MMMM d \'d\'.,EEEE',
    'long' => 'yyyy \'m\'. MMMM d \'d\'.',
    'medium' => 'yyyy.MM.dd',
    'short' => 'yyyy-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'priešpiet',
  'pmName' => 'popiet',
);
