<?php
/**
 * Locale data for 'lv_LV'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.46',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'LVL' => 'Ls',
    'XXX' => 'XXX',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'janvāris',
      2 => 'februāris',
      3 => 'marts',
      4 => 'aprīlis',
      5 => 'maijs',
      6 => 'jūnijs',
      7 => 'jūlijs',
      8 => 'augusts',
      9 => 'septembris',
      10 => 'oktobris',
      11 => 'novembris',
      12 => 'decembris',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Feb',
      3 => 'Mar',
      4 => 'Apr',
      5 => 'Mai',
      6 => 'Jūn',
      7 => 'Jūl',
      8 => 'Aug',
      9 => 'Sep',
      10 => 'Okt',
      11 => 'Nov',
      12 => 'Dec',
    ),
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'J',
      7 => 'J',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'svētdiena',
      1 => 'pirmdiena',
      2 => 'otrdiena',
      3 => 'trešdiena',
      4 => 'ceturtdiena',
      5 => 'piektdiena',
      6 => 'sestdiena',
    ),
    'abbreviated' => 
    array (
      0 => 'sv',
      1 => 'pr',
      2 => 'ot',
      3 => 'tr',
      4 => 'ce',
      5 => 'pk',
      6 => 'se',
    ),
    'narrow' => 
    array (
      0 => 'S',
      1 => 'P',
      2 => 'O',
      3 => 'T',
      4 => 'C',
      5 => 'P',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'p.m.ē.',
      1 => 'm.ē.',
    ),
    'wide' => 
    array (
      0 => 'pirms mūsu ēras',
      1 => 'mūsu ērā',
    ),
    'narrow' => 
    array (
      0 => 'p.m.ē.',
      1 => 'm.ē.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy. \'gada\' d. MMMM',
    'long' => 'yyyy. \'gada\' d. MMMM',
    'medium' => 'yyyy.d.M',
    'short' => 'yy.d.M',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
