<?php
/**
 * Locale data for 'ms'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.59',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00;(¤#,##0.00)',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'MYR' => 'RM',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Januari',
      2 => 'Februari',
      3 => 'Mac',
      4 => 'April',
      5 => 'Mei',
      6 => 'Jun',
      7 => 'Julai',
      8 => 'Ogos',
      9 => 'September',
      10 => 'Oktober',
      11 => 'November',
      12 => 'Disember',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Feb',
      3 => 'Mac',
      4 => 'Apr',
      5 => 'Mei',
      6 => 'Jun',
      7 => 'Jul',
      8 => 'Ogos',
      9 => 'Sep',
      10 => 'Okt',
      11 => 'Nov',
      12 => 'Dis',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Ahad',
      1 => 'Isnin',
      2 => 'Selasa',
      3 => 'Rabu',
      4 => 'Khamis',
      5 => 'Jumaat',
      6 => 'Sabtu',
    ),
    'abbreviated' => 
    array (
      0 => 'Ahd',
      1 => 'Isn',
      2 => 'Sel',
      3 => 'Rab',
      4 => 'Kha',
      5 => 'Jum',
      6 => 'Sab',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'S.M.',
      1 => 'T.M.',
    ),
    'wide' => 
    array (
      0 => 'S.M.',
      1 => 'T.M.',
    ),
    'narrow' => 
    array (
      0 => 'S.M.',
      1 => 'T.M.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE dd MMM yyyy',
    'long' => 'dd MMMM yyyy',
    'medium' => 'dd MMM yyyy',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
