<?php
/**
 * Locale data for 'my'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.26',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => '၊',
    'percentSign' => '%',
    'nativeZeroDigit' => '၀',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'MMK' => 'K',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ဇန်နဝါရီ',
      2 => 'ဖေဖော်ဝါရီ',
      3 => 'မတ်',
      4 => 'ဧပြီ',
      5 => 'မေ',
      6 => 'ဇွန်',
      7 => 'ဇူလိုင်',
      8 => 'ဩဂုတ်',
      9 => 'စက်တင်ဘာ',
      10 => 'အောက်တိုဘာ',
      11 => 'နိုဝင်ဘာ',
      12 => 'ဒီဇင်ဘာ',
    ),
    'abbreviated' => 
    array (
      1 => 'ဇန်',
      2 => 'ဖေ',
      3 => 'မတ်',
      4 => 'ဧ',
      5 => 'မေ',
      6 => 'ဇွန်',
      7 => 'ဇူ',
      8 => 'ဩ',
      9 => 'စက်',
      10 => 'အောက်',
      11 => 'နို',
      12 => 'ဒီ',
    ),
    'narrow' => 
    array (
      1 => 'ဇ',
      2 => 'ဖ',
      3 => 'မ',
      4 => 'ဧ',
      5 => 'မ',
      6 => 'ဇ',
      7 => 'ဇ',
      8 => 'ဩ',
      9 => 'စ',
      10 => 'အ',
      11 => 'န',
      12 => 'ဒ',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'တနင်္ဂနွေ',
      1 => 'တနင်္လာ',
      2 => 'အင်္ဂါ',
      3 => 'ဗုဒ္ဓဟူး',
      4 => 'ကြာသပတေး',
      5 => 'သောကြာ',
      6 => 'စနေ',
    ),
    'abbreviated' => 
    array (
      0 => 'နွေ',
      1 => 'လာ',
      2 => 'ဂါ',
      3 => 'ဟူး',
      4 => 'တေး',
      5 => 'ကြာ',
      6 => 'နေ',
    ),
    'narrow' => 
    array (
      0 => 'တ',
      1 => 'တ',
      2 => 'အ',
      3 => 'ဗ',
      4 => 'က',
      5 => 'သ',
      6 => 'စ',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ဘီစီ',
      1 => 'အေဒီ',
    ),
    'wide' => 
    array (
      0 => 'ခရစ်တော် မပေါ်မီကာလ',
      1 => 'ခရစ်တော် ပေါ်ထွန်းပြီးကာလ',
    ),
    'narrow' => 
    array (
      0 => 'ဘီစီ',
      1 => 'အေဒီ',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'နံနက်',
  'pmName' => 'ညနေ',
);
