<?php
/**
 * Locale data for 'nb_NO'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.45',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0 %',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'BRL',
    'EUR' => 'EUR',
    'GBP' => 'GBP',
    'INR' => 'INR',
    'ITL' => 'ITL',
    'JPY' => 'JPY',
    'USD' => 'USD',
    'BGL' => 'lev',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'januar',
      2 => 'februar',
      3 => 'mars',
      4 => 'april',
      5 => 'mai',
      6 => 'juni',
      7 => 'juli',
      8 => 'august',
      9 => 'september',
      10 => 'oktober',
      11 => 'november',
      12 => 'desember',
    ),
    'abbreviated' => 
    array (
      1 => 'jan.',
      2 => 'feb.',
      3 => 'mars',
      4 => 'apr.',
      5 => 'mai',
      6 => 'juni',
      7 => 'juli',
      8 => 'aug.',
      9 => 'sep.',
      10 => 'okt.',
      11 => 'nov.',
      12 => 'des.',
    ),
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'J',
      7 => 'J',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'søndag',
      1 => 'mandag',
      2 => 'tirsdag',
      3 => 'onsdag',
      4 => 'torsdag',
      5 => 'fredag',
      6 => 'lørdag',
    ),
    'abbreviated' => 
    array (
      0 => 'sø.',
      1 => 'ma.',
      2 => 'ti.',
      3 => 'on.',
      4 => 'to.',
      5 => 'fr.',
      6 => 'lø.',
    ),
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'T',
      3 => 'O',
      4 => 'T',
      5 => 'F',
      6 => 'L',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'f.Kr.',
      1 => 'e.Kr.',
    ),
    'wide' => 
    array (
      0 => 'f.Kr.',
      1 => 'e.Kr.',
    ),
    'narrow' => 
    array (
      0 => 'f.Kr.',
      1 => 'e.Kr.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d. MMMM yyyy',
    'long' => 'd. MMMM yyyy',
    'medium' => 'd. MMM yyyy',
    'short' => 'dd.MM.yy',
  ),
  'timeFormats' => 
  array (
    'full' => '\'kl\'. HH.mm.ss v',
    'long' => 'HH.mm.ss z',
    'medium' => 'HH.mm.ss',
    'short' => 'HH.mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'formiddag',
  'pmName' => 'ettermiddag',
);
