<?php
/**
 * Locale data for 'nnh_CM'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2013 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2014 Yii Software LLC (https://www.yiiframework.com/license/)
 */
return array (
  'version' => '8245',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ',',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'A$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'saŋ tsetsɛ̀ɛ lùm',
      2 => 'saŋ kàg ngwóŋ',
      3 => 'saŋ lepyè shúm',
      4 => 'saŋ cÿó',
      5 => 'saŋ tsɛ̀ɛ cÿó',
      6 => 'saŋ njÿoláʼ',
      7 => 'saŋ tyɛ̀b tyɛ̀b mbʉ̀',
      8 => 'saŋ mbʉ̀ŋ',
      9 => 'saŋ ngwɔ̀ʼ mbÿɛ',
      10 => 'saŋ tàŋa tsetsáʼ',
      11 => 'saŋ mejwoŋó',
      12 => 'saŋ lùm',
    ),
    'abbreviated' => 
    array (
      1 => 'saŋ tsetsɛ̀ɛ lùm',
      2 => 'saŋ kàg ngwóŋ',
      3 => 'saŋ lepyè shúm',
      4 => 'saŋ cÿó',
      5 => 'saŋ tsɛ̀ɛ cÿó',
      6 => 'saŋ njÿoláʼ',
      7 => 'saŋ tyɛ̀b tyɛ̀b mbʉ̀',
      8 => 'saŋ mbʉ̀ŋ',
      9 => 'saŋ ngwɔ̀ʼ mbÿɛ',
      10 => 'saŋ tàŋa tsetsáʼ',
      11 => 'saŋ mejwoŋó',
      12 => 'saŋ lùm',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
    'abbreviated' => 
    array (
      1 => 'saŋ tsetsɛ̀ɛ lùm',
      2 => 'saŋ kàg ngwóŋ',
      3 => 'saŋ lepyè shúm',
      4 => 'saŋ cÿó',
      5 => 'saŋ tsɛ̀ɛ cÿó',
      6 => 'saŋ njÿoláʼ',
      7 => 'saŋ tyɛ̀b tyɛ̀b mbʉ̀',
      8 => 'saŋ mbʉ̀ŋ',
      9 => 'saŋ ngwɔ̀ʼ mbÿɛ',
      10 => 'saŋ tàŋa tsetsáʼ',
      11 => 'saŋ mejwoŋó',
      12 => 'saŋ lùm',
    ),
    'wide' => 
    array (
      1 => 'saŋ tsetsɛ̀ɛ lùm',
      2 => 'saŋ kàg ngwóŋ',
      3 => 'saŋ lepyè shúm',
      4 => 'saŋ cÿó',
      5 => 'saŋ tsɛ̀ɛ cÿó',
      6 => 'saŋ njÿoláʼ',
      7 => 'saŋ tyɛ̀b tyɛ̀b mbʉ̀',
      8 => 'saŋ mbʉ̀ŋ',
      9 => 'saŋ ngwɔ̀ʼ mbÿɛ',
      10 => 'saŋ tàŋa tsetsáʼ',
      11 => 'saŋ mejwoŋó',
      12 => 'saŋ lùm',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'lyɛʼɛ́ sẅíŋtè',
      1 => 'mvfò lyɛ̌ʼ',
      2 => 'mbɔ́ɔntè mvfò lyɛ̌ʼ',
      3 => 'tsètsɛ̀ɛ lyɛ̌ʼ',
      4 => 'mbɔ́ɔntè tsetsɛ̀ɛ lyɛ̌ʼ',
      5 => 'mvfò màga lyɛ̌ʼ',
      6 => 'màga lyɛ̌ʼ',
    ),
    'abbreviated' => 
    array (
      0 => 'lyɛʼɛ́ sẅíŋtè',
      1 => 'mvfò lyɛ̌ʼ',
      2 => 'mbɔ́ɔntè mvfò lyɛ̌ʼ',
      3 => 'tsètsɛ̀ɛ lyɛ̌ʼ',
      4 => 'mbɔ́ɔntè tsetsɛ̀ɛ lyɛ̌ʼ',
      5 => 'mvfò màga lyɛ̌ʼ',
      6 => 'màga lyɛ̌ʼ',
    ),
    'short' => 
    array (
      0 => 'lyɛʼɛ́ sẅíŋtè',
      1 => 'mvfò lyɛ̌ʼ',
      2 => 'mbɔ́ɔntè mvfò lyɛ̌ʼ',
      3 => 'tsètsɛ̀ɛ lyɛ̌ʼ',
      4 => 'mbɔ́ɔntè tsetsɛ̀ɛ lyɛ̌ʼ',
      5 => 'mvfò màga lyɛ̌ʼ',
      6 => 'màga lyɛ̌ʼ',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'T',
      3 => 'W',
      4 => 'T',
      5 => 'F',
      6 => 'S',
    ),
    'abbreviated' => 
    array (
      0 => 'lyɛʼɛ́ sẅíŋtè',
      1 => 'mvfò lyɛ̌ʼ',
      2 => 'mbɔ́ɔntè mvfò lyɛ̌ʼ',
      3 => 'tsètsɛ̀ɛ lyɛ̌ʼ',
      4 => 'mbɔ́ɔntè tsetsɛ̀ɛ lyɛ̌ʼ',
      5 => 'mvfò màga lyɛ̌ʼ',
      6 => 'màga lyɛ̌ʼ',
    ),
    'short' => 
    array (
      0 => 'lyɛʼɛ́ sẅíŋtè',
      1 => 'mvfò lyɛ̌ʼ',
      2 => 'mbɔ́ɔntè mvfò lyɛ̌ʼ',
      3 => 'tsètsɛ̀ɛ lyɛ̌ʼ',
      4 => 'mbɔ́ɔntè tsetsɛ̀ɛ lyɛ̌ʼ',
      5 => 'mvfò màga lyɛ̌ʼ',
      6 => 'màga lyɛ̌ʼ',
    ),
    'wide' => 
    array (
      0 => 'lyɛʼɛ́ sẅíŋtè',
      1 => 'mvfò lyɛ̌ʼ',
      2 => 'mbɔ́ɔntè mvfò lyɛ̌ʼ',
      3 => 'tsètsɛ̀ɛ lyɛ̌ʼ',
      4 => 'mbɔ́ɔntè tsetsɛ̀ɛ lyɛ̌ʼ',
      5 => 'mvfò màga lyɛ̌ʼ',
      6 => 'màga lyɛ̌ʼ',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'm.z.Y.',
      1 => 'm.g.n.Y.',
    ),
    'wide' => 
    array (
      0 => 'mé zyé Yěsô',
      1 => 'mé gÿo ńzyé Yěsô',
    ),
    'narrow' => 
    array (
      0 => 'm.z.Y.',
      1 => 'm.g.n.Y.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE , \'lyɛ\'̌ʼ d \'na\' MMMM, y',
    'long' => '\'lyɛ\'̌ʼ d \'na\' MMMM, y',
    'medium' => 'd MMM, y',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss a',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1},{0}',
  'amName' => 'mbaʼámbaʼ',
  'pmName' => 'ncwònzém',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'bas' => 'Shwóŋò pʉa mbasǎ',
    'bax' => 'Shwóŋò pamom',
    'bbj' => 'Shwóŋò pʉa nzsekàʼa',
    'bfd' => 'Shwóŋò pafut',
    'bkm' => 'Shwóŋò pʉ̀a njinikom',
    'bss' => 'Shwóŋò pakɔsi',
    'bum' => 'Shwóŋò mbulu',
    'byv' => 'Shwóŋò ngáŋtʉɔʼ',
    'de' => 'nzǎmɔ̂ɔn',
    'en' => 'ngilísè',
    'ewo' => 'Shwóŋò pʉa Yɔɔnmendi',
    'ff' => 'Shwóŋò menkesaŋ',
    'fr' => 'felaŋsée',
    'kkj' => 'Shwóŋò pʉa shÿó Bɛgtùa',
    'nnh' => 'Shwóŋò ngiembɔɔn',
    'yav' => 'Shwóŋò pʉa shÿó Mbafìa',
    'ybb' => 'Shwóŋò Tsaŋ',
  ),
  'territories' => 
  array (
    'cm' => 'Kàmalûm',
  ),
  'pluralRules' => 
  array (
    0 => 'n==1',
    1 => 'true',
  ),
);
