<?php
/**
 * Locale data for 'nr_ZA'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.13',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'ZAR' => 'R',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Janabari',
      2 => 'uFeberbari',
      3 => 'uMatjhi',
      4 => 'u-Apreli',
      5 => 'Meyi',
      6 => 'Juni',
      7 => 'Julayi',
      8 => 'Arhostosi',
      9 => 'Septemba',
      10 => 'Oktoba',
      11 => 'Usinyikhaba',
      12 => 'Disemba',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Feb',
      3 => 'Mat',
      4 => 'Apr',
      5 => 'Mey',
      6 => 'Jun',
      7 => 'Jul',
      8 => 'Arh',
      9 => 'Sep',
      10 => 'Okt',
      11 => 'Usi',
      12 => 'Dis',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'uSonto',
      1 => 'uMvulo',
      2 => 'uLesibili',
      3 => 'Lesithathu',
      4 => 'uLesine',
      5 => 'ngoLesihlanu',
      6 => 'umGqibelo',
    ),
    'abbreviated' => 
    array (
      0 => 'Son',
      1 => 'Mvu',
      2 => 'Bil',
      3 => 'Tha',
      4 => 'Ne',
      5 => 'Hla',
      6 => 'Gqi',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BC',
      1 => 'AD',
    ),
    'wide' => 
    array (
      0 => 'BC',
      1 => 'AD',
    ),
    'narrow' => 
    array (
      0 => 'BC',
      1 => 'AD',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
