<?php
/**
 * Locale data for 'nso_ZA'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '9061',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'superscriptingExponent' => '×',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'ARS' => '$',
    'AUD' => 'A$',
    'BBD' => '$',
    'BDT' => '৳',
    'BMD' => '$',
    'BND' => '$',
    'BRL' => 'R$',
    'BSD' => '$',
    'BYR' => 'р.',
    'BZD' => '$',
    'CAD' => 'CA$',
    'CLP' => '$',
    'CNY' => 'CN¥',
    'COP' => '$',
    'CRC' => '₡',
    'CUP' => '$',
    'DOP' => '$',
    'ESP' => '₧',
    'EUR' => '€',
    'FJD' => '$',
    'GBP' => '£',
    'GHS' => '₵',
    'GIP' => '£',
    'GYD' => '$',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JMD' => '$',
    'JPY' => 'JP¥',
    'KHR' => '៛',
    'KRW' => '₩',
    'KYD' => '$',
    'KZT' => '₸',
    'LAK' => '₭',
    'LRD' => '$',
    'MNT' => '₮',
    'MXN' => 'MX$',
    'NAD' => '$',
    'NGN' => '₦',
    'NZD' => 'NZ$',
    'PHP' => '₱',
    'PYG' => '₲',
    'RUR' => 'р.',
    'SBD' => '$',
    'SGD' => '$',
    'SRD' => '$',
    'SSP' => '£',
    'THB' => '฿',
    'TRY' => '₺',
    'TTD' => '$',
    'TWD' => 'NT$',
    'UAH' => '₴',
    'USD' => 'US$',
    'UYU' => '$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'ZAR' => 'R',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Janaware',
      2 => 'Feberware',
      3 => 'Matšhe',
      4 => 'Aporele',
      5 => 'Mei',
      6 => 'June',
      7 => 'Julae',
      8 => 'Agostose',
      9 => 'Setemere',
      10 => 'Oktobore',
      11 => 'Nofemere',
      12 => 'Disemere',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Feb',
      3 => 'Mat',
      4 => 'Apo',
      5 => 'Mei',
      6 => 'Jun',
      7 => 'Jul',
      8 => 'Ago',
      9 => 'Set',
      10 => 'Okt',
      11 => 'Nof',
      12 => 'Dis',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Sontaga',
      1 => 'Mosupalogo',
      2 => 'Labobedi',
      3 => 'Laboraro',
      4 => 'Labone',
      5 => 'Labohlano',
      6 => 'Mokibelo',
    ),
    'abbreviated' => 
    array (
      0 => 'Son',
      1 => 'Mos',
      2 => 'Bed',
      3 => 'Rar',
      4 => 'Ne',
      5 => 'Hla',
      6 => 'Mok',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'T',
      3 => 'W',
      4 => 'T',
      5 => 'F',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'y MMMM d, EEEE',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'y-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'ltr',
  'pluralRules' => 
  array (
    0 => 'n = 0..1 @integer 0, 1 @decimal 0.0, 1.0, 0.00, 1.00, 0.000, 1.000, 0.0000, 1.0000',
    1 => ' @integer 2~17, 100, 1000, 10000, 100000, 1000000, … @decimal 0.1~0.9, 1.1~1.7, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …',
    2 => 'true',
  ),
  'languages' => 
  array (
    'nso' => 'Sesotho sa Leboa',
  ),
);
