<?php
/**
 * Locale data for 'om'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.52',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'ETB' => '$',
    'KES' => 'Ksh',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Amajjii',
      2 => 'Guraandhala',
      3 => 'Bitooteessa',
      4 => 'Elba',
      5 => 'Caamsa',
      6 => 'Waxabajjii',
      7 => 'Adooleessa',
      8 => 'Hagayya',
      9 => 'Fuulbana',
      10 => 'Onkololeessa',
      11 => 'Sadaasa',
      12 => 'Muddee',
    ),
    'abbreviated' => 
    array (
      1 => 'Ama',
      2 => 'Gur',
      3 => 'Bit',
      4 => 'Elb',
      5 => 'Cam',
      6 => 'Wax',
      7 => 'Ado',
      8 => 'Hag',
      9 => 'Ful',
      10 => 'Onk',
      11 => 'Sad',
      12 => 'Mud',
    ),
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'J',
      7 => 'J',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Dilbata',
      1 => 'Wiixata',
      2 => 'Qibxata',
      3 => 'Roobii',
      4 => 'Kamiisa',
      5 => 'Jimaata',
      6 => 'Sanbata',
    ),
    'abbreviated' => 
    array (
      0 => 'Dil',
      1 => 'Wix',
      2 => 'Qib',
      3 => 'Rob',
      4 => 'Kam',
      5 => 'Jim',
      6 => 'San',
    ),
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'T',
      3 => 'W',
      4 => 'T',
      5 => 'F',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'KD',
      1 => 'KB',
    ),
    'wide' => 
    array (
      0 => 'KD',
      1 => 'KB',
    ),
    'narrow' => 
    array (
      0 => 'KD',
      1 => 'KB',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, MMMM d, yyyy',
    'long' => 'dd MMMM yyyy',
    'medium' => 'dd-MMM-yyyy',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'WD',
  'pmName' => 'WB',
);
