<?php
/**
 * Locale data for 'or'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.41',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '୦',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##,##0%',
  'currencyFormat' => '¤ #,##,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ଜାନୁଆରୀ',
      2 => 'ଫେବ୍ରୁୟାରୀ',
      3 => 'ମାର୍ଚ୍ଚ',
      4 => 'ଅପ୍ରେଲ',
      5 => 'ମେ',
      6 => 'ଜୁନ',
      7 => 'ଜୁଲାଇ',
      8 => 'ଅଗଷ୍ଟ',
      9 => 'ସେପ୍ଟେମ୍ବର',
      10 => 'ଅକ୍ଟୋବର',
      11 => 'ନଭେମ୍ବର',
      12 => 'ଡିସେମ୍ବର',
    ),
    'abbreviated' => 
    array (
      1 => 'ଜାନୁଆରୀ',
      2 => 'ଫେବ୍ରୁୟାରୀ',
      3 => 'ମାର୍ଚ୍ଚ',
      4 => 'ଅପ୍ରେଲ',
      5 => 'ମେ',
      6 => 'ଜୁନ',
      7 => 'ଜୁଲାଇ',
      8 => 'ଅଗଷ୍ଟ',
      9 => 'ସେପ୍ଟେମ୍ବର',
      10 => 'ଅକ୍ଟୋବର',
      11 => 'ନଭେମ୍ବର',
      12 => 'ଡିସେମ୍ବର',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ରବିବାର',
      1 => 'ସୋମବାର',
      2 => 'ମଙ୍ଗଳବାର',
      3 => 'ବୁଧବାର',
      4 => 'ଗୁରୁବାର',
      5 => 'ଶୁକ୍ରବାର',
      6 => 'ଶନିବାର',
    ),
    'abbreviated' => 
    array (
      0 => 'ରବି',
      1 => 'ସୋମ',
      2 => 'ମଙ୍ଗଳ',
      3 => 'ବୁଧ',
      4 => 'ଗୁରୁ',
      5 => 'ଶୁକ୍ର',
      6 => 'ଶନି',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'MMMM d,EEEE, yyyy',
    'long' => 'MMMM d, yyyy',
    'medium' => 'dd-MM-yyyy',
    'short' => 'dd-MM-yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
