<?php
/**
 * Locale data for 'pa'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.61',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '੦',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##,##0%',
  'currencyFormat' => '¤ #,##,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => 'ਰੁ.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'XXX' => 'ਅਣਜਾਣ',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ਜਨਵਰੀ',
      2 => 'ਫ਼ਰਵਰੀ',
      3 => 'ਮਾਰਚ',
      4 => 'ਅਪ੍ਰੈਲ',
      5 => 'ਮਈ',
      6 => 'ਜੂਨ',
      7 => 'ਜੁਲਾਈ',
      8 => 'ਅਗਸਤ',
      9 => 'ਸਤੰਬਰ',
      10 => 'ਅਕਤੂਬਰ',
      11 => 'ਨਵੰਬਰ',
      12 => 'ਦਸੰਬਰ',
    ),
    'abbreviated' => 
    array (
      1 => 'ਜਨਵਰੀ',
      2 => 'ਫ਼ਰਵਰੀ',
      3 => 'ਮਾਰਚ',
      4 => 'ਅਪ੍ਰੈਲ',
      5 => 'ਮਈ',
      6 => 'ਜੂਨ',
      7 => 'ਜੁਲਾਈ',
      8 => 'ਅਗਸਤ',
      9 => 'ਸਤੰਬਰ',
      10 => 'ਅਕਤੂਬਰ',
      11 => 'ਨਵੰਬਰ',
      12 => 'ਦਸੰਬਰ',
    ),
    'narrow' => 
    array (
      1 => 'ਜ',
      2 => 'ਫ',
      3 => 'ਮਾ',
      4 => 'ਅ',
      5 => 'ਮ',
      6 => 'ਜੂ',
      7 => 'ਜੁ',
      8 => 'ਅ',
      9 => 'ਸ',
      10 => 'ਅ',
      11 => 'ਨ',
      12 => 'ਦ',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ਐਤਵਾਰ',
      1 => 'ਸੋਮਵਾਰ',
      2 => 'ਮੰਗਲਵਾਰ',
      3 => 'ਬੁਧਵਾਰ',
      4 => 'ਵੀਰਵਾਰ',
      5 => 'ਸ਼ੁੱਕਰਵਾਰ',
      6 => 'ਸ਼ਨੀਚਰਵਾਰ',
    ),
    'abbreviated' => 
    array (
      0 => 'ਐਤ.',
      1 => 'ਸੋਮ.',
      2 => 'ਮੰਗਲ.',
      3 => 'ਬੁਧ.',
      4 => 'ਵੀਰ.',
      5 => 'ਸ਼ੁਕਰ.',
      6 => 'ਸ਼ਨੀ.',
    ),
    'narrow' => 
    array (
      0 => 'ਐ',
      1 => 'ਸੋ',
      2 => 'ਮੰ',
      3 => 'ਬੁੱ',
      4 => 'ਵੀ',
      5 => 'ਸ਼ੁੱ',
      6 => 'ਸ਼',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'ਈਸਾਪੂਰਵ',
      1 => 'ਸੰਨ',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, dd MMMM yyyy',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'dd/MM/yyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'ਸਵੇਰੇ',
  'pmName' => 'ਸ਼ਾਮ',
);
