<?php
/**
 * Locale data for 'ps_AF'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.45',
  'numberSymbols' => 
  array (
    'decimal' => '٫',
    'group' => '٬',
    'list' => ';',
    'percentSign' => '٪',
    'nativeZeroDigit' => '۰',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '−',
    'exponential' => '×۱۰^',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'AFN' => '؋',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'جنوري',
      2 => 'فبروري',
      3 => 'مارچ',
      4 => 'اپریل',
      5 => 'می',
      6 => 'جون',
      7 => 'جولای',
      8 => 'اګست',
      9 => 'سپتمبر',
      10 => 'اکتوبر',
      11 => 'نومبر',
      12 => 'دسمبر',
    ),
    'abbreviated' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => 'مـی',
      6 => 'جون',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'یکشنبه',
      1 => 'دوشنبه',
      2 => 'سه‌شنبه',
      3 => 'چهارشنبه',
      4 => 'پنجشنبه',
      5 => 'جمعه',
      6 => 'شنبه',
    ),
    'abbreviated' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ق.م.',
      1 => 'م.',
    ),
    'wide' => 
    array (
      0 => 'ق.م.',
      1 => 'م.',
    ),
    'narrow' => 
    array (
      0 => 'ق.م.',
      1 => 'م.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE د yyyy د MMMM d',
    'long' => 'د yyyy د MMMM d',
    'medium' => 'd MMM yyyy',
    'short' => 'yyyy/M/d',
  ),
  'timeFormats' => 
  array (
    'full' => 'H:mm:ss (v)',
    'long' => 'H:mm:ss (z)',
    'medium' => 'H:mm:ss',
    'short' => 'H:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'غ.م.',
  'pmName' => 'غ.و.',
);
