<?php
/**
 * Locale data for 'root'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '9737',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'superscriptingExponent' => '×',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'ARS' => '$',
    'AUD' => 'A$',
    'BBD' => '$',
    'BDT' => '৳',
    'BMD' => '$',
    'BND' => '$',
    'BRL' => 'R$',
    'BSD' => '$',
    'BYR' => 'р.',
    'BZD' => '$',
    'CAD' => 'CA$',
    'CLP' => '$',
    'CNY' => 'CN¥',
    'COP' => '$',
    'CRC' => '₡',
    'CUP' => '$',
    'DOP' => '$',
    'ESP' => '₧',
    'EUR' => '€',
    'FJD' => '$',
    'GBP' => '£',
    'GHS' => '₵',
    'GIP' => '£',
    'GYD' => '$',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JMD' => '$',
    'JPY' => 'JP¥',
    'KHR' => '៛',
    'KRW' => '₩',
    'KYD' => '$',
    'KZT' => '₸',
    'LAK' => '₭',
    'LRD' => '$',
    'MNT' => '₮',
    'MXN' => 'MX$',
    'NAD' => '$',
    'NGN' => '₦',
    'NZD' => 'NZ$',
    'PHP' => '₱',
    'PYG' => '₲',
    'RUR' => 'р.',
    'SBD' => '$',
    'SGD' => '$',
    'SRD' => '$',
    'SSP' => '£',
    'THB' => '฿',
    'TRY' => '₺',
    'TTD' => '$',
    'TWD' => 'NT$',
    'UAH' => '₴',
    'USD' => 'US$',
    'UYU' => '$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'M01',
      2 => 'M02',
      3 => 'M03',
      4 => 'M04',
      5 => 'M05',
      6 => 'M06',
      7 => 'M07',
      8 => 'M08',
      9 => 'M09',
      10 => 'M10',
      11 => 'M11',
      12 => 'M12',
    ),
    'abbreviated' => 
    array (
      1 => 'M01',
      2 => 'M02',
      3 => 'M03',
      4 => 'M04',
      5 => 'M05',
      6 => 'M06',
      7 => 'M07',
      8 => 'M08',
      9 => 'M09',
      10 => 'M10',
      11 => 'M11',
      12 => 'M12',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Sun',
      1 => 'Mon',
      2 => 'Tue',
      3 => 'Wed',
      4 => 'Thu',
      5 => 'Fri',
      6 => 'Sat',
    ),
    'abbreviated' => 
    array (
      0 => 'Sun',
      1 => 'Mon',
      2 => 'Tue',
      3 => 'Wed',
      4 => 'Thu',
      5 => 'Fri',
      6 => 'Sat',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'T',
      3 => 'W',
      4 => 'T',
      5 => 'F',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'y MMMM d, EEEE',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'y-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'ltr',
  'pluralRules' => 
  array (
    0 => ' @integer 0~15, 100, 1000, 10000, 100000, 1000000, … @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …',
    1 => 'true',
  ),
);
