<?php
/**
 * Locale data for 'rw'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.20',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'RWF' => 'F',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Mutarama',
      2 => 'Gashyantare',
      3 => 'Werurwe',
      4 => 'Mata',
      5 => 'Gicuransi',
      6 => 'Kamena',
      7 => 'Nyakanga',
      8 => 'Kanama',
      9 => 'Nzeli',
      10 => 'Ukwakira',
      11 => 'Ugushyingo',
      12 => 'Ukuboza',
    ),
    'abbreviated' => 
    array (
      1 => 'mut.',
      2 => 'gas.',
      3 => 'wer.',
      4 => 'mat.',
      5 => 'gic.',
      6 => 'kam.',
      7 => 'nya.',
      8 => 'kan.',
      9 => 'nze.',
      10 => 'ukw.',
      11 => 'ugu.',
      12 => 'uku.',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Ku cyumweru',
      1 => 'Kuwa mbere',
      2 => 'Kuwa kabiri',
      3 => 'Kuwa gatatu',
      4 => 'Kuwa kane',
      5 => 'Kuwa gatanu',
      6 => 'Kuwa gatandatu',
    ),
    'abbreviated' => 
    array (
      0 => 'cyu.',
      1 => 'mbe.',
      2 => 'kab.',
      3 => 'gtu.',
      4 => 'kan.',
      5 => 'gnu.',
      6 => 'gnd.',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
