<?php
/**
 * Locale data for 'sid_ET'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.34',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'ETB' => '$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'January',
      2 => 'February',
      3 => 'March',
      4 => 'April',
      5 => 'May',
      6 => 'June',
      7 => 'July',
      8 => 'August',
      9 => 'September',
      10 => 'October',
      11 => 'November',
      12 => 'December',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Feb',
      3 => 'Mar',
      4 => 'Apr',
      5 => 'May',
      6 => 'Jun',
      7 => 'Jul',
      8 => 'Aug',
      9 => 'Sep',
      10 => 'Oct',
      11 => 'Nov',
      12 => 'Dec',
    ),
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'J',
      7 => 'J',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Sambata',
      1 => 'Sanyo',
      2 => 'Maakisanyo',
      3 => 'Roowe',
      4 => 'Hamuse',
      5 => 'Arbe',
      6 => 'Qidaame',
    ),
    'abbreviated' => 
    array (
      0 => 'Sam',
      1 => 'San',
      2 => 'Mak',
      3 => 'Row',
      4 => 'Ham',
      5 => 'Arb',
      6 => 'Qid',
    ),
    'narrow' => 
    array (
      0 => 'S',
      1 => 'S',
      2 => 'M',
      3 => 'R',
      4 => 'H',
      5 => 'A',
      6 => 'Q',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'YIA',
      1 => 'YIG',
    ),
    'wide' => 
    array (
      0 => 'YIA',
      1 => 'YIG',
    ),
    'narrow' => 
    array (
      0 => 'YIA',
      1 => 'YIG',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, MMMM dd, yyyy',
    'long' => 'dd MMMM yyyy',
    'medium' => 'dd-MMM-yyyy',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'soodo',
  'pmName' => 'hawwaro',
);
