<?php
/**
 * Locale data for 'so_KE'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.46',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'KES' => 'Ksh',
    'SOS' => 'SOS',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Bisha Koobaad',
      2 => 'Bisha Labaad',
      3 => 'Bisha Saddexaad',
      4 => 'Bisha Afraad',
      5 => 'Bisha Shanaad',
      6 => 'Bisha Lixaad',
      7 => 'Bisha Todobaad',
      8 => 'Bisha Sideedaad',
      9 => 'Bisha Sagaalaad',
      10 => 'Bisha Tobnaad',
      11 => 'Bisha Kow iyo Tobnaad',
      12 => 'Bisha Laba iyo Tobnaad',
    ),
    'abbreviated' => 
    array (
      1 => 'Kob',
      2 => 'Lab',
      3 => 'Sad',
      4 => 'Afr',
      5 => 'Sha',
      6 => 'Lix',
      7 => 'Tod',
      8 => 'Sid',
      9 => 'Sag',
      10 => 'Tob',
      11 => 'KIT',
      12 => 'LIT',
    ),
    'narrow' => 
    array (
      1 => 'K',
      2 => 'L',
      3 => 'S',
      4 => 'A',
      5 => 'S',
      6 => 'L',
      7 => 'T',
      8 => 'S',
      9 => 'S',
      10 => 'T',
      11 => 'K',
      12 => 'L',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Axad',
      1 => 'Isniin',
      2 => 'Salaaso',
      3 => 'Arbaco',
      4 => 'Khamiis',
      5 => 'Jimco',
      6 => 'Sabti',
    ),
    'abbreviated' => 
    array (
      0 => 'Axa',
      1 => 'Isn',
      2 => 'Sal',
      3 => 'Arb',
      4 => 'Kha',
      5 => 'Jim',
      6 => 'Sab',
    ),
    'narrow' => 
    array (
      0 => 'A',
      1 => 'I',
      2 => 'S',
      3 => 'A',
      4 => 'K',
      5 => 'J',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'Ciise ka hor',
      1 => 'Ciise ka dib',
    ),
    'wide' => 
    array (
      0 => 'Ciise ka hor',
      1 => 'Ciise ka dib',
    ),
    'narrow' => 
    array (
      0 => 'Ciise ka hor',
      1 => 'Ciise ka dib',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, MMMM dd, yyyy',
    'long' => 'dd MMMM yyyy',
    'medium' => 'dd-MMM-yyyy',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'sn',
  'pmName' => 'gn',
);
