<?php
/**
 * Locale data for 'sq'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.69',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'ALL' => 'Lek',
    'XXX' => 'XXX',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'janar',
      2 => 'shkurt',
      3 => 'mars',
      4 => 'prill',
      5 => 'maj',
      6 => 'qershor',
      7 => 'korrik',
      8 => 'gusht',
      9 => 'shtator',
      10 => 'tetor',
      11 => 'nëntor',
      12 => 'dhjetor',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Shk',
      3 => 'Mar',
      4 => 'Pri',
      5 => 'Maj',
      6 => 'Qer',
      7 => 'Kor',
      8 => 'Gsh',
      9 => 'Sht',
      10 => 'Tet',
      11 => 'Nën',
      12 => 'Dhj',
    ),
    'narrow' => 
    array (
      1 => 'J',
      2 => 'S',
      3 => 'M',
      4 => 'P',
      5 => 'M',
      6 => 'Q',
      7 => 'K',
      8 => 'G',
      9 => 'S',
      10 => 'T',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'e diel',
      1 => 'e hënë',
      2 => 'e martë',
      3 => 'e mërkurë',
      4 => 'e enjte',
      5 => 'e premte',
      6 => 'e shtunë',
    ),
    'abbreviated' => 
    array (
      0 => 'Die',
      1 => 'Hën',
      2 => 'Mar',
      3 => 'Mër',
      4 => 'Enj',
      5 => 'Pre',
      6 => 'Sht',
    ),
    'narrow' => 
    array (
      0 => 'D',
      1 => 'H',
      2 => 'M',
      3 => 'M',
      4 => 'E',
      5 => 'P',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'p.e.r.',
      1 => 'n.e.r.',
    ),
    'wide' => 
    array (
      0 => 'p.e.r.',
      1 => 'n.e.r.',
    ),
    'narrow' => 
    array (
      0 => 'p.e.r.',
      1 => 'n.e.r.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, dd MMMM yyyy',
    'long' => 'dd MMMM yyyy',
    'medium' => 'yyyy-MM-dd',
    'short' => 'yy-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'h.mm.ss.a v',
    'long' => 'h.mm.ss.a z',
    'medium' => 'h:mm:ss.a',
    'short' => 'h.mm.a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'PD',
  'pmName' => 'MD',
);
