<?php
/**
 * Locale data for 'sr_Cyrl_RS'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.7',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'е',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => 'INR',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'AUD' => '$A',
    'BAM' => 'KM',
    'BEF' => 'BF',
    'CAD' => 'Can$',
    'CHF' => 'SwF',
    'CNY' => 'Y',
    'DKK' => 'DKr',
    'IEP' => 'IR£',
    'KWD' => 'KD',
    'NOK' => 'NKr',
    'SEK' => 'SKr',
    'YUN' => 'Дин',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'јануар',
      2 => 'фебруар',
      3 => 'март',
      4 => 'април',
      5 => 'мај',
      6 => 'јун',
      7 => 'јул',
      8 => 'август',
      9 => 'септембар',
      10 => 'октобар',
      11 => 'новембар',
      12 => 'децембар',
    ),
    'abbreviated' => 
    array (
      1 => 'јан',
      2 => 'феб',
      3 => 'мар',
      4 => 'апр',
      5 => 'мај',
      6 => 'јун',
      7 => 'јул',
      8 => 'авг',
      9 => 'сеп',
      10 => 'окт',
      11 => 'нов',
      12 => 'дец',
    ),
    'narrow' => 
    array (
      1 => 'ј',
      2 => 'ф',
      3 => 'м',
      4 => 'а',
      5 => 'м',
      6 => 'ј',
      7 => 'ј',
      8 => 'а',
      9 => 'с',
      10 => 'о',
      11 => 'н',
      12 => 'д',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'недеља',
      1 => 'понедељак',
      2 => 'уторак',
      3 => 'среда',
      4 => 'четвртак',
      5 => 'петак',
      6 => 'субота',
    ),
    'abbreviated' => 
    array (
      0 => 'нед',
      1 => 'пон',
      2 => 'уто',
      3 => 'сре',
      4 => 'чет',
      5 => 'пет',
      6 => 'суб',
    ),
    'narrow' => 
    array (
      0 => 'н',
      1 => 'п',
      2 => 'у',
      3 => 'с',
      4 => 'ч',
      5 => 'п',
      6 => 'с',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'п. н. е.',
      1 => 'н. е',
    ),
    'wide' => 
    array (
      0 => 'Пре нове ере',
      1 => 'Нове ере',
    ),
    'narrow' => 
    array (
      0 => 'п.н.е.',
      1 => 'н.е.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, dd. MMMM yyyy.',
    'long' => 'dd. MMMM yyyy.',
    'medium' => 'dd.MM.yyyy.',
    'short' => 'd.M.yy.',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH.mm.ss v',
    'long' => 'HH.mm.ss z',
    'medium' => 'HH.mm.ss',
    'short' => 'HH.mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'преподне',
  'pmName' => 'поподне',
);
