<?php
/**
 * Locale data for 'sr_Latn_ME'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.18',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'е',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => 'INR',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'AUD' => '$A',
    'BAM' => 'KM',
    'BEF' => 'BF',
    'CAD' => 'Can$',
    'CHF' => 'SwF',
    'CNY' => 'U',
    'DKK' => 'DKr',
    'IEP' => 'IR£',
    'KWD' => 'KD',
    'NOK' => 'NKr',
    'SEK' => 'SKr',
    'YUN' => 'Din',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'januar',
      2 => 'februar',
      3 => 'mart',
      4 => 'april',
      5 => 'maj',
      6 => 'jun',
      7 => 'jul',
      8 => 'avgust',
      9 => 'septembar',
      10 => 'oktobar',
      11 => 'novembar',
      12 => 'decembar',
    ),
    'abbreviated' => 
    array (
      1 => 'jan',
      2 => 'feb',
      3 => 'mar',
      4 => 'apr',
      5 => 'maj',
      6 => 'jun',
      7 => 'jul',
      8 => 'avg',
      9 => 'sep',
      10 => 'okt',
      11 => 'nov',
      12 => 'dec',
    ),
    'narrow' => 
    array (
      1 => 'j',
      2 => 'f',
      3 => 'm',
      4 => 'a',
      5 => 'm',
      6 => 'j',
      7 => 'j',
      8 => 'a',
      9 => 's',
      10 => 'o',
      11 => 'n',
      12 => 'd',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'nedelja',
      1 => 'ponedeljak',
      2 => 'utorak',
      3 => 'sreda',
      4 => 'četvrtak',
      5 => 'petak',
      6 => 'subota',
    ),
    'abbreviated' => 
    array (
      0 => 'ned',
      1 => 'pon',
      2 => 'uto',
      3 => 'sre',
      4 => 'čet',
      5 => 'pet',
      6 => 'sub',
    ),
    'narrow' => 
    array (
      0 => 'n',
      1 => 'p',
      2 => 'u',
      3 => 's',
      4 => 'č',
      5 => 'p',
      6 => 's',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'p. n. e.',
      1 => 'n. e',
    ),
    'wide' => 
    array (
      0 => 'Pre nove ere',
      1 => 'Nove ere',
    ),
    'narrow' => 
    array (
      0 => 'p.n.e.',
      1 => 'n. e.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, dd. MMMM yyyy.',
    'long' => 'd.MM.yyyy.',
    'medium' => 'dd.MM.yyyy.',
    'short' => 'd.M.yy.',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH.mm.ss v',
    'long' => 'HH.mm.ss z',
    'medium' => 'HH.mm.ss',
    'short' => 'HH.mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
