<?php
/**
 * Locale data for 'sw'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.64',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'KES' => 'KSh',
    'TZS' => 'TSh',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Januari',
      2 => 'Februari',
      3 => 'Machi',
      4 => 'Aprili',
      5 => 'Mei',
      6 => 'Juni',
      7 => 'Julai',
      8 => 'Agosti',
      9 => 'Septemba',
      10 => 'Oktoba',
      11 => 'Novemba',
      12 => 'Desemba',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Feb',
      3 => 'Mac',
      4 => 'Apr',
      5 => 'Mei',
      6 => 'Jun',
      7 => 'Jul',
      8 => 'Ago',
      9 => 'Sep',
      10 => 'Okt',
      11 => 'Nov',
      12 => 'Des',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Jumapili',
      1 => 'Jumatatu',
      2 => 'Jumanne',
      3 => 'Jumatano',
      4 => 'Alhamisi',
      5 => 'Ijumaa',
      6 => 'Jumamosi',
    ),
    'abbreviated' => 
    array (
      0 => 'Jpi',
      1 => 'Jtt',
      2 => 'Jnn',
      3 => 'Jtn',
      4 => 'Alh',
      5 => 'Iju',
      6 => 'Jmo',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'KK',
      1 => 'BK',
    ),
    'wide' => 
    array (
      0 => 'Kabla ya Kristo',
      1 => 'Baada ya Kristo',
    ),
    'narrow' => 
    array (
      0 => 'KK',
      1 => 'BK',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
