<?php
/**
 * Locale data for 'syr'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.40',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###;#,##0.###-',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00;¤ #,##0.00-',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'SYP' => 'ل.س.‏',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => '܏ܟܢ ܏ܒ',
      2 => 'ܫܒܛ',
      3 => 'ܐܕܪ',
      4 => 'ܢܝܣܢ',
      5 => 'ܐܝܪ',
      6 => 'ܚܙܝܪܢ',
      7 => 'ܬܡܘܙ',
      8 => 'ܐܒ',
      9 => 'ܐܝܠܘܠ',
      10 => '܏ܬܫ ܏ܐ',
      11 => '܏ܬܫ ܏ܒ',
      12 => '܏ܟܢ ܏ܐ',
    ),
    'abbreviated' => 
    array (
      1 => '܏ܟܢ ܏ܒ',
      2 => 'ܫܒܛ',
      3 => 'ܐܕܪ',
      4 => 'ܢܝܣܢ',
      5 => 'ܐܝܪ',
      6 => 'ܚܙܝܪܢ',
      7 => 'ܬܡܘܙ',
      8 => 'ܐܒ',
      9 => 'ܐܝܠܘܠ',
      10 => '܏ܬܫ ܏ܐ',
      11 => '܏ܬܫ ܏ܒ',
      12 => '܏ܟܢ ܏ܐ',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
    'abbreviated' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'dd MMMM, yyyy',
    'long' => 'dd MMMM, yyyy',
    'medium' => 'dd/MM/yyyy',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss',
    'short' => 'h:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
