<?php
/**
 * Locale data for 'ta_IN'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.55',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##,##0%',
  'currencyFormat' => '¤ #,##,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => 'ரூ',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ஜனவரி',
      2 => 'பிப்ரவரி',
      3 => 'மார்ச்',
      4 => 'ஏப்ரல்',
      5 => 'மே',
      6 => 'ஜூன்',
      7 => 'ஜூலை',
      8 => 'ஆகஸ்ட்',
      9 => 'செப்டம்பர்',
      10 => 'அக்டோபர்',
      11 => 'நவம்பர்',
      12 => 'டிசம்பர்',
    ),
    'abbreviated' => 
    array (
      1 => 'ஜன.',
      2 => 'பிப்.',
      3 => 'மார்.',
      4 => 'ஏப்.',
      5 => 'மே',
      6 => 'ஜூன்',
      7 => 'ஜூலை',
      8 => 'ஆக.',
      9 => 'செப்.',
      10 => 'அக்.',
      11 => 'நவ.',
      12 => 'டிச.',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ஞாயிறு',
      1 => 'திங்கள்',
      2 => 'செவ்வாய்',
      3 => 'புதன்',
      4 => 'வியாழன்',
      5 => 'வெள்ளி',
      6 => 'சனி',
    ),
    'abbreviated' => 
    array (
      0 => 'ஞா',
      1 => 'தி',
      2 => 'செ',
      3 => 'பு',
      4 => 'வி',
      5 => 'வெ',
      6 => 'ச',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'கிமு',
      1 => 'கிபி',
    ),
    'wide' => 
    array (
      0 => 'கிறிஸ்துவுக்கு முன்',
      1 => 'அனோ டோமினி',
    ),
    'narrow' => 
    array (
      0 => 'கிமு',
      1 => 'கிபி',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'dd-MM-yyyy',
    'short' => 'd-M-yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'காலை',
  'pmName' => 'மாலை',
);
