<?php
/**
 * Locale data for 'te_IN'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.54',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '౦',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##,##0%',
  'currencyFormat' => '¤ #,##,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'రి$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => 'రూ.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'CNY' => 'యు',
    'RUB' => 'రూబల్',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'జనవరి',
      2 => 'ఫిబ్రవరి',
      3 => 'మార్చి',
      4 => 'ఏప్రిల్',
      5 => 'మే',
      6 => 'జూన్',
      7 => 'జూలై',
      8 => 'ఆగస్టు',
      9 => 'సెప్టెంబర్',
      10 => 'అక్టోబర్',
      11 => 'నవంబర్',
      12 => 'డిసెంబర్',
    ),
    'abbreviated' => 
    array (
      1 => 'జనవరి',
      2 => 'ఫిబ్రవరి',
      3 => 'మార్చి',
      4 => 'ఏప్రిల్',
      5 => 'మే',
      6 => 'జూన్',
      7 => 'జూలై',
      8 => 'ఆగస్టు',
      9 => 'సెప్టెంబర్',
      10 => 'అక్టోబర్',
      11 => 'నవంబర్',
      12 => 'డిసెంబర్',
    ),
    'narrow' => 
    array (
      1 => 'జ',
      2 => 'ఫి',
      3 => 'మ',
      4 => 'ఎ',
      5 => 'మె',
      6 => 'జు',
      7 => 'జు',
      8 => 'ఆ',
      9 => 'సె',
      10 => 'అ',
      11 => 'న',
      12 => 'డి',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ఆదివారం',
      1 => 'సోమవారం',
      2 => 'మంగళవారం',
      3 => 'బుధవారం',
      4 => 'గురువారం',
      5 => 'శుక్రవారం',
      6 => 'శనివారం',
    ),
    'abbreviated' => 
    array (
      0 => 'ఆది',
      1 => 'సోమ',
      2 => 'మంగళ',
      3 => 'బుధ',
      4 => 'గురు',
      5 => 'శుక్ర',
      6 => 'శని',
    ),
    'narrow' => 
    array (
      0 => 'ఆ',
      1 => '2',
      2 => 'సొ',
      3 => 'భు',
      4 => 'గు',
      5 => 'శు',
      6 => 'శ',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'ఈసాపూర్వ.',
      1 => 'సన్.',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'dd-MM-yyyy',
    'short' => 'dd-MM-yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'పూర్వాహ్నం',
  'pmName' => 'అపరాహ్నం',
);
