<?php
/**
 * Locale data for 'tg_TJ'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.14',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'TJS' => 'сом',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Январ',
      2 => 'Феврал',
      3 => 'Март',
      4 => 'Апрел',
      5 => 'Май',
      6 => 'Июн',
      7 => 'Июл',
      8 => 'Август',
      9 => 'Сентябр',
      10 => 'Октябр',
      11 => 'Ноябр',
      12 => 'Декабр',
    ),
    'abbreviated' => 
    array (
      1 => 'Янв',
      2 => 'Фев',
      3 => 'Мар',
      4 => 'Апр',
      5 => 'Май',
      6 => 'Июн',
      7 => 'Июл',
      8 => 'Авг',
      9 => 'Сен',
      10 => 'Окт',
      11 => 'Ноя',
      12 => 'Дек',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Якшанбе',
      1 => 'Душанбе',
      2 => 'Сешанбе',
      3 => 'Чоршанбе',
      4 => 'Панҷшанбе',
      5 => 'Ҷумъа',
      6 => 'Шанбе',
    ),
    'abbreviated' => 
    array (
      0 => 'Яшб',
      1 => 'Дшб',
      2 => 'Сшб',
      3 => 'Чшб',
      4 => 'Пшб',
      5 => 'Ҷмъ',
      6 => 'Шнб',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ПеМ',
      1 => 'ПаМ',
    ),
    'wide' => 
    array (
      0 => 'Пеш аз милод',
      1 => 'ПаМ',
    ),
    'narrow' => 
    array (
      0 => 'ПеМ',
      1 => 'ПаМ',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'пе. чо.',
  'pmName' => 'па. чо.',
);
