<?php
/**
 * Locale data for 'th_TH'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.47',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00;¤-#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => '\\u00A3',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => '\\u00A5',
    'USD' => 'US$',
    'ARS' => 'Arg$',
    'AUD' => '$A',
    'CAD' => 'Can$',
    'CLP' => 'Ch$',
    'CNY' => '￥',
    'FJD' => 'F$',
    'HKD' => 'HK$',
    'IDR' => 'Rp',
    'IEP' => 'IR\\u00A3',
    'MXN' => 'MEX$',
    'MYR' => 'RM',
    'NZD' => '$NZ',
    'PKR' => 'Pra',
    'RUB' => 'RUB',
    'SGD' => 'S$',
    'THB' => '฿',
    'XXX' => 'XXX',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'มกราคม',
      2 => 'กุมภาพันธ์',
      3 => 'มีนาคม',
      4 => 'เมษายน',
      5 => 'พฤษภาคม',
      6 => 'มิถุนายน',
      7 => 'กรกฎาคม',
      8 => 'สิงหาคม',
      9 => 'กันยายน',
      10 => 'ตุลาคม',
      11 => 'พฤศจิกายน',
      12 => 'ธันวาคม',
    ),
    'abbreviated' => 
    array (
      1 => 'ม.ค.',
      2 => 'ก.พ.',
      3 => 'มี.ค.',
      4 => 'เม.ย.',
      5 => 'พ.ค.',
      6 => 'มิ.ย.',
      7 => 'ก.ค.',
      8 => 'ส.ค.',
      9 => 'ก.ย.',
      10 => 'ต.ค.',
      11 => 'พ.ย.',
      12 => 'ธ.ค.',
    ),
    'narrow' => 
    array (
      1 => 'ม.ค.',
      2 => 'ก.พ.',
      3 => 'มี.ค.',
      4 => 'เม.ย.',
      5 => 'พ.ค.',
      6 => 'มิ.ย.',
      7 => 'ก.ค.',
      8 => 'ส.ค.',
      9 => 'ก.ย.',
      10 => 'ต.ค.',
      11 => 'พ.ย.',
      12 => 'ธ.ค.',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'วันอาทิตย์',
      1 => 'วันจันทร์',
      2 => 'วันอังคาร',
      3 => 'วันพุธ',
      4 => 'วันพฤหัสบดี',
      5 => 'วันศุกร์',
      6 => 'วันเสาร์',
    ),
    'abbreviated' => 
    array (
      0 => 'อา.',
      1 => 'จ.',
      2 => 'อ.',
      3 => 'พ.',
      4 => 'พฤ.',
      5 => 'ศ.',
      6 => 'ส.',
    ),
    'narrow' => 
    array (
      0 => 'อา.',
      1 => 'จ',
      2 => 'อ',
      3 => 'พ',
      4 => 'พฤ',
      5 => 'ศ',
      6 => 'ส',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ปีก่อน ค.ศ.',
      1 => 'ค.ศ.',
    ),
    'wide' => 
    array (
      0 => 'ปีก่อนคริสต์ราช',
      1 => 'คริสต์ศักราช',
    ),
    'narrow' => 
    array (
      0 => 'ปีก่อน ค.ศ.',
      1 => 'ค.ศ.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEEที่ d MMMM G yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'd MMM yyyy',
    'short' => 'd/M/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'H นาฬิกา m นาที ss วินาที v',
    'long' => 'H นาฬิกา m นาที ss วินาที z',
    'medium' => 'H:mm:ss',
    'short' => 'H:mm',
  ),
  'dateTimeFormat' => '{1}, {0}',
  'amName' => 'ก่อนเที่ยง',
  'pmName' => 'หลังเที่ยง',
);
