<?php
/**
 * Locale data for 'ti'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.59',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'USD',
    'CNY' => 'Y',
    'ETB' => '$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ጃንዩወሪ',
      2 => 'ፌብሩወሪ',
      3 => 'ማርች',
      4 => 'ኤፕረል',
      5 => 'ሜይ',
      6 => 'ጁን',
      7 => 'ጁላይ',
      8 => 'ኦገስት',
      9 => 'ሴፕቴምበር',
      10 => 'ኦክተውበር',
      11 => 'ኖቬምበር',
      12 => 'ዲሴምበር',
    ),
    'abbreviated' => 
    array (
      1 => 'ጃንዩ',
      2 => 'ፌብሩ',
      3 => 'ማርች',
      4 => 'ኤፕረ',
      5 => 'ሜይ',
      6 => 'ጁን',
      7 => 'ጁላይ',
      8 => 'ኦገስ',
      9 => 'ሴፕቴ',
      10 => 'ኦክተ',
      11 => 'ኖቬም',
      12 => 'ዲሴም',
    ),
    'narrow' => 
    array (
      1 => 'ጃ',
      2 => 'ፌ',
      3 => 'ማ',
      4 => 'ኤ',
      5 => 'ሜ',
      6 => 'ጁ',
      7 => 'ጁ',
      8 => 'ኦ',
      9 => 'ሴ',
      10 => 'ኦ',
      11 => 'ኖ',
      12 => 'ዲ',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ሰንበት',
      1 => 'ሰኑይ',
      2 => 'ሠሉስ',
      3 => 'ረቡዕ',
      4 => 'ኃሙስ',
      5 => 'ዓርቢ',
      6 => 'ቀዳም',
    ),
    'abbreviated' => 
    array (
      0 => 'ሰንበ',
      1 => 'ሰኑይ',
      2 => 'ሠሉስ',
      3 => 'ረቡዕ',
      4 => 'ኃሙስ',
      5 => 'ዓርቢ',
      6 => 'ቀዳም',
    ),
    'narrow' => 
    array (
      0 => 'ሰ',
      1 => 'ሰ',
      2 => 'ሠ',
      3 => 'ረ',
      4 => 'ኃ',
      5 => 'ዓ',
      6 => 'ቀ',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ዓ/ዓ',
      1 => 'ዓ/ም',
    ),
    'wide' => 
    array (
      0 => 'ዓ/ዓ',
      1 => 'ዓ/ም',
    ),
    'narrow' => 
    array (
      0 => 'ዓ/ዓ',
      1 => 'ዓ/ም',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE፣ dd MMMM መዓልቲ yyyy G',
    'long' => 'dd MMMM yyyy',
    'medium' => 'dd-MMM-yyyy',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'ንጉሆ ሰዓተ',
  'pmName' => 'ድሕር ሰዓት',
);
