<?php
/**
 * Locale data for 'to_TO'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.5',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Sānuali',
      2 => 'Fēpueli',
      3 => 'Maʻasi',
      4 => 'ʻEpeleli',
      5 => 'Mē',
      6 => 'Sune',
      7 => 'Siulai',
      8 => 'ʻAokosi',
      9 => 'Sēpitema',
      10 => 'ʻOkatopa',
      11 => 'Nōvema',
      12 => 'Tisema',
    ),
    'abbreviated' => 
    array (
      1 => 'Sān',
      2 => 'Fēp',
      3 => 'Maʻa',
      4 => 'ʻEpe',
      5 => 'Mē',
      6 => 'Sun',
      7 => 'Siu',
      8 => 'ʻAok',
      9 => 'Sēp',
      10 => 'ʻOka',
      11 => 'Nōv',
      12 => 'Tis',
    ),
    'narrow' => 
    array (
      1 => 'S',
      2 => 'F',
      3 => 'M',
      4 => 'E',
      5 => 'M',
      6 => 'S',
      7 => 'S',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'T',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Sāpate',
      1 => 'Mōnite',
      2 => 'Tusite',
      3 => 'Pulelulu',
      4 => 'Tuʻapulelulu',
      5 => 'Falaite',
      6 => 'Tokonaki',
    ),
    'abbreviated' => 
    array (
      0 => 'Sāp',
      1 => 'Mōn',
      2 => 'Tus',
      3 => 'Pul',
      4 => 'Tuʻa',
      5 => 'Fal',
      6 => 'Tok',
    ),
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'T',
      3 => 'P',
      4 => 'T',
      5 => 'F',
      6 => 'T',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'KM',
      1 => 'TS',
    ),
    'wide' => 
    array (
      0 => 'ki muʻa',
      1 => 'taʻu ʻo Sīsū',
    ),
    'narrow' => 
    array (
      0 => 'KāMā',
      1 => 'TāSā',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'd MMM yyyy',
    'short' => 'dd-MM-yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'HH',
  'pmName' => 'EA',
);
