<?php
/**
 * Locale data for 'trv'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.6',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Kingal idas',
      2 => 'Dha idas',
      3 => 'Tru idas',
      4 => 'Spat idas',
      5 => 'Rima idas',
      6 => 'Mataru idas',
      7 => 'Empitu idas',
      8 => 'Maspat idas',
      9 => 'Mngari idas',
      10 => 'Maxal idas',
      11 => 'Maxal kingal idas',
      12 => 'Maxal dha idas',
    ),
    'abbreviated' => 
    array (
      1 => 'Kii',
      2 => 'Dhi',
      3 => 'Tri',
      4 => 'Spi',
      5 => 'Rii',
      6 => 'Mti',
      7 => 'Emi',
      8 => 'Mai',
      9 => 'Mni',
      10 => 'Mxi',
      11 => 'Mxk',
      12 => 'Mxd',
    ),
    'narrow' => 
    array (
      1 => 'K',
      2 => 'D',
      3 => 'T',
      4 => 'S',
      5 => 'R',
      6 => 'M',
      7 => 'E',
      8 => 'P',
      9 => 'A',
      10 => 'M',
      11 => 'K',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Jiyax sngayan',
      1 => 'tgKingal jiyax iyax sngayan',
      2 => 'tgDha jiyax iyax sngayan',
      3 => 'tgTru jiyax iyax sngayan',
      4 => 'tgSpac jiyax iyax sngayan',
      5 => 'tgRima jiyax iyax sngayan',
      6 => 'tgMataru jiyax iyax sngayan',
    ),
    'abbreviated' => 
    array (
      0 => 'Emp',
      1 => 'Kin',
      2 => 'Dha',
      3 => 'Tru',
      4 => 'Spa',
      5 => 'Rim',
      6 => 'Mat',
    ),
    'narrow' => 
    array (
      0 => 'E',
      1 => 'K',
      2 => 'D',
      3 => 'T',
      4 => 'S',
      5 => 'R',
      6 => 'M',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BRY',
      1 => 'BUY',
    ),
    'wide' => 
    array (
      0 => 'Brah jikan Yisu Thulang',
      1 => 'Bukuy jikan Yisu Thulang',
    ),
    'narrow' => 
    array (
      0 => 'BRY',
      1 => 'BUY',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yyyy-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'Brax kndaax',
  'pmName' => 'Baubau kndaax',
);
