<?php
/**
 * Locale data for 'ts'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.20',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'ZAR' => 'R',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Sunguti',
      2 => 'Nyenyenyani',
      3 => 'Nyenyankulu',
      4 => 'Dzivamisoko',
      5 => 'Mudyaxihi',
      6 => 'Khotavuxika',
      7 => 'Mawuwani',
      8 => 'Mhawuri',
      9 => 'Ndzhati',
      10 => 'Nhlangula',
      11 => 'Hukuri',
      12 => 'N\'wendzamhala',
    ),
    'abbreviated' => 
    array (
      1 => 'Sun',
      2 => 'Yan',
      3 => 'Kul',
      4 => 'Dzi',
      5 => 'Mud',
      6 => 'Kho',
      7 => 'Maw',
      8 => 'Mha',
      9 => 'Ndz',
      10 => 'Nhl',
      11 => 'Huk',
      12 => 'N\'w',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Sonto',
      1 => 'Musumbhunuku',
      2 => 'Ravumbirhi',
      3 => 'Ravunharhu',
      4 => 'Ravumune',
      5 => 'Ravuntlhanu',
      6 => 'Mugqivela',
    ),
    'abbreviated' => 
    array (
      0 => 'Son',
      1 => 'Mus',
      2 => 'Bir',
      3 => 'Har',
      4 => 'Ne',
      5 => 'Tlh',
      6 => 'Mug',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BC',
      1 => 'AD',
    ),
    'wide' => 
    array (
      0 => 'BC',
      1 => 'AD',
    ),
    'narrow' => 
    array (
      0 => 'BC',
      1 => 'AD',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
