<?php
/**
 * Locale data for 'ur_PK'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.33',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'ق',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'یہ عدد نہیں',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'ڈالر',
    'PKR' => 'روپے',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'جنوری',
      2 => 'فروری',
      3 => 'مار چ',
      4 => 'اپريل',
      5 => 'مئ',
      6 => 'جون',
      7 => 'جولائ',
      8 => 'اگست',
      9 => 'ستمبر',
      10 => 'اکتوبر',
      11 => 'نومبر',
      12 => 'دسمبر',
    ),
    'abbreviated' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
    'narrow' => 
    array (
      1 => 'ج',
      2 => 'ف',
      3 => 'م',
      4 => 'ا',
      5 => 'م',
      6 => 'ج',
      7 => 'ج',
      8 => 'ا',
      9 => 'س',
      10 => 'ا',
      11 => 'ن',
      12 => 'د',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'اتوار',
      1 => 'پير',
      2 => 'منگل',
      3 => 'بده',
      4 => 'جمعرات',
      5 => 'جمعہ',
      6 => 'ہفتہ',
    ),
    'abbreviated' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ق م',
      1 => 'عيسوی سن',
    ),
    'wide' => 
    array (
      0 => 'قبل مسيح',
      1 => 'عيسوی سن',
    ),
    'narrow' => 
    array (
      0 => 'ق م',
      1 => 'عيسوی سن',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, d, MMMM yyyy',
    'long' => 'd, MMMM yyyy',
    'medium' => 'd, MMM yyyy',
    'short' => 'd/M/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'قبل دوپہر',
  'pmName' => 'بعد دوپہر',
);
