<?php
/**
 * Locale data for 'uz_Arab_AF'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.20',
  'numberSymbols' => 
  array (
    'decimal' => '٫',
    'group' => '٬',
    'list' => ';',
    'percentSign' => '٪',
    'nativeZeroDigit' => '۰',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '−',
    'exponential' => '×۱۰^',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'UZS' => 'сўм',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'جنوری',
      2 => 'فبروری',
      3 => 'مارچ',
      4 => 'اپریل',
      5 => 'می',
      6 => 'جون',
      7 => 'جولای',
      8 => 'اگست',
      9 => 'سپتمبر',
      10 => 'اکتوبر',
      11 => 'نومبر',
      12 => 'دسمبر',
    ),
    'abbreviated' => 
    array (
      1 => 'جنو',
      2 => 'فبر',
      3 => 'مار',
      4 => 'اپر',
      5 => 'مـی',
      6 => 'جون',
      7 => 'جول',
      8 => 'اگس',
      9 => 'سپت',
      10 => 'اکت',
      11 => 'نوم',
      12 => 'دسم',
    ),
    'narrow' => 
    array (
      1 => 'Я',
      2 => 'Ф',
      3 => 'М',
      4 => 'А',
      5 => 'М',
      6 => 'И',
      7 => 'И',
      8 => 'А',
      9 => 'С',
      10 => 'О',
      11 => 'Н',
      12 => 'Д',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'یکشنبه',
      1 => 'دوشنبه',
      2 => 'سه‌شنبه',
      3 => 'چهارشنبه',
      4 => 'پنجشنبه',
      5 => 'جمعه',
      6 => 'شنبه',
    ),
    'abbreviated' => 
    array (
      0 => 'ی.',
      1 => 'د.',
      2 => 'س.',
      3 => 'چ.',
      4 => 'پ.',
      5 => 'ج.',
      6 => 'ش.',
    ),
    'narrow' => 
    array (
      0 => 'Я',
      1 => 'Д',
      2 => 'С',
      3 => 'Ч',
      4 => 'П',
      5 => 'Ж',
      6 => 'Ш',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ق.م.',
      1 => 'م.',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'yyyy نچی ییل d نچی MMMM EEEE کونی',
    'long' => 'd نچی MMMM yyyy',
    'medium' => 'd MMM yyyy',
    'short' => 'yyyy/M/d',
  ),
  'timeFormats' => 
  array (
    'full' => 'H:mm:ss (v)',
    'long' => 'H:mm:ss (z)',
    'medium' => 'H:mm:ss',
    'short' => 'H:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
