<?php
/**
 * Locale data for 'uz_Cyrl'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.20',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'UZS' => 'сўм',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Муҳаррам',
      2 => 'Сафар',
      3 => 'Рабиул-аввал',
      4 => 'Рабиул-охир',
      5 => 'Жумодиул-уло',
      6 => 'Жумодиул-ухро',
      7 => 'Ражаб',
      8 => 'Шаъбон',
      9 => 'Рамазон',
      10 => 'Шаввол',
      11 => 'Зил-қаъда',
      12 => 'Зил-ҳижжа',
    ),
    'abbreviated' => 
    array (
      1 => 'Янв',
      2 => 'Фев',
      3 => 'Мар',
      4 => 'Апр',
      5 => 'Май',
      6 => 'Июн',
      7 => 'Июл',
      8 => 'Авг',
      9 => 'Сен',
      10 => 'Окт',
      11 => 'Ноя',
      12 => 'Дек',
    ),
    'narrow' => 
    array (
      1 => 'Я',
      2 => 'Ф',
      3 => 'М',
      4 => 'А',
      5 => 'М',
      6 => 'И',
      7 => 'И',
      8 => 'А',
      9 => 'С',
      10 => 'О',
      11 => 'Н',
      12 => 'Д',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'якшанба',
      1 => 'душанба',
      2 => 'сешанба',
      3 => 'чоршанба',
      4 => 'пайшанба',
      5 => 'жума',
      6 => 'шанба',
    ),
    'abbreviated' => 
    array (
      0 => 'Якш',
      1 => 'Душ',
      2 => 'Сеш',
      3 => 'Чор',
      4 => 'Пай',
      5 => 'Жум',
      6 => 'Шан',
    ),
    'narrow' => 
    array (
      0 => 'Я',
      1 => 'Д',
      2 => 'С',
      3 => 'Ч',
      4 => 'П',
      5 => 'Ж',
      6 => 'Ш',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
