<?php
/**
 * Locale data for 'uz_Latn_UZ'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.19',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'UZS' => 'soʿm',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Muharram',
      2 => 'Safar',
      3 => 'Rabiul-avval',
      4 => 'Rabiul-oxir',
      5 => 'Jumodiul-ulo',
      6 => 'Jumodiul-uxro',
      7 => 'Rajab',
      8 => 'Shaʿbon',
      9 => 'Ramazon',
      10 => 'Shavvol',
      11 => 'Zil-qaʿda',
      12 => 'Zil-hijja',
    ),
    'abbreviated' => 
    array (
      1 => 'Yanv',
      2 => 'Fev',
      3 => 'Mar',
      4 => 'Apr',
      5 => 'May',
      6 => 'Iyun',
      7 => 'Iyul',
      8 => 'Avg',
      9 => 'Sen',
      10 => 'Okt',
      11 => 'Noya',
      12 => 'Dek',
    ),
    'narrow' => 
    array (
      1 => 'Y',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'I',
      7 => 'I',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'yakshanba',
      1 => 'dushanba',
      2 => 'seshanba',
      3 => 'chorshanba',
      4 => 'payshanba',
      5 => 'juma',
      6 => 'shanba',
    ),
    'abbreviated' => 
    array (
      0 => 'Yaksh',
      1 => 'Dush',
      2 => 'Sesh',
      3 => 'Chor',
      4 => 'Pay',
      5 => 'Jum',
      6 => 'Shan',
    ),
    'narrow' => 
    array (
      0 => 'Y',
      1 => 'D',
      2 => 'S',
      3 => 'C',
      4 => 'P',
      5 => 'J',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
