<?php
/**
 * Locale data for 'vi'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.70',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'VND' => '₫',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'tháng một',
      2 => 'tháng hai',
      3 => 'tháng ba',
      4 => 'tháng tư',
      5 => 'tháng năm',
      6 => 'tháng sáu',
      7 => 'tháng bảy',
      8 => 'tháng tám',
      9 => 'tháng chín',
      10 => 'tháng mười',
      11 => 'tháng mười một',
      12 => 'tháng mười hai',
    ),
    'abbreviated' => 
    array (
      1 => 'thg 1',
      2 => 'thg 2',
      3 => 'thg 3',
      4 => 'thg 4',
      5 => 'thg 5',
      6 => 'thg 6',
      7 => 'thg 7',
      8 => 'thg 8',
      9 => 'thg 9',
      10 => 'thg 10',
      11 => 'thg 11',
      12 => 'thg 12',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Chủ nhật',
      1 => 'Thứ hai',
      2 => 'Thứ ba',
      3 => 'Thứ tư',
      4 => 'Thứ năm',
      5 => 'Thứ sáu',
      6 => 'Thứ bảy',
    ),
    'abbreviated' => 
    array (
      0 => 'CN',
      1 => 'Th 2',
      2 => 'Th 3',
      3 => 'Th 4',
      4 => 'Th 5',
      5 => 'Th 6',
      6 => 'Th 7',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'tr. CN',
      1 => 'sau CN',
    ),
    'wide' => 
    array (
      0 => 'tr. CN',
      1 => 'sau CN',
    ),
    'narrow' => 
    array (
      0 => 'tr. CN',
      1 => 'sau CN',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, \'ngày\' dd MMMM \'năm\' yyyy',
    'long' => '\'Ngày\' dd \'tháng\' M \'năm\' yyyy',
    'medium' => 'dd-MM-yyyy',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{0} {1}',
  'amName' => 'SA',
  'pmName' => 'CH',
);
