<?php
/**
 * Locale data for 'vo'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2013 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2014 Yii Software LLC (https://www.yiiframework.com/license/)
 */
return array (
  'version' => '8245',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'A$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'janul',
      2 => 'febul',
      3 => 'mäzil',
      4 => 'prilul',
      5 => 'mayul',
      6 => 'yunul',
      7 => 'yulul',
      8 => 'gustul',
      9 => 'setul',
      10 => 'tobul',
      11 => 'novul',
      12 => 'dekul',
    ),
    'abbreviated' => 
    array (
      1 => 'jan',
      2 => 'feb',
      3 => 'mäz',
      4 => 'prl',
      5 => 'may',
      6 => 'yun',
      7 => 'yul',
      8 => 'gst',
      9 => 'set',
      10 => 'ton',
      11 => 'nov',
      12 => 'dek',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'P',
      5 => 'M',
      6 => 'Y',
      7 => 'Y',
      8 => 'G',
      9 => 'S',
      10 => 'T',
      11 => 'N',
      12 => 'D',
    ),
    'abbreviated' => 
    array (
      1 => 'jan',
      2 => 'feb',
      3 => 'mäz',
      4 => 'prl',
      5 => 'may',
      6 => 'yun',
      7 => 'yul',
      8 => 'gst',
      9 => 'set',
      10 => 'tob',
      11 => 'nov',
      12 => 'Dek',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'sudel',
      1 => 'mudel',
      2 => 'tudel',
      3 => 'vedel',
      4 => 'dödel',
      5 => 'fridel',
      6 => 'zädel',
    ),
    'abbreviated' => 
    array (
      0 => 'su.',
      1 => 'mu.',
      2 => 'tu.',
      3 => 've.',
      4 => 'dö.',
      5 => 'fr.',
      6 => 'zä.',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'T',
      3 => 'V',
      4 => 'D',
      5 => 'F',
      6 => 'Z',
    ),
    'abbreviated' => 
    array (
      0 => 'Su',
      1 => 'Mu',
      2 => 'Tu',
      3 => 'Ve',
      4 => 'Dö',
      5 => 'Fr',
      6 => 'Zä',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'b. t. kr.',
      1 => 'p. t. kr.',
    ),
    'wide' => 
    array (
      0 => 'b. t. kr.',
      1 => 'p. t. kr.',
    ),
    'narrow' => 
    array (
      0 => 'b. t. kr.',
      1 => 'p. t. kr.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'y MMMMa \'d\'. d\'id\'',
    'long' => 'y MMMM d',
    'medium' => 'y MMM. d',
    'short' => 'y-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'posz.',
  'pmName' => 'büz.',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'vo' => 'Volapük',
  ),
  'pluralRules' => 
  array (
    0 => 'n==1',
    1 => 'true',
  ),
);
