<?php
/**
 * Locale data for 'yo'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.26',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'NGN' => '₦',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Oṣù Ṣẹ́rẹ́',
      2 => 'Oṣù Èrèlè',
      3 => 'Oṣù Ẹrẹ̀nà',
      4 => 'Oṣù Ìgbé',
      5 => 'Oṣù Ẹ̀bibi',
      6 => 'Oṣù Òkúdu',
      7 => 'Oṣù Agẹmọ',
      8 => 'Oṣù Ògún',
      9 => 'Oṣù Owewe',
      10 => 'Oṣù Ọ̀wàrà',
      11 => 'Oṣù Bélú',
      12 => 'Oṣù Ọ̀pẹ̀',
    ),
    'abbreviated' => 
    array (
      1 => 'Ṣẹ́rẹ́',
      2 => 'Èrèlè',
      3 => 'Ẹrẹ̀nà',
      4 => 'Ìgbé',
      5 => 'Ẹ̀bibi',
      6 => 'Òkúdu',
      7 => 'Agẹmọ',
      8 => 'Ògún',
      9 => 'Owewe',
      10 => 'Ọ̀wàrà',
      11 => 'Bélú',
      12 => 'Ọ̀pẹ̀',
    ),
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Ọjọ́ Àìkú',
      1 => 'Ọjọ́ Ajé',
      2 => 'Ọjọ́ Ìsẹ́gun',
      3 => 'Ọjọ́rú',
      4 => 'Ọjọ́ Àṣẹ̀ṣẹ̀dáiyé',
      5 => 'Ọjọ́ Ẹtì',
      6 => 'Ọjọ́ Àbámẹ́ta',
    ),
    'abbreviated' => 
    array (
      0 => 'Àìkú',
      1 => 'Ajé',
      2 => 'Ìsẹ́gun',
      3 => 'Ọjọ́rú',
      4 => 'Àṣẹ̀ṣẹ̀dáiyé',
      5 => 'Ẹtì',
      6 => 'Àbámẹ́ta',
    ),
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'SK',
      1 => 'LK',
    ),
    'wide' => 
    array (
      0 => 'Saju Kristi',
      1 => 'Lehin Kristi',
    ),
    'narrow' => 
    array (
      0 => 'SK',
      1 => 'LK',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, yyyy MMMM dd',
    'long' => 'yyyy MMMM d',
    'medium' => 'yyyy MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss v',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'àárọ̀',
  'pmName' => 'ọ̀sán',
);
