<?php
/**
 * Locale data for 'zh_Hans_CN'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.36',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'ITL',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'CNY' => '￥',
    'HKD' => 'HK$',
    'KRW' => '￦',
    'MOP' => 'P',
    'SAR' => 'SRl',
    'SGD' => 'S$',
    'TWD' => 'NT$',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => '1月',
      2 => '2月',
      3 => '3月',
      4 => '4月',
      5 => '5月',
      6 => '6月',
      7 => '7月',
      8 => '8月',
      9 => '9月',
      10 => '10月',
      11 => '11月',
      12 => '12月',
    ),
    'abbreviated' => 
    array (
      1 => '1月',
      2 => '2月',
      3 => '3月',
      4 => '4月',
      5 => '5月',
      6 => '6月',
      7 => '7月',
      8 => '8月',
      9 => '9月',
      10 => '10月',
      11 => '11月',
      12 => '12月',
    ),
    'narrow' => 
    array (
      1 => '1月',
      2 => '2月',
      3 => '3月',
      4 => '4月',
      5 => '5月',
      6 => '6月',
      7 => '7月',
      8 => '8月',
      9 => '9月',
      10 => '10月',
      11 => '11月',
      12 => '12月',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => '星期日',
      1 => '星期一',
      2 => '星期二',
      3 => '星期三',
      4 => '星期四',
      5 => '星期五',
      6 => '星期六',
    ),
    'abbreviated' => 
    array (
      0 => '周日',
      1 => '周一',
      2 => '周二',
      3 => '周三',
      4 => '周四',
      5 => '周五',
      6 => '周六',
    ),
    'narrow' => 
    array (
      0 => '日',
      1 => '一',
      2 => '二',
      3 => '三',
      4 => '四',
      5 => '五',
      6 => '六',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => '公元前',
      1 => '公元',
    ),
    'wide' => 
    array (
      0 => '公元前',
      1 => '公元',
    ),
    'narrow' => 
    array (
      0 => '公元前',
      1 => '公元',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'yyyy年M月d日EEEE',
    'long' => 'yyyy年M月d日',
    'medium' => 'yyyy-M-d',
    'short' => 'yy-M-d',
  ),
  'timeFormats' => 
  array (
    'full' => 'ahh时mm分ss秒v',
    'long' => 'ahh时mm分ss秒z',
    'medium' => 'ahh:mm:ss',
    'short' => 'ah:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => '上午',
  'pmName' => '下午',
);
