<?php
/**
 * Locale data for 'zu'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2009 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '1.21',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'nativeZeroDigit' => '0',
    'patternDigit' => '#',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'BRL' => 'R$',
    'EUR' => '€',
    'GBP' => 'UK£',
    'INR' => '0≤Rs.|1≤Re.|1<Rs.',
    'ITL' => 'IT₤',
    'JPY' => 'JP¥',
    'USD' => 'US$',
    'ZAR' => 'R',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Januwari',
      2 => 'Februwari',
      3 => 'Mashi',
      4 => 'Apreli',
      5 => 'Meyi',
      6 => 'Juni',
      7 => 'Julayi',
      8 => 'Agasti',
      9 => 'Septhemba',
      10 => 'Okthoba',
      11 => 'Novemba',
      12 => 'Disemba',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Feb',
      3 => 'Mas',
      4 => 'Apr',
      5 => 'Mey',
      6 => 'Jun',
      7 => 'Jul',
      8 => 'Aga',
      9 => 'Sep',
      10 => 'Okt',
      11 => 'Nov',
      12 => 'Dis',
    ),
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'J',
      7 => 'J',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Sonto',
      1 => 'Msombuluko',
      2 => 'Lwesibili',
      3 => 'Lwesithathu',
      4 => 'uLwesine',
      5 => 'Lwesihlanu',
      6 => 'Mgqibelo',
    ),
    'abbreviated' => 
    array (
      0 => 'Son',
      1 => 'Mso',
      2 => 'Bil',
      3 => 'Tha',
      4 => 'Sin',
      5 => 'Hla',
      6 => 'Mgq',
    ),
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'B',
      3 => 'T',
      4 => 'S',
      5 => 'H',
      6 => 'M',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BC',
      1 => 'AD',
    ),
    'wide' => 
    array (
      0 => 'BC',
      1 => 'AD',
    ),
    'narrow' => 
    array (
      0 => 'BC',
      1 => 'AD',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE dd MMMM yyyy',
    'long' => 'd MMMM yyyy',
    'medium' => 'd MMM yyyy',
    'short' => 'yyyy-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a v',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
);
