<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure you want to delete this item?' => 'この項目を削除してもよろしいですか?',
  'Delete' => '削除',
  'Displaying {start}-{end} of {count} result(s).' => '{count}個の結果を{start}から{end}まで表示します。',
  'Either "name" or "value" must be specified for CDataColumn.' => 'CDataColumnの"name"または"value"を指定しなければなりません。',
  'No results found.' => '結果が得られませんでした。',
  'Not set' => 'セットされません。',
  'Please specify the "attributes" property.' => '"attributes"プロパティを指定してください。',
  'Please specify the "data" property.' => '"data"プロパティを指定してください。',
  'Sort by: ' => 'ソート:',
  'The "dataProvider" property cannot be empty.' => '"dataProvider"プロパティは空ではいけません。',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '"Type"と"Label"がオプションであるときアトリビュートは"Name:Type:Label"というフォーマットで指定されます。',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '"Type"と"Label"がオプションであるときカラムは"Name:Type:Label"というフォーマットで指定されます。',
  'The property "itemView" cannot be empty.' => '"itemView"プロパティは空ではいけません。',
  'Total {count} result(s).' => 'トータル{count}個',
  'Update' => '更新',
  'View' => '表示',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class}は"model"と"attribute"または"name"プロパティ値を指定すべきです。',
);
