<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Home' => 'Pagina principală',
  'The button type "{type}" is not supported.' => 'Tipul de buton „{type}” nu este suportat.',
  'Are you sure you want to delete this item?' => 'Confirmați ștergerea acestui element?',
  'Delete' => 'Ștergere',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Se afișează 1 rezultat.|Se afișează {start}-{end} din {count} rezultate.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Trebuie să specificați "name" sau "value" pentru CDataColumn.',
  'No results found.' => 'Nu sunt rezultate pentru afișare.',
  'Not set' => 'Nu este definit(ă)',
  'Please specify the "attributes" property.' => 'Definiți proprietatea „attributes”.',
  'Please specify the "data" property.' => 'Definiți proprietatea „data”.',
  'Sort by: ' => 'Sortare după: ',
  'The "dataProvider" property cannot be empty.' => 'Proprietatea „dataProvider” nu poate fi nulă.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Atributul trebuie definit în formatul „Name:Type:Label”, unde „Type” și „Label” sunt opționale.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Coloana trebuie definită în formatul „Name:Type:Label”, unde „Type” et „Label” sunt opționale.',
  'The property "itemView" cannot be empty.' => 'Proprietatea „itemView” nu poate fi nulă',
  'Total 1 result.|Total {count} results.' => 'Total 1 rezultat.|Total {count} rezultate.',
  'Update' => 'Actualizare',
  'View' => 'Vizualizare',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} trebuie să definească valori pentru proprietățile „model” și „attribute” sau „name”.',
);
