<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure you want to delete this item?' => 'Ben je zeker dat je dit item wil verwijderen?',
  'Delete' => 'Verwijderen',
  'Displaying {start}-{end} of {count} result(s).' => 'Getoond: {start}-{end} van {count} resulta(a)t(en).',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Of "name" of "value" moet opgegeven worden voor CDataColumn',
  'Home' => 'Thuis',
  'No results found.' => 'Geen resultaten gevonden',
  'Not set' => 'Niet opgegeven',
  'Please specify the "attributes" property.' => 'Gelieve het "attributes" property op te geven',
  'Please specify the "data" property.' => 'Gelieve het "data" property op te geven',
  'Sort by: ' => 'Sorteren volgens: ',
  'The "dataProvider" property cannot be empty.' => 'Het "dataProvider" property mag niet leeg zijn.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Het formaat van het attribute moet "Name:Type:Label" zijn, "Type" en "Label" zijn optioneel.',
  'The button type "{type}" is not supported.' => 'Het button type "{type}" wordt niet ondersteund.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Het formaat van de kolom moet "Name:Type:Label" zijn, "Type" en "Label" zijn optioneel.',
  'The property "itemView" cannot be empty.' => 'Het "itemView" property mag niet leeg zijn.',
  'Total {count} result(s).' => 'Totaal {count} resulta(a)t(en).',
  'Update' => 'Updaten',
  'View' => 'Bekijken',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} moet de "model" en "attribute" of "name" property waarden bevatten.',
);
