<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER non contiene {vars}.',
  '$_SERVER variable' => 'variabile $_SERVER',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] deve essere identico al path del file di entrata.',
  'APC extension' => 'Estensione APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Tutte le <a href="http://www.yiiframework.com/doc/api/#system.db">classi legate al DB</a>',
  'DOM extension' => 'Estensione DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Uno tra $_SERVER["REQUEST_URI"] o $_SERVER["QUERY_STRING"] deve esistere',
  'GD extension' => 'Estensione GD',
  'Mcrypt extension' => 'Estensione Mcrypt',
  'Memcache extension' => 'Estensione Memcache',
  'PCRE extension' => 'Estensione PCRE',
  'PDO MySQL extension' => 'Estensione PDO MySQL',
  'PDO PostgreSQL extension' => 'Estensione PDO PostgreSQL',
  'PDO SQLite extension' => 'Estensione PDO SQLite',
  'PDO extension' => 'Estensione PDO',
  'PHP 5.1.0 or higher is required.' => 'È richiesto PHP 5.1.0 o superiore',
  'PHP version' => 'Versione PHP',
  'Reflection extension' => 'Estensione Reflection',
  'SOAP extension' => 'Estensione SOAP',
  'SPL extension' => 'Estensione SPL',
  'This is required if you are using MySQL database.' => 'Necessario se si utilizza il database MySQL.',
  'This is required if you are using PostgreSQL database.' => 'Necessario se si utilizza il database PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Necessario se si utilizza il database SQLite .',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Impossibile determinare il path dell\'URL. Assicurarsi che $_SERVER["PATH_INFO"] (o $_SERVER["PHP_SELF"] e $_SERVER["SCRIPT_NAME"]) contengano valori adeguati.',
);