#!/usr/bin/env php
<?php
/**
 * Yii command line script file.
 *
 * This script is meant to be run on command line to execute
 * one of the pre-defined console commands.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @link http://www.yiiframework.com/
 * @copyright Copyright &copy; 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 * @version $Id$
 */

defined('YII_DEBUG') or define('YII_DEBUG',true);

// disable E_NOTICE so that "yiic shell" is more friendly
error_reporting(E_ALL ^ E_NOTICE);

require_once(dirname(__FILE__).'/yii.php');
Yii::createConsoleApplication(array('basePath'=>dirname(__FILE__).'/cli'))->run();
