#!/usr/bin/env php
<?php
/**
 * Yee command line script for Unix/Linux.
 *
 * This is the bootstrap script for running yeec on Unix/Linux.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @link http://www.yeeframework.com/
 * @copyright 2008 Yee Software LLC
 * @license http://www.yeeframework.com/license/
 */

require_once(dirname(__FILE__).'/yeec.php');
