<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Home' => 'Басты',
  'The button type "{type}" is not supported.' => 'Батырманың "{type}" түріне қолдау жоқ.',
  'Are you sure you want to delete this item?' => 'Бұл нәрсені өшіруді шынымен қалайсыз ба?',
  'Delete' => 'Өшіру',
  'Displaying {start}-{end} of {count} result(s).' => '{start}—{end} нәрсе, барлығы {count}.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'CDataColumn үшін "name" не "value" көрсету керек.',
  'No results found.' => 'Нәтижелері жоқ.',
  'Not set' => 'Орнатылмаған',
  'Please specify the "attributes" property.' => '"attributes" қасиетін орнатыңыз.',
  'Please specify the "data" property.' => '"data" қасиетін орнатыңыз.',
  'Sort by: ' => 'Сұрыптау: ',
  'The "dataProvider" property cannot be empty.' => '"dataProvider" қасиеті бос болмауы тиіс.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Атрибут "Аты:Түрі:Тақырыптамасы" пішімінде көрсетілуі тиіс. "Түрі" мен "Тақырыптамасы" міндетті емес.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Баған "Аты:Түрі:Тақырыптамасы" пішімінде көрсетілуі тиіс. "Түрі" мен "Тақырыптамасы" міндетті емес.',
  'The property "itemView" cannot be empty.' => '"itemView" қасиеті бос болмауы тиіс.',
  'Total {count} result(s).' => 'Барлық нәтиже саны: {count}.',
  'Update' => 'Жаңарту',
  'View' => 'Қарау',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} класында "model" и "attribute" қасиеттерінің мәндері, немесе "name" мәні берілуі керек.',
);
