<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => 'Расширение GD<br />с поддержкой FreeType<br /> или ImageMagick<br /> с поддержкой PNG',
  '$_SERVER does not have {vars}.' => 'Переменная $_SERVER не содержит {vars}.',
  '$_SERVER variable' => 'Переменная $_SERVER.',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => 'Переменная $_SERVER["SCRIPT_FILENAME"] должна соответствовать пути к файлу входного скрипта.',
  'APC extension' => 'Расширение APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Все <a href="http://www.yiiframework.com/doc/api/#system.db">DB-классы</a>',
  'Ctype extension' => 'Расширение Ctype',
  'DOM extension' => 'Расширение DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Должна существовать хотя бы одна из серверных переменных: $_SERVER["REQUEST_URI"] или $_SERVER["QUERY_STRING"].',
  'GD installed,<br />FreeType support not installed' => 'Расширение GD установлено<br />без поддержки FreeType',
  'GD or ImageMagick not installed' => 'Расшиение GD или ImageMagick не установлены',
  'Mcrypt extension' => 'Расширение Mcrypt',
  'Memcache extension' => 'Расширение Memcache',
  'PCRE extension' => 'Расширение PCRE',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => 'Расширение PDO MSSQL (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)',
  'PDO MSSQL extension (pdo_dblib)' => 'Расширение PDO MSSQL (pdo_dblib)',
  'PDO MSSQL extension (pdo_mssql)' => 'Расширение PDO MSSQL (pdo_mssql)',
  'PDO MySQL extension' => 'Расширение PDO MySQL',
  'PDO Oracle extension' => 'Расширение PDO Oracle',
  'PDO PostgreSQL extension' => 'Расширение PDO PostgreSQL',
  'PDO SQLite extension' => 'Расширение PDO SQLite',
  'PDO extension' => 'Расширение PDO',
  'PHP 5.1.0 or higher is required.' => 'Необходима версия РНР 5.1.0 и выше.',
  'PHP version' => 'Версия РНР',
  'Reflection extension' => 'Расширение',
  'SOAP extension' => 'Расширение SOAP',
  'SPL extension' => 'Расширение SPL',
  'This is required by encrypt and decrypt methods.' => 'Требуется для работы методов шифрования и дешифрации.',
  'This is required if you are using MSSQL database from GNU/Linux or other UNIX.' => 'Требуется для работы с БД MSSQL при использовании из GNU/Linux или UNIX.',
  'This is required if you are using MSSQL database from MS Windows' => 'Требуется для работы с БД MSSQL при использовании из MS Windows.',
  'This is required if you are using MSSQL database with the driver provided by Microsoft.' => 'Требуется для работы с БД MSSQL при использовании драйвера от Microsoft.',
  'This is required if you are using MySQL database.' => 'Требуется для работы с БД MySQL.',
  'This is required if you are using Oracle database.' => 'Требуется для работы с БД Oracle.',
  'This is required if you are using PostgreSQL database.' => 'Требуется для работы с БД PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Требуется для работы с БД SQLite.',
  'To use memcached set <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => 'Чтобы использовать memcached установите значение свойства <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> равным <code>true</code>.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Не удалось получить информацию о пути. Пожалуйста, проверьте, содержится ли корректное значение в переменной $_SERVER["PATH_INFO"] (или $_SERVER["PHP_SELF"] и $_SERVER["SCRIPT_NAME"]).',
);
