<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER verfügt nicht über {vars}.',
  '$_SERVER variable' => '$_SERVER Variable',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] muss der selbe Eingangsscriptpfad sein.',
  'APC extension' => 'APC Erweiterung',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Alle <a href="http://www.yiiframework.com/doc/api/#system.db">DB-bezüglichen Klassen</a>',
  'DOM extension' => 'DOM Erweiterung',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Entweder $_SERVER["REQUEST_URI"] oder $_SERVER["QUERY_STRING"] müssen exisitieren.',
  'GD extension' => 'GD Erweiterung',
  'Mcrypt extension' => 'Mcyrpt Erweiterung',
  'Memcache extension' => 'Memcache Erweiterung',
  'PCRE extension' => 'PCRE Erweiterung',
  'PDO MySQL extension' => 'PDO MySQL Erweiterung',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL Erweiterung',
  'PDO SQLite extension' => 'PDO SQLite Erweiterung',
  'PDO extension' => 'PDO Erweiterung',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0 oder Neuer wird benötigt.',
  'PHP version' => 'PHP Version',
  'Reflection extension' => 'Reflection Erweiterung',
  'SOAP extension' => 'SOAP Erweiterung',
  'SPL extension' => 'SPL Erweiterung',
  'This is required if you are using MySQL database.' => 'Dies wird bei Verwendung einer MySQL Datenbank benötigt.',
  'This is required if you are using PostgreSQL database.' => 'Dies wird bei Verwendung einer PostgreSQL Datenbank benötigt.',
  'This is required if you are using SQLite database.' => 'Dies wird bei Verwendung einer SQLite Datenbank benötigt.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Die URL Pfadinformation kann nicht ermittelt werden. Stellen Sie bitte sicher, dass entweder $_SERVER["PATH_INFO"] (oder $_SERVER["PHP_SELF"] und $_SERVER["SCRIPT_NAME"]) mit korrekten Werten gefüllt sind.',
);
