<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'This is required by encrypt and decrypt methods.' => 'É necessário aos métodos encrypt e decrypt.',
  '$_SERVER does not have {vars}.' => '$_SERVER não possui {vars}.',
  '$_SERVER variable' => 'variável $_SERVER',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] precisa ser o mesmo que o arquivo de script de entrada.',
  'APC extension' => 'extensão APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Todas as classes relacionadas ao <a href="http://www.yiiframework.com/doc/api/#system.db">banco de dados</a>',
  'DOM extension' => 'extensão DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"] ou $_SERVER["QUERY_STRING"] é obrigatório.',
  'GD extension' => 'extensão GD',
  'Mcrypt extension' => 'extensão Mcrypt',
  'Memcache extension' => 'extensão Memcache',
  'PCRE extension' => 'extensão PCRE',
  'PDO MySQL extension' => 'extensão PDO_MySQL',
  'PDO PostgreSQL extension' => 'extensão PDO_PostgreSQL',
  'PDO SQLite extension' => 'extensão PDO_SQLite',
  'PDO extension' => 'extensão PDO',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0 ou mais recente é necessário.',
  'PHP version' => 'versão PHP',
  'Reflection extension' => 'extensão Reflection',
  'SOAP extension' => 'extensão SOAP',
  'SPL extension' => 'extensão SPL',
  'This is required if you are using MySQL database.' => 'Este item é obrigatório se você estiver utilizando MySQL.',
  'This is required if you are using PostgreSQL database.' => 'Este item é obrigatório se você estiver utilizando PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Este item é obrigatório se você estiver utilizando SQLite.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Não foi possível determinar o caminho da URL. Verifique se $_SERVER["PATH_INFO"] (ou $_SERVER["PHP_SELF"] e $_SERVER["SCRIPT_NAME"]) contem os valores corretos.',
);
