<?php
/**
 * Message translations for [sk].
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure you want to delete this item?' => 'Odstrániť záznam?',
  'Delete' => 'Odstrániť',
  'Displaying {start}-{end} of {count} result(s).' => 'Zobrazených {start}-{end} z celkovo {count} záznamov.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Uveďte prosím  "name" alebo "value" pre CDataColumn.',
  'Home' => 'Úvod',
  'No results found.' => 'Neboli nájdené žiadne záznamy.',
  'Not set' => 'Nie je nastavený',
  'Please specify the "attributes" property.' => 'Zadajte prosím vlastnosti pre "attributes".',
  'Please specify the "data" property.' => 'Zadajte prosím vlastnosti pre "data".',
  'Sort by: ' => 'Zoradané podľa:',
  'The "dataProvider" property cannot be empty.' => 'Vlastnosť "dataProvider" nesmie byť prázdna.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Atribút musí byť špecifikovaný v tvare "Name:Type:Label", pričom "Type" a "Label" sú nepovinné.',
  'The button type "{type}" is not supported.' => 'Tlačidlo typu "{type}" nie je podporované.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Stĺpec musí byť špecifikovaný v tvare "Name:Type:Label", pričom "Type" a "Label" sú nepovinné.',
  'The property "itemView" cannot be empty.' => 'Vlastnosť "itemView" nesmie byť prázdna.',
  'Total {count} result(s).' => 'Nájdených celkovo {count} záznamov',
  'Update' => 'Uložiť zmeny',
  'View' => 'Náhľad',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} musí mať špecifikované vlastnosti pre "model" a "attribute" alebo "name".',
);
