<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Ctype extension' => 'Extension Ctype',
  '$_SERVER does not have {vars}.' => '$_SERVER tidak memiliki {vars}.',
  '$_SERVER variable' => 'Variabel $_SERVER',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] harus sama dengan alur file skrip entri',
  'APC extension' => 'Extension APC',
  'All <a href="https://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Semua <a href="https://www.yiiframework.com/doc/api/#system.db">kelas berhubungan DB </a>',
  'DOM extension' => 'Extension DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Salah satu dari $_SERVER["REQUEST_URI"] atau $_SERVER["QUERY_STRING"] harus ada.',
  'GD extension with<br />FreeType support' => 'Dukungan Extension GD dengan <br/>FreeType',
  'GD installed<br />FreeType support not installed' => 'GD terinstalasi<br/>Dukungan FreeType tidak terinstalasi',
  'GD not installed' => 'GD tidak terinstalasi',
  'Mcrypt extension' => 'Extension Mcrypt',
  'Memcache extension' => 'Extension Memcache',
  'PCRE extension' => 'Extension PCRE',
  'PDO MySQL extension' => 'Extension PDO MySQL',
  'PDO PostgreSQL extension' => 'Extension PDO PostgreSQL',
  'PDO SQLite extension' => 'Extension PDO SQLite',
  'PDO extension' => 'Extension PDO',
  'PHP 5.1.0 or higher is required.' => 'Diperlukan PHP 5.1.0 atau lebih tinggi.',
  'PHP version' => 'Versi PHP',
  'Reflection extension' => 'Extension Reflection',
  'SOAP extension' => 'Extension SOAP',
  'SPL extension' => 'Extension SPL',
  'This is required by encrypt and decrypt methods.' => 'Ini diperlukan oleh method enkripsi dan dekripsi',
  'This is required if you are using MySQL database.' => 'Ini diperlukan apabila anda menggunakan database MySQL',
  'This is required if you are using PostgreSQL database.' => 'Ini diperlukan apabila anda menggunakan database PostgreSQL',
  'This is required if you are using SQLite database.' => 'Ini diperlukan apabila anda menggunakan database SQLite',
  'To use memcached set <a href="https://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => 'Untuk menggunakan memcached set <a href="https://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> menjadi <code>true</code>.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Tidak dapat menentukan info alur URL. Harap memastikan $_SERVER["PATH_INFO"] (atau $_SERVER["PHP_SELF"] dan $_SERVER"SCRIPT_NAME"]) berisi nilai yang benar.',
);