<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER tidak memiliki {vars}.',
  '$_SERVER variable' => 'Variabel $_SERVER',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] harus sama dengan alur file skrip entri',
  'APC extension' => 'Ekstensi APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Semua <a href="http://www.yiiframework.com/doc/api/#system.db">kelas berhubungan DB </a>',
  'DOM extension' => 'Ekstensi DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Salah satu dari $_SERVER["REQUEST_URI"] atau $_SERVER["QUERY_STRING"] harus ada.',
  'GD extension with<br />FreeType support' => 'Dukungan Ekstensi GD dengan <br/>FreeType',
  'GD installed<br />FreeType support not installed' => 'GD terinstalasi<br/>Dukungan FreeType tidak terinstalasi',
  'GD not installed' => 'GD tidak terinstalasi',
  'Mcrypt extension' => 'Ekstensi Mcrypt',
  'Memcache extension' => 'Ekstensi Memcache',
  'PCRE extension' => 'Ekstensi PCRE',
  'PDO MySQL extension' => 'Ekstensi PDO MySQL',
  'PDO PostgreSQL extension' => 'Ekstensi PDO PostgreSQL',
  'PDO SQLite extension' => 'Ekstensi PDO SQLite',
  'PDO extension' => 'Ekstensi PDO',
  'PHP 5.1.0 or higher is required.' => 'Diperlukan PHP 5.1.0 atau lebih tinggi.',
  'PHP version' => 'Versi PHP',
  'Reflection extension' => 'Ekstensi Reflection',
  'SOAP extension' => 'Ekstensi SOAP',
  'SPL extension' => 'Ekstensi SPL',
  'This is required by encrypt and decrypt methods.' => 'Ini diperlukan oleh metode enkripsi dan dekripsi',
  'This is required if you are using MySQL database.' => 'Ini diperlukan apabila anda menggunakan basis data MySQL',
  'This is required if you are using PostgreSQL database.' => 'Ini diperlukan apabila anda menggunakan basis data PostgreSQL',
  'This is required if you are using SQLite database.' => 'Ini diperlukan apabila anda menggunakan basis data SQLite',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Tidak dapat menentukan info alur URL. Harap memastikan $_SERVER["PATH_INFO"] (atau $_SERVER["PHP_SELF"] dan $_SERVER"SCRIPT_NAME"]) mengandung nilai yang benar.',
  'GD extension' => 'Ekstensi GD',
);
