<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER heeft geen {vars}.',
  '$_SERVER variable' => '$_SERVER variabele',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] moet hetzelfde zijn als het bestandspad van het startscript.',
  'APC extension' => 'APC extensie',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Alle <a href="http://www.yiiframework.com/doc/api/#system.db">DB-gerelateerde classes</a>',
  'DOM extension' => 'DOM extensie',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Of $_SERVER["REQUEST_URI"] of $_SERVER["QUERY_STRING"] moet gedefinieerd zijn.',
  'GD extension' => 'GD extensie',
  'Mcrypt extension' => 'Mcrypt extensie',
  'Memcache extension' => 'Memcache extensie',
  'PCRE extension' => 'PCRE extensie',
  'PDO MySQL extension' => 'PDO MySQL extensie',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL extensie',
  'PDO SQLite extension' => 'PDO SQLite extensie',
  'PDO extension' => 'PDO extensie',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0 of hoger is vereist.',
  'PHP version' => 'PHP versie',
  'Reflection extension' => 'Reflection extensie',
  'SOAP extension' => 'SOAP extensie',
  'SPL extension' => 'SPL extensie',
  'This is required if you are using MySQL database.' => 'Dit is vereist als een MySQL database wordt gebruikt.',
  'This is required if you are using PostgreSQL database.' => 'Dit is vereist als een PostgreSQL database wordt gebruikt.',
  'This is required if you are using SQLite database.' => 'Dit is vereist als een SQLite database wordt gebruikt.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Niet in staat om informatie over het URL pad te verkrijgen. Zorg er a.u.b. voor dat $_SERVER["PATH_INFO"] (of $_SERVER["PHP_SELF"] en $_SERVER["SCRIPT_NAME"]) een juiste waarde bevatten.',
);
