<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '$_SERVER does not have {vars}.' => 'Змінна $_SERVER не містить {vars}.',
  '$_SERVER variable' => 'Змінна $_SERVER.',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => 'Змінна $_SERVER["SCRIPT_FILENAME"] повинна відповідати шляху до файла вхідного скрипта.',
  'APC extension' => 'Розширення APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Всі <a href="http://www.yiiframework.com/doc/api/#system.db">DB-класи</a>',
  'DOM extension' => 'Розширення DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Повинна існувати хоча б одна з серверних змінних: $_SERVER["REQUEST_URI"] або $_SERVER["QUERY_STRING"].',
  'GD extension' => 'Розширення GD',
  'Mcrypt extension' => 'Розширення Mcrypt',
  'Memcache extension' => 'Розширення Memcache',
  'PCRE extension' => 'Розширення PCRE',
  'PDO MySQL extension' => 'Розширення PDO MySQL',
  'PDO PostgreSQL extension' => 'Розширення PDO PostgreSQL',
  'PDO SQLite extension' => 'Розширення PDO SQLite',
  'PDO extension' => 'Розширення PDO',
  'PHP 5.1.0 or higher is required.' => 'Вимагається версія РНР 5.1.0 і вище.',
  'PHP version' => 'Версія РНР',
  'Reflection extension' => 'Розширення Reflection',
  'SOAP extension' => 'Розширення SOAP',
  'SPL extension' => 'Розширення SPL',
  'This is required by encrypt and decrypt methods.' => 'Вимагається для роботи методів шифрування і дешифрування.',
  'This is required if you are using MySQL database.' => 'Вимагається для роботи з БД MySQL.',
  'This is required if you are using PostgreSQL database.' => 'Вимагається для роботи з БД PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Вимагається для роботи з БД SQLite.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Не вдалось отримати інформацію про URL-шлях. Будь ласка, перевірте чи містяться вірні значення у змінній $_SERVER["PATH_INFO"] (або $_SERVER["PHP_SELF"] і $_SERVER["SCRIPT_NAME"]).',
);
