<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '',
  '$_SERVER variable' => '',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '',
  'APC extension' => '',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => '',
  'DOM extension' => '',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '',
  'GD extension' => '',
  'Mcrypt extension' => '',
  'Memcache extension' => '',
  'PCRE extension' => '',
  'PDO MySQL extension' => '',
  'PDO PostgreSQL extension' => '',
  'PDO SQLite extension' => '',
  'PDO extension' => '',
  'PHP 5.1.0 or higher is required.' => '',
  'PHP version' => '',
  'Reflection extension' => '',
  'SOAP extension' => '',
  'SPL extension' => '',
  'This is required by encrypt and decrypt methods.' => '',
  'This is required if you are using MySQL database.' => '',
  'This is required if you are using PostgreSQL database.' => '',
  'This is required if you are using SQLite database.' => '',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => '',
);
