<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'GD extension with<br />FreeType support'=>'GD拡張 (FreeTypeサポート)',
  'GD installed<br />FreeType support not installed' => 'GDはインストールされています。<br />FreeTypeサポートはインストールされていません。',
  'GD not installed' => 'GDがインストールされていません。',
  '$_SERVER does not have {vars}.' => '$_SERVERは{vars}を持ちません。',
  '$_SERVER variable' => '$_SERVER変数',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"]はエントリスクリプトのパスと同じであるべきです。',
  'APC extension' => 'APC拡張',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => '全ての<a href="http://www.yiiframework.com/doc/api/#system.db">データベース関連クラス</a>',
  'DOM extension' => 'DOM拡張',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"]か$_SERVER["QUERY_STRING"]が存在するべきです。',
  'Mcrypt extension' => 'Mcrypt拡張',
  'Memcache extension' => 'Memcache拡張',
  'PCRE extension' => 'PCRE拡張',
  'PDO MySQL extension' => 'PDO MySQL拡張',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL拡張',
  'PDO SQLite extension' => 'PDO SQLite拡張',
  'PDO extension' => 'PDO拡張',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0かそれ以上が必要です。',
  'PHP version' => 'PHP版数',
  'Reflection extension' => 'Reflection拡張',
  'SOAP extension' => 'SOAP拡張',
  'SPL extension' => 'SPL拡張',
  'This is required by encrypt and decrypt methods.' => 'これは暗号化と複号に必要です。',
  'This is required if you are using MySQL database.' => 'これはMySQLデータベースをお使いなら必要です。',
  'This is required if you are using PostgreSQL database.' => 'これはPostgreSQLデータベースをお使いなら必要です。',
  'This is required if you are using SQLite database.' => 'これはSQLiteデータベースをお使いなら必要です。',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'URLパス情報を決定できません。$_SERVER["PATH_INFO"](もしくは$_SERVER["PHP_SELF"]と$_SERVER["SCRIPT_NAME"])が正しい値かどうか確認してください。',
);
