<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER に {vars} が存在しません。',
  '$_SERVER variable' => '$_SERVER 変数',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] は、エントリスクリプトのパスと同じでなければなりません。',
  'APC extension' => 'APC 拡張',
  'All <a href="https://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => '全ての<a href="https://www.yiiframework.com/doc/api/#system.db">データベース関連クラス</a>',
  'Ctype extension' => 'Ctype 拡張',
  'DOM extension' => 'DOM 拡張',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"] か $_SERVER["QUERY_STRING"] のどちらかが存在しなければなりません。',
  'Fileinfo extension' => 'Fileinfo 拡張',
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => 'GD 拡張<br />(+ FreeType サポート)<br />または<br />ImageMagick 拡張<br />(+ PNG サポート)',
  'GD installed,<br />FreeType support not installed' => 'GD インストール済み<br />FreeType サポート 未インストール',
  'GD or ImageMagick not installed' => 'GD も ImageMagick も未インストール',
  'Mcrypt extension' => 'Mcrypt 拡張',
  'Memcache extension' => 'Memcache 拡張',
  'PCRE extension' => 'PCRE 拡張',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => 'PDO MSSQL 拡張 (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)',
  'PDO MSSQL extension (pdo_dblib)' => 'PDO MSSQL 拡張 (pdo_dblib)',
  'PDO MSSQL extension (pdo_mssql)' => 'PDO MSSQL 拡張 (pdo_mssql)',
  'PDO MySQL extension' => 'PDO MySQL 拡張',
  'PDO ODBC extension' => 'PDO ODBC 拡張',
  'PDO Oracle extension' => 'PDO Oracle 拡張',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL 拡張',
  'PDO SQLite extension' => 'PDO SQLite 拡張',
  'PDO extension' => 'PDO 拡張',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0 以上が必要です。',
  'PHP version' => 'PHP バージョン',
  'Reflection extension' => 'Reflection 拡張',
  'Required by encrypt and decrypt methods.' => '暗号化と復号のメソッドに必要。',
  'Required for MIME-type validation' => 'MIME-type バリデーションに必要。',
  'Required for MSSQL database from GNU/Linux or other UNIX.' => 'GNU/Linux その他の UNIX で MSSQL データベース を使用する場合に必要。',
  'Required for MSSQL database from MS Windows' => 'MS Windows で MSSQL データベースを使用する場合に必要。',
  'Required for MSSQL database with the driver provided by Microsoft.' => 'Microsoft によって提供されているドライバで MSSQL データベースを使用する場合に必要。',
  'Required for MySQL database.' => 'MySQL データベースを使用する場合に必要。',
  'Required for Oracle database.' => 'Oracle データベースを使用する場合に必要。',
  'Required for PostgreSQL database.' => 'PostgreSQL データベースを使用する場合に必要。',
  'Required for SQLite database.' => 'SQLite データベースを使用する場合に必要。',
  'Required for secure password storage.' => '安全なパスワード保存に必要。',
  'Required in case database interaction will be through ODBC layer.' => 'データベースへのアクセスを ODBC レイヤーを通して行う場合に必要。',
  'SOAP extension' => 'SOAP 拡張',
  'SPL extension' => 'SPL 拡張',
  'To use memcached set <a href="https://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => 'memcached を使用するためには <a href="https://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> を <code>true</code> に設定して下さい。',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'URL パス情報を決定できません。$_SERVER["PATH_INFO"] (もしくは $_SERVER["PHP_SELF"] と $_SERVER["SCRIPT_NAME"]) が正しい値かどうか確認してください。',
  'crypt() CRYPT_BLOWFISH option' => 'crypt() CRYPT_BLOWFISH オプション',
);
