<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Home' => 'Naslovnica',
  'The button type "{type}" is not supported.' => 'Tip gumba "{type}" nije podržan.',
  'Are you sure you want to delete this item?' => 'Da li ste sigurni da želite obrisati stavku?',
  'Delete' => 'Obrišite',
  'Displaying {start}-{end} of {count} result(s).' => 'Prikazujem {start}-{end} od {count} rezultata.',
  'Either "name" or "value" must be specified for CDataColumn.' => '"ime" ili "vrijednost" moraju biti navedeni za CDataColumn.',
  'No results found.' => 'Nema pronađenih rezultata.',
  'Not set' => 'Nije postavljen',
  'Please specify the "attributes" property.' => 'Molimo odredite "atribute" nekretnine.',
  'Please specify the "data" property.' => 'Molimo odredite "podatke"-nekretnine.',
  'Sort by: ' => 'Poredaj po:',
  'The "dataProvider" property cannot be empty.' => '"dataProvider" nekretnina ne može biti prazno.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Atribut mora biti određen u formatu "Ime:Tip:Naziv", gdje su "Tip" i "Naziv" neobavezani.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Stupac mora biti određen u formatu "Ime:Tip:Naziv", gdje su "Tip" i "Naziv" neobavezani.',
  'The property "itemView" cannot be empty.' => 'Nekretnina "itemView" ne može biti prazna.',
  'Total {count} result(s).' => 'Ukupno {count} rezultat(a)',
  'Update' => 'Ažurirajte',
  'View' => 'Pregled',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} mora biti određena vrijednosti "modelom" i "atributom" ili "imenom" nekretnine.',
);