<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure to delete this item?' => 'Bạn có chắc là muốn xóa?',
  'Delete' => 'Xóa',
  'Displaying {start}-{end} of {count} result(s).' => 'Hiển thị {start}-{end} của {count} kết quả.',
  'No' => 'No',
  'No results found.' => 'Không có dữ liệu.',
  'Not set' => 'Chưa có thông tin',
  'Please specify the "attributes" property.' => 'Xin hãy chỉ rõ nội dung "attributes".',
  'Please specify the "model" property.' => 'Xin hãy chỉ rõ nội dung "model".',
  'Sort by: ' => 'Sắp theo:',
  'The "dataProvider" property cannot be empty.' => '"dataProvider" không được phép rỗng.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Thuộc tính phải được định nghĩa theo dạng "Name:Type:Label", với "Type" và "Label" là tùy chọn.',
  'The property "itemView" cannot be empty.' => 'Thuộc tính "itemView" không được phép rỗng.',
  'Total {count} result(s).' => 'Tất cả {count} kết quả',
  'Unknown type "{type}".' => 'Không hiểu loại "{type}".',
  'Update' => 'Cập nhật',
  'View' => 'Xem',
  'Yes' => 'Yes',
  '{class} must specify "model" and "attribute" or "name" property values.' => 'Lới {class} phải xác định rõ giá trị "model" và "attribute" hoặc "name".',
);
