<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Home' => 'Главная',
  'The button type "{type}" is not supported.' => 'Тип кнопки "{type}" не поддерживается.',
  'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить данный элемент?',
  'Delete' => 'Удалить',
  'Displaying {start}-{end} of {count} result(s).' => 'Элементы {start}—{end} из {count}.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Для CDataColumn необходимо указать "name" или "value".',
  'No results found.' => 'Нет результатов.',
  'Not set' => 'Не задан',
  'Please specify the "attributes" property.' => 'Определите свойство "attributes".',
  'Please specify the "data" property.' => 'Определите свойство "data".',
  'Sort by: ' => 'Сортировка: ',
  'The "dataProvider" property cannot be empty.' => 'Свойство "dataProvider" не может быть пустым.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Атрибут должен быть указан в формате "Имя:Тип:Заголовок". "Тип" и "Заголовок" не обязательны.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Столбец должен быть указан в формате "Name:Type:Label". "Тип" и "Заголовок" не обязательны.',
  'The property "itemView" cannot be empty.' => 'Свойство "itemView" не может быть пустым.',
  'Total {count} result(s).' => 'Всего результатов: {count}.',
  'Update' => 'Редактировать',
  'View' => 'Просмотреть',
  '{class} must specify "model" and "attribute" or "name" property values.' => 'В классе {class} должны быть заданы значения свойств "model" и "attribute", либо значение "name".',
);
