<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER indeholder ikke {vars}.',
  '$_SERVER variable' => '$_SERVER variabel',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] skal være som stien til startscriptet.',
  'APC extension' => 'APC extension',
  'All <a href="https://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Alle <a href="https://www.yiiframework.com/doc/api/#system.db">DB-relaterede klasser</a>',
  'Ctype extension' => 'Ctype extension',
  'DOM extension' => 'DOM extension',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"] eller $_SERVER["QUERY_STRING"] skal eksistere.',
  'Fileinfo extension' => 'Fileinfo extension',
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => 'GD extension med<br />FreeType support<br />eller ImageMagick<br />extension med<br />PNG support',
  'GD installed,<br />FreeType support not installed' => 'GD installeret,<br />FreeType support er ikke installeret',
  'GD or ImageMagick not installed' => 'GD eller ImageMagick er ikke installeret',
  'Mcrypt extension' => 'Mcrypt extension',
  'Memcache extension' => 'Memcache extension',
  'PCRE extension' => 'PCRE extension',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => 'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)',
  'PDO MSSQL extension (pdo_dblib)' => 'PDO MSSQL extension (pdo_dblib)',
  'PDO MSSQL extension (pdo_mssql)' => 'PDO MSSQL extension (pdo_mssql)',
  'PDO MySQL extension' => 'PDO MYSQL extension',
  'PDO Oracle extension' => 'PDO Oracle extension',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL extension',
  'PDO SQLite extension' => 'PDO SQLite extension',
  'PDO extension' => 'PDO extension',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0 eller nyere er påkrævet.',
  'PHP version' => 'PHP version',
  'Reflection extension' => 'Reflection extension',
  'Required by encrypt and decrypt methods.' => 'Påkrævet af encrypt og decrypt funktioner.',
  'Required for MIME-type validation' => 'Påkrævet for MIME-type validering',
  'Required for MSSQL database from GNU/Linux or other UNIX.' => 'Påkrævet for MSSQL database fra GNU/Linux eller andre UNIX.',
  'Required for MSSQL database from MS Windows' => 'Påkrævet for MSSQL database fra MS Windows',
  'Required for MSSQL database with the driver provided by Microsoft.' => 'Påkrævet for MSSQL database med driveren leveret af Microsoft.',
  'Required for MySQL database.' => 'Påkrævet for MySQL database.',
  'Required for Oracle database.' => 'Påkrævet for Oracle database.',
  'Required for PostgreSQL database.' => 'Påkrævet for PostgreSQL database.',
  'Required for SQLite database.' => 'Påkrævet for SQLite database.',
  'Required for secure password storage.' => 'Påkrævet for sikkert kodeordslager.',
  'SOAP extension' => 'SOAP extension',
  'SPL extension' => 'SPL extension',
  'To use memcached set <a href="https://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => 'For at bruge memcached sæt <a href="https://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> til <code>true</code>.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Kunne ikke bestemme path info. Venligst tjek at $_SERVER["PATH_INFO"] (eller $_SERVER["PHP_SELF"] og $_SERVER["SCRIPT_NAME"]) indeholder passende værdier.',
  'crypt() CRYPT_BLOWFISH option' => 'crypt() CRYPT_BLOWFISH option',
);
