<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure you want to delete this item?' => 'Er du sikker på at du vil slette dette element?',
  'Delete' => 'Slet',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Viser {start}-{end} af 1 resultat.|Viser {start}-{end} af {count} resultater.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Enten "name" eller "value" skal være defineret for CDataColumn.',
  'Home' => 'Start',
  'No results found.' => 'Ingen resultater fundet.',
  'Not set' => 'Ikke angivet',
  'Please specify the "attributes" property.' => 'Angiv venligst egenskaben "attributes".',
  'Please specify the "data" property.' => 'Angiv venligst egenskaben "data".',
  'Sort by: ' => 'Sorter efter: ',
  'The "dataProvider" property cannot be empty.' => 'Egenskaben "dataProvider" kan ikke være tom.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Attributten skal være specificeret i formatet "Name:Type:Label", hvor "Type" og "Label" er valgfrie.',
  'The button type "{type}" is not supported.' => 'Knaptypen "{type}" er ikke supporteret.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Kolonnen skal være specificeret i formatet "Name:Type:Label", hvor "Type" og "Label" er valgfrie.',
  'The property "itemView" cannot be empty.' => 'Egenskaben "itemView" kan ikke være tom.',
  'The property filterSelector should be defined.' => 'Egenskaben filterSelector burde være defineret.',
  'The property updateSelector should be defined.' => 'Egenskaben updateSelector burde være defineret.',
  'Total 1 result.|Total {count} results.' => 'Total 1 resultat.|Total {count} resultater.',
  'Update' => 'Opdater',
  'View' => 'Vis',
  '{class} must specify "model" and "{attribute}" or "{name}" property values.' => '{class} skal specificere værdier for egenskaberne "model" og "{attribute}" eller "{name}".' ,
);
