<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id$
 */
return array (
  'PHP version' => 'PHP版本',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0或更高版本是必须的。',
  '$_SERVER variable' => '$_SERVER变量',
  'Reflection extension' => 'Reflection扩展模块',
  'PCRE extension' => 'PCRE扩展模块',
  'SPL extension' => 'SPL扩展模块',
  'DOM extension' => 'DOM扩展模块',
  'PDO extension' => 'PDO扩展模块',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => '所有和<a href="http://www.yiiframework.com/doc/api/#system.db">数据库相关的类</a>',
  'Memcache extension' => 'Memcache扩展模块',
  'APC extension' => 'APC扩展模块',
  'Mcrypt extension' => 'Mcrypt扩展模块',
  'SOAP extension' => 'SOAP扩展模块',
  'GD extension' => 'GD扩展模块',
  '$_SERVER does not have {vars}.' => '$_SERVER缺少{vars}。',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"]必须与入口文件路径一致。',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"]或$_SERVER["QUERY_STRING"]必须存在。',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => '无法确定URL path info。请检查$_SERVER["PATH_INFO"]（或$_SERVER["PHP_SELF"]和$_SERVER["SCRIPT_NAME"]）的值是否正确。',
  'PDO SQLite extension' => 'PDO SQLite扩展模块',
  'This is required if you are using SQLite database.' => '如果使用SQLite数据库，这是必须的。',
  'PDO MySQL extension' => 'PDO MySQL扩展模块',
  'This is required if you are using MySQL database.' => '如果使用MySQL数据库，这是必须的。',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL扩展模块',
  'This is required if you are using PostgreSQL database.' => '如果使用PostgreSQL数据库，这是必须的。',
);
