<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER no contiene {vars}',
  '$_SERVER variable' => 'variable de $_SERVER',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] debe ser igual a la ruta del script de entrada',
  'APC extension' => 'Extensión APC',
  'All <a href="https://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Todas las <a href="https://www.yiiframework.com/doc/api/#system.db">clases relacionadas con DB</a>',
  'Ctype extension' => 'Extensión Ctype',
  'DOM extension' => 'Extensión DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"] o $_SERVER["QUERY_STRING"] deben existir.',
  'Fileinfo extension' => 'Extensión Fileinfo',
  'GD extension with<br />FreeType support<br />or ImageMagick<br />extension with<br />PNG support' => 'Extensión GD con<br />soporte FreeType<br />o extensión<br />ImageMagick con<br />soporte PNG',
  'GD installed,<br />FreeType support not installed' => 'GD instalado,<br />soporte FreeType no instalado',
  'GD or ImageMagick not installed' => 'GD o ImageMagick no instalados',
  'Mcrypt extension' => 'Extensión Mcrypt',
  'Memcache extension' => 'Extensión Memcache',
  'PCRE extension' => 'Extensión PCRE',
  'PDO MSSQL extension (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)' => 'Extensión PDO MSSQL (<a href="http://sqlsrvphp.codeplex.com/">pdo_sqlsrv</a>)',
  'PDO MSSQL extension (pdo_dblib)' => 'Extensión PDO MSSQL (pdo_dblib)',
  'PDO MSSQL extension (pdo_mssql)' => 'Extensión PDO MSSQL (pdo_mssql)',
  'PDO MySQL extension' => 'Extensión PDO MySQL',
  'PDO Oracle extension' => 'Extensión PDO Oracle ',
  'PDO PostgreSQL extension' => 'Extension PDO PostgreSQL',
  'PDO SQLite extension' => 'Extensión PDO SQLite',
  'PDO extension' => 'Extensión PDO',
  'PHP 5.1.0 or higher is required.' => 'Requiere PHP 5.1.0 o superior',
  'PHP version' => 'Versión PHP',
  'Reflection extension' => 'Extensión Reflection',
  'Required by encrypt and decrypt methods.' => 'Requerida para los métodos encrypt y decrypt',
  'Required for MIME-type validation' => 'Requerida para validación de tipos MIME',
  'Required for MSSQL database from GNU/Linux or other UNIX.' => 'Requerida para base de datos MSSQL desde GNU/Linux u otro UNIX.',
  'Required for MSSQL database from MS Windows' => 'Requerida para base de datos MSSQL desde MS Windows',
  'Required for MSSQL database with the driver provided by Microsoft.' => 'Requerida para base de datos MSSQL con el manejador provisto por Microsoft.',
  'Required for MySQL database.' => 'Requerida para base de datos MySQL',
  'Required for Oracle database.' => 'Requerida para base de datos Oracle',
  'Required for PostgreSQL database.' => 'Requerida para base de datos PostgreSQL',
  'Required for SQLite database.' => 'Requerida para base de datos SQLite',
  'SOAP extension' => 'Extensión SOAP',
  'SPL extension' => 'Extensión SPL',
  'To use memcached set <a href="https://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => 'Para usar memcached asigna <a href="https://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> a <code>true</code>.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'No es posible determinar la ruta de información del URL. Por favor asegúrese que $_SERVER["PATH_INFO"] o ($_SERVER["PHP_SELF"] y $_SERVER["SCRIPT_NAME"]) contenga/n un valor correcto.',
);
