<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER nie posiada zmiennej(nych) {vars}',
  '$_SERVER variable' => 'zmienna $_SERVER',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] musi byæ taki sam jak œcie¿ka pliku skryptu wejœciowego.',
  'APC extension' => 'rozszerzenie APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Wszystkie <a href="http://www.yiiframework.com/doc/api/#system.db">klasy bazodanowe</a>',
  'DOM extension' => 'rozszerzenie DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Zarówno $_SERVER["REQUEST_URI"] jak i $_SERVER["QUERY_STRING"] musz¹ istnieæ.',
  'GD extension' => 'rozszerzenie GD',
  'Mcrypt extension' => 'rozszerzenie Mcrypt',
  'Memcache extension' => 'rozszerzenie Memcache',
  'PCRE extension' => 'rozszerzenie PCRE',
  'PDO MySQL extension' => 'rozszerzenie PDO MySQL',
  'PDO PostgreSQL extension' => 'rozszerzenie PDO PostgreSQL ',
  'PDO SQLite extension' => 'rozszerzenie PDO SQLite ',
  'PDO extension' => 'rozszerzenie PDO',
  'PHP 5.1.0 or higher is required.' => 'Wymagane jest PHP w wersji 5.1.0 lub wy¿szej',
  'PHP version' => 'wersja PHP',
  'Reflection extension' => 'rozszerzenie Reflection',
  'SOAP extension' => 'rozszerzenie SOAP',
  'SPL extension' => 'rozszerzenie SPL',
  'This is required by encrypt and decrypt methods.' => 'Wymagane przez metody szyfruj¹ce i deszyfruj¹ce.',
  'This is required if you are using MySQL database.' => 'Wymagane jeœli u¿ywasz bazy danych MySQL.',
  'This is required if you are using PostgreSQL database.' => 'Wymagane jeœli u¿ywasz bazy danych PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Wymagane jeœli u¿ywasz bazy danych SQLite',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Nie mo¿na okreœliæ œcie¿ki URL. Upewnij siê, ¿e $_SERVER["PATH_INFO"] (lub $_SERVER["PHP_SELF"] oraz $_SERVER["SCRIPT_NAME"]) zawieraj¹ odpowiednie wartoœci.',
);
