<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @author Srinivasan A Paul Joseph <sapauljoseph@gmail.com>
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER {vars} ஐக் கொண்டிருக்கவில்லை.',
  '$_SERVER variable' => '$_SERVER மாறிலி',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] வழித்தடம் முதன்மை வழித்தடத்திலிருக்க வேண்டும்.',
  'APC extension' => 'APC நீட்சி',
  'All <a href="https://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => '<a href="https://www.yiiframework.com/doc/api/#system.db">தகவல்தளம்</a> சம்பந்தப்பட்ட உருக்கள் அனைத்தும்',
  'DOM extension' => 'DOM நீட்சி',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"] அல்லது $_SERVER["QUERY_STRING"] கண்டிப்பாக இருக்க வேண்டும்.',
  'GD extension with<br />FreeType support' => 'GD நீட்சி<br />FreeType பயன்பாட்டுடன்',
  'GD installed<br />FreeType support not installed' => 'GD நிறுவப்பட்டுள்ளது<br />FreeType பயன்பாடு நிறுவப்பட்டிருக்கவில்லை',
  'GD not installed' => 'GD நிறுவப்பட்டிருக்கவில்லை',
  'Mcrypt extension' => 'Mcrypt நீட்சி',
  'Memcache extension' => 'Memcache நீட்சி',
  'PCRE extension' => 'PCRE நீட்சி',
  'PDO MySQL extension' => 'PDO MySQL நீட்சி',
  'PDO PostgreSQL extension' => 'PDO PostgreSQL நீட்சி',
  'PDO SQLite extension' => 'PDO SQLite நீட்சி',
  'PDO extension' => 'PDO நீட்சி',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0 அல்லது மேன்மையானது இருத்தல் வேண்டும்.',
  'PHP version' => 'PHP பதிப்பு',
  'Reflection extension' => 'Reflection நீட்சி',
  'SOAP extension' => 'SOAP நீட்சி',
  'SPL extension' => 'SPL நீட்சி',
  'This is required by encrypt and decrypt methods.' => 'இது encrypt மற்றும் decrypt பயன்பாடுகளுக்குத் தேவையானது.',
  'This is required if you are using MySQL database.' => 'நீங்கள் MySQL தகவல்தளத்தை உபயோகப்படுத்தினால் இது தேவையானது.',
  'This is required if you are using PostgreSQL database.' => 'நீங்கள் PostgreSQL தகவல்தளத்தை உபயோகப்படுத்தினால் இது தேவையானது.',
  'This is required if you are using SQLite database.' => 'நீங்கள் SQLite தகவல்தளத்தை உபயோகப்படுத்தினால் இது தேவையானது.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'முகவரியின் தகவல்களைப் பெற இயலவில்லை. தயவுசெய்து $_SERVER["PATH_INFO"] (அல்லது $_SERVER["PHP_SELF"] மற்றும் $_SERVER["SCRIPT_NAME"]) தகவல்களை சரிபார்க்கவும்.',
);
